project:
  type: book
  output-dir: _book

book:
  title: "Meta-Analysis Workshop"
  author: "Daniel W.A. Noble, Patrice Pottier"
  date: today
  sidebar:
    style: docked
    collapse-level: 1
    logo: figs/logo.png
  chapters:
    - part: "**Welcome**"
      chapters:
        - index.qmd
    - part: "**Fundamentals of Meta-Analysis**"
      chapters:
        - introduction-to-meta.qmd
        - systematic_review.qmd
    - part: "**Effect Sizes**"
      chapters:
        - effect-size.qmd
        - nuis-het.qmd
    - part: "**Statistical Models**"
      chapters:
        - fixed-vs-random.qmd
        - multi-level.qmd
    - part: "**Heterogeneity**"
      chapters:
        - het.qmd
    - part: "**Meta-Regression**"
      chapters:
        - metaregression.qmd
    - part: "**Advanced Topics**"
      chapters:
        - phylo.qmd
        - complex-nonind.qmd
    - part: "**Publication Bias**"
      chapters:
        - pub-bias1.qmd
        - pub-bias2.qmd
  repo-url: https://github.com/noble-lab/meta-analysis_workshop
  sharing: [twitter, facebook, linkedin]
  
bibliography: bib/refs.bib
csl: bib/the-journal-of-experimental-biology.csl

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: false
    code-fold: show
    code-tools: true
    code-copy: true
    
knitr:
  opts_chunk:
    echo: true
    cache: false
    message: false
    warning: false
