# **Welcome** {.unnumbered}

This book contains materials for a 1.5-2 day meta-analysis workshop run by [Daniel Noble](https://sites.google.com/view/noblelab/home) from The [Australian National University](https://www.anu.edu.au/) and [Patrice Pottier](https://patricepottier.academicwebsite.com/) from [Gothenburg University](https://www.gu.se/en). The workshop provides comprehensive coverage of meta-analytic approaches and methods, from basic concepts to advanced topics.

# **Workshop Overview**

Over the course of this workshop, you will learn:

- **Systematic Review Protocols and Data Curation**: How to conduct systematic searches and curate data for meta-analysis
- **Fundamentals of meta-analysis**: Understanding what meta-analysis is and when to use it
- **Effect sizes**: How to calculate and interpret different effect size metrics
- **Statistical models**: Fixed-effect vs. random-effects models and when to use each
- **Heterogeneity**: Understanding and quantifying variation in effect sizes
- **Meta-regression**: Exploring moderators of effect sizes
- **Publication bias**: Detecting and accounting for biases in the literature
- **Advanced topics**: Multi-level models, complex non-independence, phylogenetic meta-analysis

Each chapter contains:

- Theoretical background and explanations
- Worked examples with R code
- Practical exercises

You can navigate through the chapters using the sidebar menu. Code snippets can be copied using the copy button in the top-right corner of each code block.

The material covered here is geared towards researchers interested in conducting a meta-analysis in the fields of physiology, ecology and evolution. Having said that, all the principles learnt here apply to meta-analyses conducted in any research field.

Meta-analysis is a huge, complex topic. We can only hope to touch the surface of how it's done in a single workshop. As such, we will only have time to superficially cover the process of systematic searching and data curation and we may not get to cover the more advanced topics. 

For any meta-analysis, systematic searches are important for a comprehensive, transparent and reproducible meta-analyses. The question needs to be clearly defined, and systematic searches need to be well documented, carefully refined, have detailed inclusion/exclusion criteria so that they may be repeated in the future. [Foo *et al.* 2021](https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/2041-210X.13654) is an excellent resource for this stage of a meta-analysis. We also recommend following the PRISMA Eco-Evo protocol proposed by [O'Dea *et al.* 2020](https://onlinelibrary.wiley.com/doi/abs/10.1111/brv.12721). For data curation in preparation for a meta-analysis, we recommend following advice by [Schwanz *et al.* 2022](https://journals.biologists.com/jeb/article/225/Suppl_1/jeb243295/274297/Best-practices-for-building-and-curating-databases).

We also provide a list of [useful readings](#read) and [software](https://daniel1noble.github.io/meta-workshop/software) for earlier elements of a meta-analysis (e.g., extracting data from figures literature searching, snowballing etc). Please cite these software in your meta-analysis. Many of the authors spend a huge amount of time developing and maintaining these free resources. They are as important to cite as the statistical software used to analyse the data. 

# **Prerequisites**

This workshop assumes you have:

- Basic familiarity with R and RStudio
- Understanding of fundamental statistical concepts
- Interest in synthesizing research findings

# **Preparation for the workshop**

In preparation for the workshop, we highly recommend the following background knowledge as we will use the `metafor` *R* package ([Viechtbauer 2010](https://www.jstatsoft.org/article/view/v036i03)) as our primary method for constructing meta-analytic models:

* Understanding the basis for doing a meta-analysis (see [Introduction: why do meta-analysis?](introduction-to-meta.qmd))
* Familiarise yourself with the `metafor` package and its functions (see [`metafor` website](https://wviechtb.github.io/metafor/))
* As our workshop focuses on real-world data (and the complexities that it comes with) we highly recommend working through the ["Meta-Analysis in *R* with {metafor}](https://www.youtube.com/watch?v=IkduL5iRdqo&t=1602s&ab_channel=UseROslo) tutorial from "UseR Olso". Having said that, this is not essential as we will walk participants through the code we provide. 

# **Recommended readings** {#read}

* Ten appraisal questions for biologist conducting meta-analysis studies ([Nakagawa *et al.* 2017](https://bmcbiol.biomedcentral.com/articles/10.1186/s12915-017-0357-7))
* Meta-analytic approaches and effect sizes to account for ‘nuisance heterogeneity’ in comparative physiology ([Noble *et al.* 2022](https://journals.biologists.com/jeb/article/225/Suppl_1/jeb243225/274278/Meta-analytic-approaches-and-effect-sizes-to))
* Methodological issues and advances in biological meta-analysis ([Nakagawa & Santos 2012](https://link.springer.com/article/10.1007/s10682-012-9555-5))
* Non‐independence and sensitivity analyses in ecological and evolutionary meta‐analyses ([Noble *et al.* 2017](https://onlinelibrary.wiley.com/doi/abs/10.1111/mec.14031))
* Importance of phylogeny in ecological and evolutionary meta-analyses ([Cinar *et al.* 2021](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.13760))
* Testing for publication bias in ecological and evolutionary meta-analyses ([Nakagawa *et al.* 2021](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.13724))

For a comprehensive guide on meta-analysis starting from a scoping study to writing a meta-analysis paper, see the YouTube [Hard-Boiled Synthesis](https://www.youtube.com/c/LajeunesseLab/featured) course by Marc Lajeunesse. It covers materials in detail beyond our workshop.

# **Acknowledgements**
We'd like to acknowledge the many people who have contributed to the development of this workshop over the years, especially [Shinichi Nakagawa](https://www.cossee.org/shinichi-nakagawa.html), [Malgorzata Lagisz](https://mlagisz.weebly.com/), [Nicholas Wu](https://wunicholas.wixsite.com/home), as well as [Wolfgang Viechtbauer](https://www.wvbauer.com) and [Marc Lajeunesse](https://www.usf.edu/arts-sciences/departments/ib/people/faculty/marc-lajeunesse.aspx) who have provided valuable online resources for teaching. The materials in this workshop have been developed and refined over many years of teaching and research, and we are grateful for the contributions of all those colleagues who have helped shape it.

# **Contact**

For questions or feedback, please contact [Dan](mailto:daniel.noble@anu.edu.au).
