<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Bayesian Meta-analysis – Meta-Analysis Workshop</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./phylo.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-47d0440b87685b87fa0f37ef00e16435.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./complex-nonind.html"><strong>Advanced Topics</strong></a></li><li class="breadcrumb-item"><a href="./bayes_meta.html"><span class="chapter-title">Bayesian Meta-analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./figs/logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Meta-Analysis Workshop</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/daniel1noble/meta-analysis_workshop" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text"><strong>Welcome</strong></span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Welcome</strong></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text"><strong>Fundamentals of Meta-Analysis</strong></span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction-to-meta.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introduction to Meta-analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./systematic_review.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Systematic Review</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text"><strong>Effect Sizes</strong></span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./effect-size.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Calculating and interpreting effect sizes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nuis-het.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Nuisance heterogeneity</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text"><strong>Statistical Models</strong></span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fixed-vs-random.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Fixed versus Random Effects Meta-analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multi-level.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Multi-level Meta-analysis</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text"><strong>Heterogeneity</strong></span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./het.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Heterogeneity in Meta-analysis</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text"><strong>Meta-Regression</strong></span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./metaregression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Multi-level Meta-regression</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text"><strong>Publication Bias</strong></span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pub-bias1.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Publication Bias in Meta-analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pub-bias2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Publication Bias: Analytical Approaches</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text"><strong>Advanced Topics</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./complex-nonind.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Complex Non-independence in Meta-analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./phylo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Phylogenetic Meta-analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bayes_meta.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Bayesian Meta-analysis</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction-to-bayesian-meta-analysis" id="toc-introduction-to-bayesian-meta-analysis" class="nav-link active" data-scroll-target="#introduction-to-bayesian-meta-analysis"><strong>Introduction to Bayesian Meta-analysis</strong></a></li>
  <li><a href="#formal-definition-of-the-bayesian-phylogenetic-meta-analytic-model" id="toc-formal-definition-of-the-bayesian-phylogenetic-meta-analytic-model" class="nav-link" data-scroll-target="#formal-definition-of-the-bayesian-phylogenetic-meta-analytic-model"><strong>Formal Definition of the Bayesian Phylogenetic Meta-analytic Model</strong></a></li>
  <li><a href="#example-bayesian-phylogenetic-meta-analysis" id="toc-example-bayesian-phylogenetic-meta-analysis" class="nav-link" data-scroll-target="#example-bayesian-phylogenetic-meta-analysis"><strong>Example: Bayesian Phylogenetic Meta-analysis</strong></a>
  <ul class="collapse">
  <li><a href="#format-raw-data-for-analysis" id="toc-format-raw-data-for-analysis" class="nav-link" data-scroll-target="#format-raw-data-for-analysis">Format raw data for analysis</a></li>
  <li><a href="#build-the-tree-and-the-phylogenetic-correlation-matrix" id="toc-build-the-tree-and-the-phylogenetic-correlation-matrix" class="nav-link" data-scroll-target="#build-the-tree-and-the-phylogenetic-correlation-matrix">Build the tree and the phylogenetic correlation matrix</a></li>
  <li><a href="#specify-priors" id="toc-specify-priors" class="nav-link" data-scroll-target="#specify-priors">Specify priors</a></li>
  <li><a href="#fit-the-model-in-brms" id="toc-fit-the-model-in-brms" class="nav-link" data-scroll-target="#fit-the-model-in-brms">Fit the model in <code>brms</code></a></li>
  <li><a href="#check-mcmc-diagnostics" id="toc-check-mcmc-diagnostics" class="nav-link" data-scroll-target="#check-mcmc-diagnostics">Check MCMC diagnostics</a></li>
  <li><a href="#posterior-summaries" id="toc-posterior-summaries" class="nav-link" data-scroll-target="#posterior-summaries">Posterior summaries</a></li>
  </ul></li>
  <li><a href="#extracting-posterior-distributions-and-derived-quantities" id="toc-extracting-posterior-distributions-and-derived-quantities" class="nav-link" data-scroll-target="#extracting-posterior-distributions-and-derived-quantities"><strong>Extracting Posterior distributions and Derived Quantities</strong></a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><strong>References</strong></a></li>
  <li><a href="#session-information" id="toc-session-information" class="nav-link" data-scroll-target="#session-information"><strong>Session Information</strong></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./complex-nonind.html"><strong>Advanced Topics</strong></a></li><li class="breadcrumb-item"><a href="./bayes_meta.html"><span class="chapter-title">Bayesian Meta-analysis</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-title">Bayesian Meta-analysis</span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction-to-bayesian-meta-analysis" class="level2">
<h2 class="anchored" data-anchor-id="introduction-to-bayesian-meta-analysis"><strong>Introduction to Bayesian Meta-analysis</strong></h2>
<p>Throughout the previous chapters we have estimated meta-analytic models with <a href="./fixed-vs-random.html"><code>metafor</code></a> using restricted maximum likelihood (REML). The model objects we obtained — overall effects, variance components, confidence intervals — are <em>frequentist</em> estimates.</p>
<p>A <strong>Bayesian</strong> meta-analysis instead returns a <em>posterior distribution</em> for every parameter in the model, by combining the data (through the likelihood) with prior beliefs about plausible parameter values. This re-framing brings several practical benefits when synthesising data in ecology, evolution and physiology:</p>
<ul>
<li><strong>Honest uncertainty for variance components.</strong> REML-based confidence intervals for variance components (e.g.&nbsp;<span class="math inline">\(\tau^2\)</span>, phylogenetic <span class="math inline">\(\sigma_{a}^2\)</span>) can be poorly behaved when the number of studies is small or when an estimate is near the boundary of zero <span class="citation" data-cites="Burkner2017">(<a href="#ref-Burkner2017" role="doc-biblioref">Bürkner, 2017</a>)</span>. Posterior credible intervals do not have this problem.</li>
<li><strong>Propagating uncertainty more easily.</strong> The Bayesian framing lets you propagate uncertainty into derived quantities (e.g.&nbsp;between-study heterogeneity ratios, prediction intervals) and gives you more flexibility in the derived quantities you present within your paper.</li>
<li><strong>Easy to extend.</strong> Once we have the Bayesian machinery in place, adding non-Gaussian likelihoods, missing-data models, or measurement-error structures is mostly a one-line change.</li>
</ul>
<p>Bayesian methods are well-established in ecological and evolutionary meta-analysis, not just a fashionable alternative, but are not used as often as frequentist methods. <span class="citation" data-cites="Pappalardo2020">Pappalardo et al. (<a href="#ref-Pappalardo2020" role="doc-biblioref">2020</a>)</span> compared traditional REML and Bayesian fits across a range of ecological meta-analytic scenarios and found that the two approaches generally recover the same overall effect, but that the Bayesian fit gives better-calibrated uncertainty when the number of studies is small or when variance components are near zero. Similarly, <span class="citation" data-cites="Nakagawa2022comment">Nakagawa et al. (<a href="#ref-Nakagawa2022comment" role="doc-biblioref">2022</a>)</span>, in their re-analysis of the simulations of <span class="citation" data-cites="Song2020">Song et al. (<a href="#ref-Song2020" role="doc-biblioref">2020</a>)</span>, included a Bayesian multilevel model alongside the frequentist alternatives and showed that it can help control the inflated Type I error rates that arise when effect sizes are non-independent (see the simulation figure in their Comment). Together, these papers position Bayesian multilevel models as a robust, often preferable, complement to REML for the kinds of complex, multi-strata data routinely synthesised in our field.</p>
<p>In this tutorial we use the <a href="https://paulbuerkner.com/brms/"><code>brms</code></a> R package <span class="citation" data-cites="Burkner2017">(<a href="#ref-Burkner2017" role="doc-biblioref">Bürkner, 2017</a>)</span>. <code>brms</code> provides a <code>lme4</code>-style formula interface to the <a href="https://mc-stan.org/">Stan</a> probabilistic programming language, which means the syntax will look familiar if you have used <code>lmer</code> or <code>metafor::rma.mv</code>. We re-fit the <strong>phylogenetic multilevel meta-analysis</strong> from the <a href="./phylo.html">previous chapter</a> so you can directly compare the Bayesian and REML estimates on the same data.</p>
</section>
<section id="formal-definition-of-the-bayesian-phylogenetic-meta-analytic-model" class="level2">
<h2 class="anchored" data-anchor-id="formal-definition-of-the-bayesian-phylogenetic-meta-analytic-model"><strong>Formal Definition of the Bayesian Phylogenetic Meta-analytic Model</strong></h2>
<p><a href="./phylo.html">Recall</a> the phylogenetic multilevel meta-analytic model:</p>
<p><span class="math display">\[
\begin{aligned}
y_{i} &amp;= \mu + s_{j[i]} + spp_{k[i]} + a_{k[i]} + e_{i} + m_{i} \\
m_{i} &amp;\sim N(0, v_{i}\textbf{I}) \\
s_{j} &amp;\sim N(0, \tau^2\textbf{I}) \\
spp_{k} &amp;\sim N(0, \sigma_{k}^2\textbf{I}) \\
a_{k} &amp;\sim N(0, \sigma_{a}^2\textbf{A}) \\
e_{i} &amp;\sim N(0, \sigma_{e}^2\textbf{I})
\end{aligned}
\]</span></p>
<p>The model is structurally identical to the one we fit with <code>metafor::rma.mv</code>. To make it Bayesian we add <strong>priors</strong> on every estimated parameter:</p>
<p><span class="math display">\[
\begin{aligned}
\mu &amp;\sim N(0, 1) \\
\tau, \sigma_{k}, \sigma_{a}, \sigma_{e} &amp;\sim t^{+}_{3}(0, 2.5)
\end{aligned}
\]</span></p>
<p>These are <em>weakly informative</em> priors. For an effect size on the Fisher’s <span class="math inline">\(Z_r\)</span> scale, <span class="math inline">\(\mu \sim N(0, 1)\)</span> says we expect the overall correlation to be near zero with a standard deviation that easily covers the range of biologically plausible effects. For each random-effect standard deviation we use a half-Student-t prior with 3 degrees of freedom and scale 2.5 — written <span class="math inline">\(t^{+}_{3}(0, 2.5)\)</span>. This is the conventional default for variance components in <code>brms</code> and Stan: it concentrates posterior mass on small, biologically plausible SDs while keeping heavier tails than a half-Normal, so the prior does not pull large variance components down toward zero when the data really do support them. We will discuss how to override these defaults below.</p>
</section>
<section id="example-bayesian-phylogenetic-meta-analysis" class="level2">
<h2 class="anchored" data-anchor-id="example-bayesian-phylogenetic-meta-analysis"><strong>Example: Bayesian Phylogenetic Meta-analysis</strong></h2>
<p><img src="./figs/WuSeebacher.png" class="img-fluid"></p>
<section id="format-raw-data-for-analysis" class="level3">
<h3 class="anchored" data-anchor-id="format-raw-data-for-analysis">Format raw data for analysis</h3>
<p>We re-use the dispersal data set (Z-transformed correlation coefficients, <span class="math inline">\(Z_r\)</span>) from <a href="https://www.nature.com/articles/s42003-022-03055-y"><span class="citation" data-cites="WuSeebacher2022">Wu and Seebacher (<span>2022</span>)</span></a> introduced in the <a href="./effect-size.html">Effect Size tutorial</a> and analysed with REML in the <a href="./phylo.html">Phylogenetic Meta-analysis tutorial</a>.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>zr_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/daniel1noble/meta-workshop/gh-pages/data/ind_disp_raw_data.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>dispersal_def) <span class="sc">%&gt;%</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  tibble<span class="sc">::</span><span class="fu">rowid_to_column</span>(<span class="st">"es_ID"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">species_OTL =</span> stringr<span class="sc">::</span><span class="fu">str_replace_all</span>(species_OTL, <span class="st">"_"</span>, <span class="st">" "</span>))</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>zr_data <span class="ot">&lt;-</span> metafor<span class="sc">::</span><span class="fu">escalc</span>(<span class="at">measure =</span> <span class="st">"ZCOR"</span>, <span class="at">ri =</span> corr_coeff, <span class="at">ni =</span> sample_size,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>                           <span class="at">data =</span> zr_data, <span class="at">var.names =</span> <span class="fu">c</span>(<span class="st">"Zr"</span>, <span class="st">"V_Zr"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="build-the-tree-and-the-phylogenetic-correlation-matrix" class="level3">
<h3 class="anchored" data-anchor-id="build-the-tree-and-the-phylogenetic-correlation-matrix">Build the tree and the phylogenetic correlation matrix</h3>
<p>This step is identical to the <a href="./phylo.html">Phylogenetic Meta-analysis chapter</a>; we reproduce it here so the chapter is self-contained.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>species <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">unique</span>(<span class="fu">as.character</span>(zr_data<span class="sc">$</span>species_OTL)))</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>taxa    <span class="ot">&lt;-</span> rotl<span class="sc">::</span><span class="fu">tnrs_match_names</span>(<span class="at">names =</span> species)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>tree <span class="ot">&lt;-</span> rotl<span class="sc">::</span><span class="fu">tol_induced_subtree</span>(<span class="at">ott_ids =</span> <span class="fu">ott_id</span>(taxa), <span class="at">label_format =</span> <span class="st">"name"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>tree <span class="ot">&lt;-</span> ape<span class="sc">::</span><span class="fu">compute.brlen</span>(tree, <span class="at">method =</span> <span class="st">"Grafen"</span>, <span class="at">power =</span> <span class="dv">1</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>tree <span class="ot">&lt;-</span> ape<span class="sc">::</span><span class="fu">multi2di</span>(tree, <span class="at">random =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>phylo_cov <span class="ot">&lt;-</span> <span class="fu">vcv</span>(tree, <span class="at">cor =</span> <span class="cn">FALSE</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>zr_data <span class="ot">&lt;-</span> zr_data <span class="sc">%&gt;%</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">species_OTL =</span> stringr<span class="sc">::</span><span class="fu">str_replace_all</span>(species_OTL, <span class="st">" "</span>, <span class="st">"_"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="specify-priors" class="level3">
<h3 class="anchored" data-anchor-id="specify-priors">Specify priors</h3>
<p><code>brms</code> will assign reasonable defaults for any parameter you do not name explicitly. To see what <code>brms</code> <em>would</em> use, ask for the prior skeleton implied by the model formula:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">get_prior</span>(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  Zr <span class="sc">|</span> <span class="fu">se</span>(<span class="fu">sqrt</span>(V_Zr)) <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">|</span> study_ID) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> es_ID) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> species) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> <span class="fu">gr</span>(species_OTL, <span class="at">cov =</span> A)),</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data  =</span> zr_data,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data2 =</span> <span class="fu">list</span>(<span class="at">A =</span> phylo_cov)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We override the defaults with weakly-informative priors that match the formal definition above:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>priors <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  brms<span class="sc">::</span><span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>, <span class="dv">1</span>),         <span class="at">class =</span> <span class="st">"Intercept"</span>),</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  brms<span class="sc">::</span><span class="fu">prior</span>(<span class="fu">student_t</span>(<span class="dv">3</span>, <span class="dv">0</span>, <span class="fl">2.5</span>), <span class="at">class =</span> <span class="st">"sd"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><code>class = "sd"</code> applies the same prior to every group-level standard deviation. To put a different prior on, say, the phylogenetic SD only, use <code>class = "sd", group = "species_OTL"</code>.</p>
</section>
<section id="fit-the-model-in-brms" class="level3">
<h3 class="anchored" data-anchor-id="fit-the-model-in-brms">Fit the model in <code>brms</code></h3>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>bayes_phylo <span class="ot">&lt;-</span> brms<span class="sc">::</span><span class="fu">brm</span>(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  Zr <span class="sc">|</span> <span class="fu">se</span>(<span class="fu">sqrt</span>(V_Zr)) <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">|</span> study_ID) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> es_ID) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> species) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> <span class="fu">gr</span>(species_OTL, <span class="at">cov =</span> A)),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data    =</span> zr_data,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data2   =</span> <span class="fu">list</span>(<span class="at">A =</span> phylo_cov),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">prior   =</span> priors,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">chains  =</span> <span class="dv">4</span>, <span class="at">iter =</span> <span class="dv">3000</span>, <span class="at">warmup =</span> <span class="dv">1000</span>, <span class="at">thin =</span> <span class="dv">1</span>, <span class="at">cores =</span> <span class="dv">4</span>, <span class="at">seed =</span> <span class="dv">42</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">control =</span> <span class="fu">list</span>(<span class="at">adapt_delta =</span> <span class="fl">0.95</span>),</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">file    =</span> <span class="st">"models/bayes_phylo"</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The first render will compile and sample the model (a few minutes). Subsequent renders read the cached fit from <code>models/bayes_phylo.rds</code> and complete in seconds. Delete the <code>.rds</code> to force a refit (e.g.&nbsp;after editing the formula or priors).</p>
</div>
</div>
<p>A few things to note:</p>
<p>First, the <code>| se(sqrt(V_Zr))</code> syntax tells <code>brms</code> to use the sampling variances to control for uncertainty in the effect sizes. The <code>se</code> stands for standard error, which is why we need to take the square root of the sampling variance. Now, there are a couple of ways we can use the <code>se()</code> function. Currently, we are not setting the <code>sigma</code> argument within the function to <code>TRUE</code>, i.e., <code>se(sqrt(V_Zr), sigma = FALSE)</code>, which means that the model will not estimate a separate residual SD for the model. If we set <code>sigma = TRUE</code> we will allow the model to estimate a separate residual SD for the model. Instead, we are fitting an observation-level random effect (to keep consistent with <code>metafor</code>) which is a common way to model residual error in meta-analysis. If we had set <code>sigma = TRUE</code> as well the model would have estimated a separate residual SD for the model, but we would need to drop the observation-level random effect as these would be redundant. We can try that formulation below to show it’s roughly the same:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>bayes_phylo2 <span class="ot">&lt;-</span> brms<span class="sc">::</span><span class="fu">brm</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  Zr <span class="sc">|</span> <span class="fu">se</span>(<span class="fu">sqrt</span>(V_Zr), <span class="at">sigma =</span> <span class="cn">TRUE</span>) <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">|</span> study_ID) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> species) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> <span class="fu">gr</span>(species_OTL, <span class="at">cov =</span> A)),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data    =</span> zr_data,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data2   =</span> <span class="fu">list</span>(<span class="at">A =</span> phylo_cov),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">prior   =</span> priors,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">chains  =</span> <span class="dv">4</span>, <span class="at">iter =</span> <span class="dv">3000</span>, <span class="at">warmup =</span> <span class="dv">1000</span>, <span class="at">thin =</span> <span class="dv">1</span>, <span class="at">cores =</span> <span class="dv">4</span>, <span class="at">seed =</span> <span class="dv">42</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">control =</span> <span class="fu">list</span>(<span class="at">adapt_delta =</span> <span class="fl">0.95</span>),</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">file    =</span> <span class="st">"models/bayes_phylo2"</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We’ll explore below the similarities between these models.</p>
<p>Second, the <code>gr()</code> function around the phylogenetic random effect is a special syntax that tells <code>brms</code> to use the supplied covariance matrix <code>A</code> for that grouping factor. The <code>data2</code> argument is where we pass the phylogenetic covariance matrix. Also note that the phylogenetic A matrix differs from metafor because it’s a covariance matrix whereas <code>metafor</code> expects a correlation matrix. In our specific case the distinction is purely terminological: because we built the tree with <code>ape::compute.brlen(..., method = "Grafen", power = 1)</code> it is ultrametric with root-to-tip distance equal to 1, so every diagonal of <code>vcv(tree, cor = FALSE)</code> equals 1 and the covariance matrix is numerically identical to the correlation matrix. The distinction only matters if you use a non-ultrametric tree or skip the Grafen normalisation.</p>
<p>Finally, the <code>control</code> argument is where we can tweak the MCMC sampling parameters. <code>adapt_delta</code> controls the target acceptance rate for the Hamiltonian Monte Carlo sampler; increasing it can help with convergence when the model is complex.</p>
</section>
<section id="check-mcmc-diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="check-mcmc-diagnostics">Check MCMC diagnostics</h3>
<p>Before interpreting any posterior summary, it is important to confirm that the chains have converged. We can usually get a good sense of this from the printed summary of the model fit already but it’s also good to visually inspect the trace plots and posterior densities.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bayes_phylo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> Family: gaussian 
  Links: mu = identity 
Formula: Zr | se(sqrt(V_Zr)) ~ 1 + (1 | study_ID) + (1 | es_ID) + (1 | species) + (1 | gr(species_OTL, cov = A)) 
   Data: zr_data (Number of observations: 272) 
  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
         total post-warmup draws = 4000

Multilevel Hyperparameters:
~es_ID (Number of levels: 272) 
              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sd(Intercept)     0.34      0.02     0.30     0.39 1.00      979     1716

~species (Number of levels: 79) 
              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sd(Intercept)     0.12      0.06     0.01     0.24 1.01      318      649

~species_OTL (Number of levels: 74) 
              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sd(Intercept)     0.07      0.06     0.00     0.21 1.00     1053     1636

~study_ID (Number of levels: 88) 
              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sd(Intercept)     0.11      0.06     0.01     0.23 1.01      301      892

Regression Coefficients:
          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept     0.11      0.06    -0.01     0.25 1.00     1506     1621

Further Distributional Parameters:
      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sigma     0.00      0.00     0.00     0.00   NA       NA       NA

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
</div>
</div>
<p>Two things to look for in the printout:</p>
<ul>
<li><strong>R-hat (<span class="math inline">\(\hat{R}\)</span>)</strong> for every parameter should be <span class="math inline">\(&lt; 1.01\)</span>. Larger values mean the chains have not mixed.</li>
<li><strong>Bulk_ESS</strong> and <strong>Tail_ESS</strong> should each be ~1000, though sometimes they will be lower; getting above at least 500 is desirable. Low ESS means the posterior summary is based on too few effective draws. Increasing <code>iter</code>, <code>warmup</code>, and <code>thin</code> more can help, but sometimes if the random effects are truly very low then ESS will remain low.</li>
</ul>
<p>A visual check of the trace plots and posterior densities is also really important to check to ensure proper mixing of the MCMC chains. They usually tell the same story as the printed diagnostics but can sometimes reveal issues that are not obvious from the numbers alone (e.g.&nbsp;multimodality, poor mixing, or a small number of effective samples).</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bayes_phylo, <span class="at">ask =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_meta_files/figure-html/diagnostics-plots-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_meta_files/figure-html/diagnostics-plots-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Note that there appear to be some issues with mixing for some parameters (low ESS and chains are dragging), so we should play around with MCMC parameters to try to improve this, but this isn’t bad for demonstration purposes.</p>
<p>Recall that we also fit the same model with <code>sigma = TRUE</code>. We can look at how the output for that model compares to the one we have just fit:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bayes_phylo2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> Family: gaussian 
  Links: mu = identity 
Formula: Zr | se(sqrt(V_Zr), sigma = TRUE) ~ 1 + (1 | study_ID) + (1 | species) + (1 | gr(species_OTL, cov = A)) 
   Data: zr_data (Number of observations: 272) 
  Draws: 4 chains, each with iter = 3000; warmup = 1000; thin = 1;
         total post-warmup draws = 8000

Multilevel Hyperparameters:
~species (Number of levels: 79) 
              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sd(Intercept)     0.12      0.06     0.01     0.24 1.00      912     1698

~species_OTL (Number of levels: 74) 
              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sd(Intercept)     0.07      0.06     0.00     0.21 1.00     2944     4164

~study_ID (Number of levels: 88) 
              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sd(Intercept)     0.11      0.06     0.01     0.23 1.00     1163     3037

Regression Coefficients:
          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept     0.11      0.06    -0.01     0.24 1.00     4457     3475

Further Distributional Parameters:
      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sigma     0.34      0.02     0.29     0.39 1.00     5922     5079

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
</div>
</div>
<p>Here, we can see that <code>sigma</code> is estimated and it matches the <code>sd_es_ID__Intercept</code> from the first model, which is the observation-level random effect. The two models are essentially the same, but the first one is more consistent with the way we have been modelling residual error in <code>metafor</code>. However, we can see that this is a more elegant way to model residual error for meta-analysis with <code>brms</code> (which we recommend) as you can see improvements in the MCMC diagnostics for the second model compared to the first one because of the different way the model is parameterised. So, we’ve solved our mixing issues!</p>
</section>
<section id="posterior-summaries" class="level3">
<h3 class="anchored" data-anchor-id="posterior-summaries">Posterior summaries</h3>
<p>The overall effect (intercept on the <span class="math inline">\(Z_r\)</span> scale) and 95% credible interval:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">posterior_summary</span>(bayes_phylo2, <span class="at">variable =</span> <span class="st">"b_Intercept"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Est.Error    Q2.5 Q97.5
b_Intercept    0.107    0.0616 -0.0102 0.242</code></pre>
</div>
</div>
<p>Variance components — between-study, within-study residual (here estimated as <code>sigma</code> because we used <code>se(..., sigma = TRUE)</code> and dropped the OLRE), non-phylogenetic species, and phylogenetic species:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">posterior_summary</span>(bayes_phylo2, <span class="at">variable =</span> <span class="fu">c</span>(<span class="st">"sd_study_ID__Intercept"</span>,</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>                                                   <span class="st">"sigma"</span>,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                                                   <span class="st">"sd_species__Intercept"</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>                                                   <span class="st">"sd_species_OTL__Intercept"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                          Estimate Est.Error    Q2.5 Q97.5
sd_study_ID__Intercept      0.1065    0.0631 0.00593 0.231
sigma                       0.3398    0.0241 0.29490 0.388
sd_species__Intercept       0.1237    0.0644 0.00824 0.245
sd_species_OTL__Intercept   0.0669    0.0564 0.00242 0.215</code></pre>
</div>
</div>
<section id="what-does-the-model-output-tell-us" class="level4">
<h4 class="anchored" data-anchor-id="what-does-the-model-output-tell-us">What does the model output tell us?</h4>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">Task</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<blockquote class="blockquote">
<p><strong>Is there an overall positive or negative relationship between physiology and movement?</strong></p>
</blockquote>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<blockquote class="blockquote">
<p>The posterior mean for the intercept is 0.107 with a 95% credible interval of -0.01 to 0.242. As in the <a href="./phylo.html">REML analysis</a>, the overall relationship is <strong>positive</strong> and the credible interval nearly excludes zero. Compare these numbers with the REML estimates from the previous chapter — they should be fairly similar. However, the Bayesian fit also gives us full posterior distributions for all parameters. For example, we can look at every variance component with <code>brms::mcmc_plot(bayes_phylo2, variable = "^sd_", regex = TRUE)</code>.</p>
</blockquote>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="extracting-posterior-distributions-and-derived-quantities" class="level2">
<h2 class="anchored" data-anchor-id="extracting-posterior-distributions-and-derived-quantities"><strong>Extracting Posterior distributions and Derived Quantities</strong></h2>
<p>One of the key benefits of the Bayesian framework is that we can propagate uncertainty into any derived quantity simply by computing it draw-by-draw across the posterior. As an example, we will compute a full posterior distribution for <span class="math inline">\(I^2_{total}\)</span> — the proportion of total variance attributable to genuine heterogeneity (rather than sampling noise) — using the same definition as in the <a href="./het.html">Heterogeneity chapter</a>:</p>
<p><span class="math display">\[
I^2_{total} = \frac{\tau^2 + \sigma_{k}^2 + \sigma_{a}^2 + \sigma_{e}^2}{\tau^2 + \sigma_{k}^2 + \sigma_{a}^2 + \sigma_{e}^2 + \sigma_{m}^2}
\]</span></p>
<p>The denominator includes the <strong>typical sampling variance</strong> <span class="math inline">\(\sigma^2_m\)</span>, which is a fixed function of the inverse-variance weights <span class="math inline">\(w_i = 1/v_i\)</span> and is computed once from the data (not estimated by the model):</p>
<p><span class="math display">\[
\sigma_{m}^2 = \frac{(k-1)\sum w_i}{(\sum w_i)^2 - \sum w_i^2}
\]</span></p>
<p>Omitting <span class="math inline">\(\sigma^2_m\)</span> would inflate <span class="math inline">\(I^2_{total}\)</span> because the denominator would no longer represent total variance. With <span class="math inline">\(\sigma^2_m\)</span> in hand, we compute the posterior of <span class="math inline">\(I^2_{total}\)</span> by squaring each posterior draw of the random-effect standard deviations, summing them, and dividing by the total. We first want to extract the posterior draws from the model object. We know we should have 8000 draws (rows) in total (4 chains x 2000 iterations) but the effective number of draws may be lower due to autocorrelation. We can extract the posterior draws as a data frame with <code>brms::as_draws_df()</code>, which gives us one column per parameter and one row per draw.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Typical sampling variance </span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>w        <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> zr_data<span class="sc">$</span>V_Zr</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>k        <span class="ot">&lt;-</span> <span class="fu">nrow</span>(zr_data)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>sigma2_m <span class="ot">&lt;-</span> (k <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="fu">sum</span>(w) <span class="sc">/</span> (<span class="fu">sum</span>(w)<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> <span class="fu">sum</span>(w<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Posterior draws of every random-effect SD; square to get variances!</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Remember, for bayes_phylo2 the within-study residual variance is estimated as </span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="co"># `sigma` (we used se(..., sigma = TRUE) and dropped the (1 | es_ID) </span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="co"># observation-level random effect).</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>draws        <span class="ot">&lt;-</span> brms<span class="sc">::</span><span class="fu">as_draws_df</span>(bayes_phylo2)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>sigma2_study <span class="ot">&lt;-</span> draws<span class="sc">$</span>sd_study_ID__Intercept<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>sigma2_es    <span class="ot">&lt;-</span> draws<span class="sc">$</span>sigma<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>sigma2_spp   <span class="ot">&lt;-</span> draws<span class="sc">$</span>sd_species__Intercept<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>sigma2_phylo <span class="ot">&lt;-</span> draws<span class="sc">$</span>sd_species_OTL__Intercept<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>var_total <span class="ot">&lt;-</span> sigma2_study <span class="sc">+</span> sigma2_es <span class="sc">+</span> sigma2_spp <span class="sc">+</span> sigma2_phylo</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>I2_total  <span class="ot">&lt;-</span> var_total <span class="sc">/</span> (var_total <span class="sc">+</span> sigma2_m)</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Posterior summary (median + 95% credible interval)</span></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(I2_total, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> 2.5%   50% 97.5% 
0.863 0.890 0.917 </code></pre>
</div>
</div>
<p>Because we computed <span class="math inline">\(I^2_{total}\)</span> per draw, we have the <em>posterior distribution</em> of <span class="math inline">\(I^2_{total}\)</span> rather than a single point estimate. The 95% interval reported above is a credible interval that fully reflects uncertainty in every variance component simultaneously — something that is awkward to obtain from the REML fit without bootstrapping.</p>
<p>We can also now nicely visualise the posterior distribution of <span class="math inline">\(I^2_{total}\)</span>:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(I2_total), <span class="fu">aes</span>(<span class="at">x =</span> I2_total)) <span class="sc">+</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">quantile</span>(I2_total, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>)), <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(I<span class="sc">^</span><span class="dv">2</span>[total]), <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_meta_files/figure-html/I2-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="your-turn-i2_study" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-i2_study">Your turn: <span class="math inline">\(I^2_{study}\)</span></h4>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">Task</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<blockquote class="blockquote">
<p><strong>Adapt the code above to compute the posterior of <span class="math inline">\(I^2_{study}\)</span></strong> — the fraction of total variance attributable to <em>between-study</em> heterogeneity alone. Report the posterior median and 95% credible interval, and contrast it with <span class="math inline">\(I^2_{total}\)</span>.</p>
</blockquote>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<blockquote class="blockquote">
<p>Only the numerator changes; we re-use <code>sigma2_study</code>, <code>var_total</code> and <code>sigma2_m</code> from the chunk above. Formally:</p>
<p><span class="math display">\[
I^2_{study} = \frac{\tau^2}{\tau^2 + \sigma_{k}^2 + \sigma_{a}^2 + \sigma_{e}^2 + \sigma_{m}^2}
\]</span></p>
</blockquote>
<blockquote class="blockquote">
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>I2_study <span class="ot">&lt;-</span> sigma2_study <span class="sc">/</span> (var_total <span class="sc">+</span> sigma2_m)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(I2_study, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    2.5%      50%    97.5% 
0.000209 0.063309 0.281499 </code></pre>
</div>
</div>
</blockquote>
<blockquote class="blockquote">
<p>The posterior median for <span class="math inline">\(I^2_{study}\)</span> is 0.063 with a 95% credible interval of 0 to 0.281. Comparing this with <span class="math inline">\(I^2_{total}\)</span> (median 0.89) tells you how much of the <em>real</em> heterogeneity is concentrated at the study level versus spread across the other variance components (within-study residual, non-phylogenetic species, phylogenetic). You can compute <span class="math inline">\(I^2\)</span> for any single component the same way — just put its squared SD in the numerator.</p>
</blockquote>
</div>
</div>
</div>
<p><br></p>
<p>This is one of the powerful features of Bayesian meta-analysis; the ability to derive full posterior distributions for any quantity of interest by computing it draw-by-draw across the posterior. You can use this same approach to get a posterior distribution for the overall effect size, prediction intervals, or any other derived quantity you like. When you have moderators, it also means you can get overall means for each group or even contrasts for specific comparisons between levels of a moderator that maybe the model doesn’t present by default.</p>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references"><strong>References</strong></h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-Burkner2017" class="csl-entry" role="listitem">
<strong>Bürkner, P.-C.</strong> (2017). <a href="https://doi.org/10.18637/jss.v080.i01"><span class="nocase">brms</span>: An <span>R</span> package for <span>Bayesian</span> multilevel models using <span>Stan</span></a>. <em>Journal of Statistical Software</em> <strong>80</strong>, 1–28.
</div>
<div id="ref-Nakagawa2022comment" class="csl-entry" role="listitem">
<strong>Nakagawa, S., Senior, A. M., Viechtbauer, W. and Noble, D. W. A.</strong> (2022). <a href="https://doi.org/10.1002/ecy.3490">An assessment of statistical methods for nonindependent data in ecological meta-analyses: comment</a>. <em>Ecology</em> <strong>103</strong>, e03490.
</div>
<div id="ref-Pappalardo2020" class="csl-entry" role="listitem">
<strong>Pappalardo, P., Ogle, K., Hamman, E. A., Bence, J. R., Hungate, B. A. and Osenberg, C. W.</strong> (2020). <a href="https://doi.org/10.1111/2041-210X.13445">Comparing traditional and <span>Bayesian</span> approaches to ecological meta-analysis</a>. <em>Methods in Ecology and Evolution</em> <strong>11</strong>, 1286–1295.
</div>
<div id="ref-Song2020" class="csl-entry" role="listitem">
<strong>Song, C., Peacor, S. D., Osenberg, C. W. and Bence, J. R.</strong> (2020). <a href="https://doi.org/10.1002/ecy.3184">An assessment of statistical methods for nonindependent data in ecological meta-analyses</a>. <em>Ecology</em> <strong>101</strong>, e03184.
</div>
<div id="ref-WuSeebacher2022" class="csl-entry" role="listitem">
<strong>Wu, N. C. and Seebacher, F.</strong> (2022). <a href="https://doi.org/10.1038/s42003-022-03055-y">Physiology can predict animal activity, exploration, and dispersal</a>. <em>Communications Biology</em> <strong>5</strong>, 1–11.
</div>
</div>
<p><br></p>
</section>
<section id="session-information" class="level2">
<h2 class="anchored" data-anchor-id="session-information"><strong>Session Information</strong></h2>
<div class="cell">
<div class="cell-output-display">
<p><strong>R version 4.5.3 (2026-03-11)</strong></p>
<p><strong>Platform:</strong> aarch64-apple-darwin20</p>
<p><strong>attached base packages:</strong> <em>stats</em>, <em>graphics</em>, <em>grDevices</em>, <em>utils</em>, <em>datasets</em>, <em>methods</em> and <em>base</em></p>
<p><strong>other attached packages:</strong> <em>bayesplot(v.1.15.0)</em>, <em>mathjaxr(v.2.0-0)</em>, <em>pander(v.0.6.6)</em>, <em>flextable(v.0.9.9)</em>, <em>orchaRd(v.2.2.0)</em>, <em>lubridate(v.1.9.5)</em>, <em>forcats(v.1.0.1)</em>, <em>stringr(v.1.6.0)</em>, <em>dplyr(v.1.2.1)</em>, <em>purrr(v.1.2.2)</em>, <em>readr(v.2.2.0)</em>, <em>tidyr(v.1.3.2)</em>, <em>tibble(v.3.3.1)</em>, <em>ggplot2(v.4.0.3)</em>, <em>tidyverse(v.2.0.0)</em>, <em>phytools(v.2.5-2)</em>, <em>maps(v.3.4.3)</em>, <em>rotl(v.3.1.1)</em>, <em>ape(v.5.8-1)</em>, <em>brms(v.2.23.0)</em>, <em>Rcpp(v.1.1.1-1.1)</em>, <em>metafor(v.5.0-1)</em>, <em>numDeriv(v.2016.8-1.1)</em>, <em>metadat(v.1.4-0)</em> and <em>Matrix(v.1.7-4)</em></p>
<p><strong>loaded via a namespace (and not attached):</strong> <em>RColorBrewer(v.1.1-3)</em>, <em>tensorA(v.0.36.2.1)</em>, <em>jsonlite(v.2.0.0)</em>, <em>magrittr(v.2.0.5)</em>, <em>TH.data(v.1.1-3)</em>, <em>estimability(v.1.5.1)</em>, <em>farver(v.2.1.2)</em>, <em>rmarkdown(v.2.31)</em>, <em>ragg(v.1.5.2)</em>, <em>vctrs(v.0.7.3)</em>, <em>askpass(v.1.2.1)</em>, <em>htmltools(v.0.5.9)</em>, <em>progress(v.1.2.3)</em>, <em>distributional(v.0.6.0)</em>, <em>curl(v.7.1.0)</em>, <em>DEoptim(v.2.2-8)</em>, <em>StanHeaders(v.2.32.10)</em>, <em>htmlwidgets(v.1.6.4)</em>, <em>plyr(v.1.8.9)</em>, <em>sandwich(v.3.1-1)</em>, <em>emmeans(v.2.0.3)</em>, <em>zoo(v.1.8-14)</em>, <em>uuid(v.1.2-2)</em>, <em>igraph(v.2.2.1)</em>, <em>lifecycle(v.1.0.5)</em>, <em>iterators(v.1.0.14)</em>, <em>pkgconfig(v.2.0.3)</em>, <em>R6(v.2.6.1)</em>, <em>fastmap(v.1.2.0)</em>, <em>digest(v.0.6.39)</em>, <em>colorspace(v.2.1-1)</em>, <em>textshaping(v.1.0.5)</em>, <em>labeling(v.0.4.3)</em>, <em>clusterGeneration(v.1.3.8)</em>, <em>timechange(v.0.4.0)</em>, <em>httr(v.1.4.8)</em>, <em>abind(v.1.4-8)</em>, <em>compiler(v.4.5.3)</em>, <em>fontquiver(v.0.2.1)</em>, <em>withr(v.3.0.2)</em>, <em>doParallel(v.1.0.17)</em>, <em>S7(v.0.2.2)</em>, <em>backports(v.1.5.1)</em>, <em>inline(v.0.3.21)</em>, <em>optimParallel(v.1.0-2)</em>, <em>QuickJSR(v.1.9.0)</em>, <em>pkgbuild(v.1.4.8)</em>, <em>MASS(v.7.3-65)</em>, <em>openssl(v.2.4.0)</em>, <em>scatterplot3d(v.0.3-44)</em>, <em>loo(v.2.9.0)</em>, <em>tools(v.4.5.3)</em>, <em>rncl(v.0.8.9)</em>, <em>otel(v.0.2.0)</em>, <em>zip(v.2.3.3)</em>, <em>rentrez(v.1.2.4)</em>, <em>glue(v.1.8.1)</em>, <em>quadprog(v.1.5-8)</em>, <em>nlme(v.3.1-168)</em>, <em>grid(v.4.5.3)</em>, <em>checkmate(v.2.3.4)</em>, <em>reshape2(v.1.4.5)</em>, <em>generics(v.0.1.4)</em>, <em>gtable(v.0.3.6)</em>, <em>tzdb(v.0.5.0)</em>, <em>data.table(v.1.18.2.1)</em>, <em>hms(v.1.1.4)</em>, <em>xml2(v.1.5.2)</em>, <em>foreach(v.1.5.2)</em>, <em>pillar(v.1.11.1)</em>, <em>posterior(v.1.6.1)</em>, <em>splines(v.4.5.3)</em>, <em>lattice(v.0.22-9)</em>, <em>survival(v.3.8-6)</em>, <em>tidyselect(v.1.2.1)</em>, <em>fontLiberation(v.0.1.0)</em>, <em>knitr(v.1.51)</em>, <em>fontBitstreamVera(v.0.1.1)</em>, <em>gridExtra(v.2.3)</em>, <em>V8(v.6.0.4)</em>, <em>stats4(v.4.5.3)</em>, <em>xfun(v.0.57)</em>, <em>expm(v.1.0-0)</em>, <em>bridgesampling(v.1.2-1)</em>, <em>matrixStats(v.1.5.0)</em>, <em>rstan(v.2.32.7)</em>, <em>stringi(v.1.8.7)</em>, <em>yaml(v.2.3.12)</em>, <em>pacman(v.0.5.1)</em>, <em>evaluate(v.1.0.5)</em>, <em>codetools(v.0.2-20)</em>, <em>officer(v.0.6.10)</em>, <em>gdtools(v.0.4.2)</em>, <em>cli(v.3.6.6)</em>, <em>RcppParallel(v.5.1.11-2)</em>, <em>xtable(v.1.8-8)</em>, <em>systemfonts(v.1.3.2)</em>, <em>coda(v.0.19-4.1)</em>, <em>XML(v.3.99-0.22)</em>, <em>parallel(v.4.5.3)</em>, <em>rstantools(v.2.6.0)</em>, <em>prettyunits(v.1.2.0)</em>, <em>Brobdingnag(v.1.2-9)</em>, <em>phangorn(v.2.12.1)</em>, <em>mvtnorm(v.1.3-7)</em>, <em>scales(v.1.4.0)</em>, <em>crayon(v.1.5.3)</em>, <em>combinat(v.0.0-8)</em>, <em>rlang(v.1.2.0)</em>, <em>fastmatch(v.1.1-8)</em>, <em>multcomp(v.1.4-28)</em> and <em>mnormt(v.2.1.2)</em></p>
</div>
</div>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./phylo.html" class="pagination-link" aria-label="Phylogenetic Meta-analysis">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Phylogenetic Meta-analysis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb21" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Bayesian Meta-analysis</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup-bayes</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(metafor, brms, ape, rotl, phytools, tidyverse, orchaRd, flextable, pander, mathjaxr, bayesplot)</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">digits=</span><span class="dv">3</span>)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a><span class="fu">## **Introduction to Bayesian Meta-analysis**</span></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>Throughout the previous chapters we have estimated meta-analytic models with <span class="co">[</span><span class="ot">`metafor`</span><span class="co">](fixed-vs-random.qmd)</span> using restricted maximum likelihood (REML). The model objects we obtained — overall effects, variance components, confidence intervals — are *frequentist* estimates.</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>A **Bayesian** meta-analysis instead returns a *posterior distribution* for every parameter in the model, by combining the data (through the likelihood) with prior beliefs about plausible parameter values. This re-framing brings several practical benefits when synthesising data in ecology, evolution and physiology:</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Honest uncertainty for variance components.** REML-based confidence intervals for variance components (e.g. $\tau^2$, phylogenetic $\sigma_{a}^2$) can be poorly behaved when the number of studies is small or when an estimate is near the boundary of zero <span class="co">[</span><span class="ot">@Burkner2017</span><span class="co">]</span>. Posterior credible intervals do not have this problem.</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Propagating uncertainty more easily.** The Bayesian framing lets you propagate uncertainty into derived quantities (e.g. between-study heterogeneity ratios, prediction intervals) and gives you more flexibility in the derived quantities you present within your paper.</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Easy to extend.** Once we have the Bayesian machinery in place, adding non-Gaussian likelihoods, missing-data models, or measurement-error structures is mostly a one-line change.</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>Bayesian methods are well-established in ecological and evolutionary meta-analysis, not just a fashionable alternative, but are not used as often as frequentist methods. @Pappalardo2020 compared traditional REML and Bayesian fits across a range of ecological meta-analytic scenarios and found that the two approaches generally recover the same overall effect, but that the Bayesian fit gives better-calibrated uncertainty when the number of studies is small or when variance components are near zero. Similarly, @Nakagawa2022comment, in their re-analysis of the simulations of @Song2020, included a Bayesian multilevel model alongside the frequentist alternatives and showed that it can help control the inflated Type I error rates that arise when effect sizes are non-independent (see the simulation figure in their Comment). Together, these papers position Bayesian multilevel models as a robust, often preferable, complement to REML for the kinds of complex, multi-strata data routinely synthesised in our field.</span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>In this tutorial we use the <span class="co">[</span><span class="ot">`brms`</span><span class="co">](https://paulbuerkner.com/brms/)</span> R package <span class="co">[</span><span class="ot">@Burkner2017</span><span class="co">]</span>. <span class="in">`brms`</span> provides a <span class="in">`lme4`</span>-style formula interface to the <span class="co">[</span><span class="ot">Stan</span><span class="co">](https://mc-stan.org/)</span> probabilistic programming language, which means the syntax will look familiar if you have used <span class="in">`lmer`</span> or <span class="in">`metafor::rma.mv`</span>. We re-fit the **phylogenetic multilevel meta-analysis** from the <span class="co">[</span><span class="ot">previous chapter</span><span class="co">](phylo.qmd)</span> so you can directly compare the Bayesian and REML estimates on the same data.</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a><span class="fu">## **Formal Definition of the Bayesian Phylogenetic Meta-analytic Model**</span></span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Recall</span><span class="co">](phylo.qmd)</span> the phylogenetic multilevel meta-analytic model:</span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a>y_{i} &amp;= \mu + s_{j<span class="co">[</span><span class="ot">i</span><span class="co">]</span>} + spp_{k<span class="co">[</span><span class="ot">i</span><span class="co">]</span>} + a_{k<span class="co">[</span><span class="ot">i</span><span class="co">]</span>} + e_{i} + m_{i} <span class="sc">\\</span></span>
<span id="cb21-36"><a href="#cb21-36" aria-hidden="true" tabindex="-1"></a>m_{i} &amp;\sim N(0, v_{i}\textbf{I}) <span class="sc">\\</span></span>
<span id="cb21-37"><a href="#cb21-37" aria-hidden="true" tabindex="-1"></a>s_{j} &amp;\sim N(0, \tau^2\textbf{I}) <span class="sc">\\</span></span>
<span id="cb21-38"><a href="#cb21-38" aria-hidden="true" tabindex="-1"></a>spp_{k} &amp;\sim N(0, \sigma_{k}^2\textbf{I}) <span class="sc">\\</span></span>
<span id="cb21-39"><a href="#cb21-39" aria-hidden="true" tabindex="-1"></a>a_{k} &amp;\sim N(0, \sigma_{a}^2\textbf{A}) <span class="sc">\\</span></span>
<span id="cb21-40"><a href="#cb21-40" aria-hidden="true" tabindex="-1"></a>e_{i} &amp;\sim N(0, \sigma_{e}^2\textbf{I})</span>
<span id="cb21-41"><a href="#cb21-41" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb21-42"><a href="#cb21-42" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-43"><a href="#cb21-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-44"><a href="#cb21-44" aria-hidden="true" tabindex="-1"></a>The model is structurally identical to the one we fit with <span class="in">`metafor::rma.mv`</span>. To make it Bayesian we add **priors** on every estimated parameter:</span>
<span id="cb21-45"><a href="#cb21-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-46"><a href="#cb21-46" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-47"><a href="#cb21-47" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb21-48"><a href="#cb21-48" aria-hidden="true" tabindex="-1"></a>\mu &amp;\sim N(0, 1) <span class="sc">\\</span></span>
<span id="cb21-49"><a href="#cb21-49" aria-hidden="true" tabindex="-1"></a>\tau, \sigma_{k}, \sigma_{a}, \sigma_{e} &amp;\sim t^{+}_{3}(0, 2.5)</span>
<span id="cb21-50"><a href="#cb21-50" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb21-51"><a href="#cb21-51" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-52"><a href="#cb21-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-53"><a href="#cb21-53" aria-hidden="true" tabindex="-1"></a>These are *weakly informative* priors. For an effect size on the Fisher's $Z_r$ scale, $\mu \sim N(0, 1)$ says we expect the overall correlation to be near zero with a standard deviation that easily covers the range of biologically plausible effects. For each random-effect standard deviation we use a half-Student-t prior with 3 degrees of freedom and scale 2.5 — written $t^{+}_{3}(0, 2.5)$. This is the conventional default for variance components in <span class="in">`brms`</span> and Stan: it concentrates posterior mass on small, biologically plausible SDs while keeping heavier tails than a half-Normal, so the prior does not pull large variance components down toward zero when the data really do support them. We will discuss how to override these defaults below.</span>
<span id="cb21-54"><a href="#cb21-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-55"><a href="#cb21-55" aria-hidden="true" tabindex="-1"></a><span class="fu">## **Example: Bayesian Phylogenetic Meta-analysis**</span></span>
<span id="cb21-56"><a href="#cb21-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-57"><a href="#cb21-57" aria-hidden="true" tabindex="-1"></a><span class="al">![](./figs/WuSeebacher.png)</span></span>
<span id="cb21-58"><a href="#cb21-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-59"><a href="#cb21-59" aria-hidden="true" tabindex="-1"></a><span class="fu">### Format raw data for analysis</span></span>
<span id="cb21-60"><a href="#cb21-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-61"><a href="#cb21-61" aria-hidden="true" tabindex="-1"></a>We re-use the dispersal data set (Z-transformed correlation coefficients, $Z_r$) from <span class="co">[</span><span class="ot">@WuSeebacher2022</span><span class="co">](https://www.nature.com/articles/s42003-022-03055-y)</span> introduced in the <span class="co">[</span><span class="ot">Effect Size tutorial</span><span class="co">](effect-size.qmd)</span> and analysed with REML in the <span class="co">[</span><span class="ot">Phylogenetic Meta-analysis tutorial</span><span class="co">](phylo.qmd)</span>.</span>
<span id="cb21-62"><a href="#cb21-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-63"><a href="#cb21-63" aria-hidden="true" tabindex="-1"></a><span class="in">```{r raw-data-bayes}</span></span>
<span id="cb21-64"><a href="#cb21-64" aria-hidden="true" tabindex="-1"></a>zr_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/daniel1noble/meta-workshop/gh-pages/data/ind_disp_raw_data.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-65"><a href="#cb21-65" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>dispersal_def) <span class="sc">%&gt;%</span></span>
<span id="cb21-66"><a href="#cb21-66" aria-hidden="true" tabindex="-1"></a>  tibble<span class="sc">::</span><span class="fu">rowid_to_column</span>(<span class="st">"es_ID"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-67"><a href="#cb21-67" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">species_OTL =</span> stringr<span class="sc">::</span><span class="fu">str_replace_all</span>(species_OTL, <span class="st">"_"</span>, <span class="st">" "</span>))</span>
<span id="cb21-68"><a href="#cb21-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-69"><a href="#cb21-69" aria-hidden="true" tabindex="-1"></a>zr_data <span class="ot">&lt;-</span> metafor<span class="sc">::</span><span class="fu">escalc</span>(<span class="at">measure =</span> <span class="st">"ZCOR"</span>, <span class="at">ri =</span> corr_coeff, <span class="at">ni =</span> sample_size,</span>
<span id="cb21-70"><a href="#cb21-70" aria-hidden="true" tabindex="-1"></a>                           <span class="at">data =</span> zr_data, <span class="at">var.names =</span> <span class="fu">c</span>(<span class="st">"Zr"</span>, <span class="st">"V_Zr"</span>))</span>
<span id="cb21-71"><a href="#cb21-71" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-72"><a href="#cb21-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-73"><a href="#cb21-73" aria-hidden="true" tabindex="-1"></a><span class="fu">### Build the tree and the phylogenetic correlation matrix</span></span>
<span id="cb21-74"><a href="#cb21-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-75"><a href="#cb21-75" aria-hidden="true" tabindex="-1"></a>This step is identical to the <span class="co">[</span><span class="ot">Phylogenetic Meta-analysis chapter</span><span class="co">](phylo.qmd)</span>; we reproduce it here so the chapter is self-contained.</span>
<span id="cb21-76"><a href="#cb21-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-79"><a href="#cb21-79" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb21-80"><a href="#cb21-80" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tree-bayes</span></span>
<span id="cb21-81"><a href="#cb21-81" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb21-82"><a href="#cb21-82" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb21-83"><a href="#cb21-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-84"><a href="#cb21-84" aria-hidden="true" tabindex="-1"></a>species <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">unique</span>(<span class="fu">as.character</span>(zr_data<span class="sc">$</span>species_OTL)))</span>
<span id="cb21-85"><a href="#cb21-85" aria-hidden="true" tabindex="-1"></a>taxa    <span class="ot">&lt;-</span> rotl<span class="sc">::</span><span class="fu">tnrs_match_names</span>(<span class="at">names =</span> species)</span>
<span id="cb21-86"><a href="#cb21-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-87"><a href="#cb21-87" aria-hidden="true" tabindex="-1"></a>tree <span class="ot">&lt;-</span> rotl<span class="sc">::</span><span class="fu">tol_induced_subtree</span>(<span class="at">ott_ids =</span> <span class="fu">ott_id</span>(taxa), <span class="at">label_format =</span> <span class="st">"name"</span>)</span>
<span id="cb21-88"><a href="#cb21-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-89"><a href="#cb21-89" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb21-90"><a href="#cb21-90" aria-hidden="true" tabindex="-1"></a>tree <span class="ot">&lt;-</span> ape<span class="sc">::</span><span class="fu">compute.brlen</span>(tree, <span class="at">method =</span> <span class="st">"Grafen"</span>, <span class="at">power =</span> <span class="dv">1</span>)</span>
<span id="cb21-91"><a href="#cb21-91" aria-hidden="true" tabindex="-1"></a>tree <span class="ot">&lt;-</span> ape<span class="sc">::</span><span class="fu">multi2di</span>(tree, <span class="at">random =</span> <span class="cn">TRUE</span>)</span>
<span id="cb21-92"><a href="#cb21-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-93"><a href="#cb21-93" aria-hidden="true" tabindex="-1"></a>phylo_cov <span class="ot">&lt;-</span> <span class="fu">vcv</span>(tree, <span class="at">cor =</span> <span class="cn">FALSE</span>)</span>
<span id="cb21-94"><a href="#cb21-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-95"><a href="#cb21-95" aria-hidden="true" tabindex="-1"></a>zr_data <span class="ot">&lt;-</span> zr_data <span class="sc">%&gt;%</span></span>
<span id="cb21-96"><a href="#cb21-96" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">species_OTL =</span> stringr<span class="sc">::</span><span class="fu">str_replace_all</span>(species_OTL, <span class="st">" "</span>, <span class="st">"_"</span>))</span>
<span id="cb21-97"><a href="#cb21-97" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-98"><a href="#cb21-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-99"><a href="#cb21-99" aria-hidden="true" tabindex="-1"></a><span class="fu">### Specify priors</span></span>
<span id="cb21-100"><a href="#cb21-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-101"><a href="#cb21-101" aria-hidden="true" tabindex="-1"></a><span class="in">`brms`</span> will assign reasonable defaults for any parameter you do not name explicitly. To see what <span class="in">`brms`</span> *would* use, ask for the prior skeleton implied by the model formula:</span>
<span id="cb21-102"><a href="#cb21-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-103"><a href="#cb21-103" aria-hidden="true" tabindex="-1"></a><span class="in">```{r priors-default, eval=FALSE}</span></span>
<span id="cb21-104"><a href="#cb21-104" aria-hidden="true" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">get_prior</span>(</span>
<span id="cb21-105"><a href="#cb21-105" aria-hidden="true" tabindex="-1"></a>  Zr <span class="sc">|</span> <span class="fu">se</span>(<span class="fu">sqrt</span>(V_Zr)) <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span></span>
<span id="cb21-106"><a href="#cb21-106" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">|</span> study_ID) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> es_ID) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> species) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> <span class="fu">gr</span>(species_OTL, <span class="at">cov =</span> A)),</span>
<span id="cb21-107"><a href="#cb21-107" aria-hidden="true" tabindex="-1"></a>  <span class="at">data  =</span> zr_data,</span>
<span id="cb21-108"><a href="#cb21-108" aria-hidden="true" tabindex="-1"></a>  <span class="at">data2 =</span> <span class="fu">list</span>(<span class="at">A =</span> phylo_cov)</span>
<span id="cb21-109"><a href="#cb21-109" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-110"><a href="#cb21-110" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-111"><a href="#cb21-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-112"><a href="#cb21-112" aria-hidden="true" tabindex="-1"></a>We override the defaults with weakly-informative priors that match the formal definition above:</span>
<span id="cb21-113"><a href="#cb21-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-114"><a href="#cb21-114" aria-hidden="true" tabindex="-1"></a><span class="in">```{r priors}</span></span>
<span id="cb21-115"><a href="#cb21-115" aria-hidden="true" tabindex="-1"></a>priors <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb21-116"><a href="#cb21-116" aria-hidden="true" tabindex="-1"></a>  brms<span class="sc">::</span><span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>, <span class="dv">1</span>),         <span class="at">class =</span> <span class="st">"Intercept"</span>),</span>
<span id="cb21-117"><a href="#cb21-117" aria-hidden="true" tabindex="-1"></a>  brms<span class="sc">::</span><span class="fu">prior</span>(<span class="fu">student_t</span>(<span class="dv">3</span>, <span class="dv">0</span>, <span class="fl">2.5</span>), <span class="at">class =</span> <span class="st">"sd"</span>)</span>
<span id="cb21-118"><a href="#cb21-118" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-119"><a href="#cb21-119" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-120"><a href="#cb21-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-121"><a href="#cb21-121" aria-hidden="true" tabindex="-1"></a><span class="in">`class = "sd"`</span> applies the same prior to every group-level standard deviation. To put a different prior on, say, the phylogenetic SD only, use <span class="in">`class = "sd", group = "species_OTL"`</span>.</span>
<span id="cb21-122"><a href="#cb21-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-123"><a href="#cb21-123" aria-hidden="true" tabindex="-1"></a><span class="fu">### Fit the model in `brms`</span></span>
<span id="cb21-124"><a href="#cb21-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-127"><a href="#cb21-127" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb21-128"><a href="#cb21-128" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: bayes-fit</span></span>
<span id="cb21-129"><a href="#cb21-129" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb21-130"><a href="#cb21-130" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb21-131"><a href="#cb21-131" aria-hidden="true" tabindex="-1"></a><span class="co">#| results: hide</span></span>
<span id="cb21-132"><a href="#cb21-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-133"><a href="#cb21-133" aria-hidden="true" tabindex="-1"></a>bayes_phylo <span class="ot">&lt;-</span> brms<span class="sc">::</span><span class="fu">brm</span>(</span>
<span id="cb21-134"><a href="#cb21-134" aria-hidden="true" tabindex="-1"></a>  Zr <span class="sc">|</span> <span class="fu">se</span>(<span class="fu">sqrt</span>(V_Zr)) <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span></span>
<span id="cb21-135"><a href="#cb21-135" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">|</span> study_ID) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> es_ID) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> species) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> <span class="fu">gr</span>(species_OTL, <span class="at">cov =</span> A)),</span>
<span id="cb21-136"><a href="#cb21-136" aria-hidden="true" tabindex="-1"></a>  <span class="at">data    =</span> zr_data,</span>
<span id="cb21-137"><a href="#cb21-137" aria-hidden="true" tabindex="-1"></a>  <span class="at">data2   =</span> <span class="fu">list</span>(<span class="at">A =</span> phylo_cov),</span>
<span id="cb21-138"><a href="#cb21-138" aria-hidden="true" tabindex="-1"></a>  <span class="at">prior   =</span> priors,</span>
<span id="cb21-139"><a href="#cb21-139" aria-hidden="true" tabindex="-1"></a>  <span class="at">chains  =</span> <span class="dv">4</span>, <span class="at">iter =</span> <span class="dv">3000</span>, <span class="at">warmup =</span> <span class="dv">1000</span>, <span class="at">thin =</span> <span class="dv">1</span>, <span class="at">cores =</span> <span class="dv">4</span>, <span class="at">seed =</span> <span class="dv">42</span>,</span>
<span id="cb21-140"><a href="#cb21-140" aria-hidden="true" tabindex="-1"></a>  <span class="at">control =</span> <span class="fu">list</span>(<span class="at">adapt_delta =</span> <span class="fl">0.95</span>),</span>
<span id="cb21-141"><a href="#cb21-141" aria-hidden="true" tabindex="-1"></a>  <span class="at">file    =</span> <span class="st">"models/bayes_phylo"</span></span>
<span id="cb21-142"><a href="#cb21-142" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-143"><a href="#cb21-143" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-144"><a href="#cb21-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-145"><a href="#cb21-145" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb21-146"><a href="#cb21-146" aria-hidden="true" tabindex="-1"></a>The first render will compile and sample the model (a few minutes). Subsequent renders read the cached fit from <span class="in">`models/bayes_phylo.rds`</span> and complete in seconds. Delete the <span class="in">`.rds`</span> to force a refit (e.g. after editing the formula or priors).</span>
<span id="cb21-147"><a href="#cb21-147" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb21-148"><a href="#cb21-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-149"><a href="#cb21-149" aria-hidden="true" tabindex="-1"></a>A few things to note: </span>
<span id="cb21-150"><a href="#cb21-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-151"><a href="#cb21-151" aria-hidden="true" tabindex="-1"></a>First, the <span class="in">`| se(sqrt(V_Zr))`</span> syntax tells <span class="in">`brms`</span> to use the sampling variances to control for uncertainty in the effect sizes. The <span class="in">`se`</span> stands for standard error, which is why we need to take the square root of the sampling variance. Now, there are a couple of ways we can use the <span class="in">`se()`</span> function. Currently, we are not setting the <span class="in">`sigma`</span> argument within the function to <span class="in">`TRUE`</span>, i.e., <span class="in">`se(sqrt(V_Zr), sigma = FALSE)`</span>, which means that the model will not estimate a separate residual SD for the model. If we set <span class="in">`sigma = TRUE`</span> we will allow the model to estimate a separate residual SD for the model. Instead, we are fitting an observation-level random effect (to keep consistent with <span class="in">`metafor`</span>) which is a common way to model residual error in meta-analysis. If we had set <span class="in">`sigma = TRUE`</span> as well the model would have estimated a separate residual SD for the model, but we would need to drop the observation-level random effect as these would be redundant. We can try that formulation below to show it's roughly the same:</span>
<span id="cb21-152"><a href="#cb21-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-153"><a href="#cb21-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-156"><a href="#cb21-156" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb21-157"><a href="#cb21-157" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: bayes-fit2</span></span>
<span id="cb21-158"><a href="#cb21-158" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb21-159"><a href="#cb21-159" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb21-160"><a href="#cb21-160" aria-hidden="true" tabindex="-1"></a><span class="co">#| results: hide</span></span>
<span id="cb21-161"><a href="#cb21-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-162"><a href="#cb21-162" aria-hidden="true" tabindex="-1"></a>bayes_phylo2 <span class="ot">&lt;-</span> brms<span class="sc">::</span><span class="fu">brm</span>(</span>
<span id="cb21-163"><a href="#cb21-163" aria-hidden="true" tabindex="-1"></a>  Zr <span class="sc">|</span> <span class="fu">se</span>(<span class="fu">sqrt</span>(V_Zr), <span class="at">sigma =</span> <span class="cn">TRUE</span>) <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span></span>
<span id="cb21-164"><a href="#cb21-164" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">|</span> study_ID) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> species) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> <span class="fu">gr</span>(species_OTL, <span class="at">cov =</span> A)),</span>
<span id="cb21-165"><a href="#cb21-165" aria-hidden="true" tabindex="-1"></a>  <span class="at">data    =</span> zr_data,</span>
<span id="cb21-166"><a href="#cb21-166" aria-hidden="true" tabindex="-1"></a>  <span class="at">data2   =</span> <span class="fu">list</span>(<span class="at">A =</span> phylo_cov),</span>
<span id="cb21-167"><a href="#cb21-167" aria-hidden="true" tabindex="-1"></a>  <span class="at">prior   =</span> priors,</span>
<span id="cb21-168"><a href="#cb21-168" aria-hidden="true" tabindex="-1"></a>  <span class="at">chains  =</span> <span class="dv">4</span>, <span class="at">iter =</span> <span class="dv">3000</span>, <span class="at">warmup =</span> <span class="dv">1000</span>, <span class="at">thin =</span> <span class="dv">1</span>, <span class="at">cores =</span> <span class="dv">4</span>, <span class="at">seed =</span> <span class="dv">42</span>,</span>
<span id="cb21-169"><a href="#cb21-169" aria-hidden="true" tabindex="-1"></a>  <span class="at">control =</span> <span class="fu">list</span>(<span class="at">adapt_delta =</span> <span class="fl">0.95</span>),</span>
<span id="cb21-170"><a href="#cb21-170" aria-hidden="true" tabindex="-1"></a>  <span class="at">file    =</span> <span class="st">"models/bayes_phylo2"</span></span>
<span id="cb21-171"><a href="#cb21-171" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-172"><a href="#cb21-172" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-173"><a href="#cb21-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-174"><a href="#cb21-174" aria-hidden="true" tabindex="-1"></a>We'll explore below the similarities between these models.</span>
<span id="cb21-175"><a href="#cb21-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-176"><a href="#cb21-176" aria-hidden="true" tabindex="-1"></a>Second, the <span class="in">`gr()`</span> function around the phylogenetic random effect is a special syntax that tells <span class="in">`brms`</span> to use the supplied covariance matrix <span class="in">`A`</span> for that grouping factor. The <span class="in">`data2`</span> argument is where we pass the phylogenetic covariance matrix. Also note that the phylogenetic A matrix differs from metafor because it's a covariance matrix whereas <span class="in">`metafor`</span> expects a correlation matrix. In our specific case the distinction is purely terminological: because we built the tree with <span class="in">`ape::compute.brlen(..., method = "Grafen", power = 1)`</span> it is ultrametric with root-to-tip distance equal to 1, so every diagonal of <span class="in">`vcv(tree, cor = FALSE)`</span> equals 1 and the covariance matrix is numerically identical to the correlation matrix. The distinction only matters if you use a non-ultrametric tree or skip the Grafen normalisation.</span>
<span id="cb21-177"><a href="#cb21-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-178"><a href="#cb21-178" aria-hidden="true" tabindex="-1"></a>Finally, the <span class="in">`control`</span> argument is where we can tweak the MCMC sampling parameters. <span class="in">`adapt_delta`</span> controls the target acceptance rate for the Hamiltonian Monte Carlo sampler; increasing it can help with convergence when the model is complex.</span>
<span id="cb21-179"><a href="#cb21-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-180"><a href="#cb21-180" aria-hidden="true" tabindex="-1"></a><span class="fu">### Check MCMC diagnostics</span></span>
<span id="cb21-181"><a href="#cb21-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-182"><a href="#cb21-182" aria-hidden="true" tabindex="-1"></a>Before interpreting any posterior summary, it is important to confirm that the chains have converged. We can usually get a good sense of this from the printed summary of the model fit already but it's also good to visually inspect the trace plots and posterior densities.</span>
<span id="cb21-183"><a href="#cb21-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-184"><a href="#cb21-184" aria-hidden="true" tabindex="-1"></a><span class="in">```{r diagnostics}</span></span>
<span id="cb21-185"><a href="#cb21-185" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bayes_phylo)</span>
<span id="cb21-186"><a href="#cb21-186" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-187"><a href="#cb21-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-188"><a href="#cb21-188" aria-hidden="true" tabindex="-1"></a>Two things to look for in the printout:</span>
<span id="cb21-189"><a href="#cb21-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-190"><a href="#cb21-190" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**R-hat ($\hat{R}$)** for every parameter should be $&lt; 1.01$. Larger values mean the chains have not mixed.</span>
<span id="cb21-191"><a href="#cb21-191" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Bulk_ESS** and **Tail_ESS** should each be ~1000, though sometimes they will be lower; getting above at least 500 is desirable. Low ESS means the posterior summary is based on too few effective draws. Increasing <span class="in">`iter`</span>, <span class="in">`warmup`</span>, and <span class="in">`thin`</span> more can help, but sometimes if the random effects are truly very low then ESS will remain low.</span>
<span id="cb21-192"><a href="#cb21-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-193"><a href="#cb21-193" aria-hidden="true" tabindex="-1"></a>A visual check of the trace plots and posterior densities is also really important to check to ensure proper mixing of the MCMC chains. They usually tell the same story as the printed diagnostics but can sometimes reveal issues that are not obvious from the numbers alone (e.g. multimodality, poor mixing, or a small number of effective samples).</span>
<span id="cb21-194"><a href="#cb21-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-195"><a href="#cb21-195" aria-hidden="true" tabindex="-1"></a><span class="in">```{r diagnostics-plots}</span></span>
<span id="cb21-196"><a href="#cb21-196" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 6</span></span>
<span id="cb21-197"><a href="#cb21-197" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bayes_phylo, <span class="at">ask =</span> <span class="cn">FALSE</span>)</span>
<span id="cb21-198"><a href="#cb21-198" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-199"><a href="#cb21-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-200"><a href="#cb21-200" aria-hidden="true" tabindex="-1"></a>Note that there appear to be some issues with mixing for some parameters (low ESS and chains are dragging), so we should play around with MCMC parameters to try to improve this, but this isn't bad for demonstration purposes.</span>
<span id="cb21-201"><a href="#cb21-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-202"><a href="#cb21-202" aria-hidden="true" tabindex="-1"></a>Recall that we also fit the same model with <span class="in">`sigma = TRUE`</span>. We can look at how the output for that model compares to the one we have just fit:</span>
<span id="cb21-203"><a href="#cb21-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-204"><a href="#cb21-204" aria-hidden="true" tabindex="-1"></a><span class="in">```{r diagnostics2}</span></span>
<span id="cb21-205"><a href="#cb21-205" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bayes_phylo2)</span>
<span id="cb21-206"><a href="#cb21-206" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-207"><a href="#cb21-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-208"><a href="#cb21-208" aria-hidden="true" tabindex="-1"></a>Here, we can see that <span class="in">`sigma`</span> is estimated and it matches the <span class="in">`sd_es_ID__Intercept`</span> from the first model, which is the observation-level random effect. The two models are essentially the same, but the first one is more consistent with the way we have been modelling residual error in <span class="in">`metafor`</span>. However, we can see that this is a more elegant way to model residual error for meta-analysis with <span class="in">`brms`</span> (which we recommend) as you can see improvements in the MCMC diagnostics for the second model compared to the first one because of the different way the model is parameterised. So, we've solved our mixing issues!</span>
<span id="cb21-209"><a href="#cb21-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-210"><a href="#cb21-210" aria-hidden="true" tabindex="-1"></a><span class="fu">### Posterior summaries</span></span>
<span id="cb21-211"><a href="#cb21-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-212"><a href="#cb21-212" aria-hidden="true" tabindex="-1"></a>The overall effect (intercept on the $Z_r$ scale) and 95% credible interval:</span>
<span id="cb21-213"><a href="#cb21-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-214"><a href="#cb21-214" aria-hidden="true" tabindex="-1"></a><span class="in">```{r posterior-summary}</span></span>
<span id="cb21-215"><a href="#cb21-215" aria-hidden="true" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">posterior_summary</span>(bayes_phylo2, <span class="at">variable =</span> <span class="st">"b_Intercept"</span>)</span>
<span id="cb21-216"><a href="#cb21-216" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-217"><a href="#cb21-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-218"><a href="#cb21-218" aria-hidden="true" tabindex="-1"></a>Variance components — between-study, within-study residual (here estimated as <span class="in">`sigma`</span> because we used <span class="in">`se(..., sigma = TRUE)`</span> and dropped the OLRE), non-phylogenetic species, and phylogenetic species:</span>
<span id="cb21-219"><a href="#cb21-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-220"><a href="#cb21-220" aria-hidden="true" tabindex="-1"></a><span class="in">```{r variance-components}</span></span>
<span id="cb21-221"><a href="#cb21-221" aria-hidden="true" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">posterior_summary</span>(bayes_phylo2, <span class="at">variable =</span> <span class="fu">c</span>(<span class="st">"sd_study_ID__Intercept"</span>,</span>
<span id="cb21-222"><a href="#cb21-222" aria-hidden="true" tabindex="-1"></a>                                                   <span class="st">"sigma"</span>,</span>
<span id="cb21-223"><a href="#cb21-223" aria-hidden="true" tabindex="-1"></a>                                                   <span class="st">"sd_species__Intercept"</span>,</span>
<span id="cb21-224"><a href="#cb21-224" aria-hidden="true" tabindex="-1"></a>                                                   <span class="st">"sd_species_OTL__Intercept"</span>))</span>
<span id="cb21-225"><a href="#cb21-225" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-226"><a href="#cb21-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-227"><a href="#cb21-227" aria-hidden="true" tabindex="-1"></a><span class="fu">#### What does the model output tell us?</span></span>
<span id="cb21-228"><a href="#cb21-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-229"><a href="#cb21-229" aria-hidden="true" tabindex="-1"></a>::: {.panel-tabset}</span>
<span id="cb21-230"><a href="#cb21-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-231"><a href="#cb21-231" aria-hidden="true" tabindex="-1"></a><span class="fu">## Task</span></span>
<span id="cb21-232"><a href="#cb21-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-233"><a href="#cb21-233" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Is there an overall positive or negative relationship between physiology and movement?**</span></span>
<span id="cb21-234"><a href="#cb21-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-235"><a href="#cb21-235" aria-hidden="true" tabindex="-1"></a><span class="fu">## Answer</span></span>
<span id="cb21-236"><a href="#cb21-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-237"><a href="#cb21-237" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; The posterior mean for the intercept is </span><span class="in">`r round(brms::posterior_summary(bayes_phylo2, variable = "b_Intercept")[, "Estimate"], 3)`</span><span class="at"> with a 95% credible interval of </span><span class="in">`r round(brms::posterior_summary(bayes_phylo2, variable = "b_Intercept")[, "Q2.5"], 3)`</span><span class="at"> to </span><span class="in">`r round(brms::posterior_summary(bayes_phylo2, variable = "b_Intercept")[, "Q97.5"], 3)`</span><span class="at">. As in the </span><span class="co">[</span><span class="ot">REML analysis</span><span class="co">](phylo.qmd)</span><span class="at">, the overall relationship is **positive** and the credible interval nearly excludes zero. Compare these numbers with the REML estimates from the previous chapter — they should be fairly similar. However, the Bayesian fit also gives us full posterior distributions for all parameters. For example, we can look at every variance component with </span><span class="in">`brms::mcmc_plot(bayes_phylo2, variable = "^sd_", regex = TRUE)`</span><span class="at">.</span></span>
<span id="cb21-238"><a href="#cb21-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-239"><a href="#cb21-239" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb21-240"><a href="#cb21-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-241"><a href="#cb21-241" aria-hidden="true" tabindex="-1"></a><span class="fu">## **Extracting Posterior distributions and Derived Quantities**</span></span>
<span id="cb21-242"><a href="#cb21-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-243"><a href="#cb21-243" aria-hidden="true" tabindex="-1"></a>One of the key benefits of the Bayesian framework is that we can propagate uncertainty into any derived quantity simply by computing it draw-by-draw across the posterior. As an example, we will compute a full posterior distribution for $I^2_{total}$ — the proportion of total variance attributable to genuine heterogeneity (rather than sampling noise) — using the same definition as in the <span class="co">[</span><span class="ot">Heterogeneity chapter</span><span class="co">](het.qmd)</span>:</span>
<span id="cb21-244"><a href="#cb21-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-245"><a href="#cb21-245" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-246"><a href="#cb21-246" aria-hidden="true" tabindex="-1"></a>I^2_{total} = \frac{\tau^2 + \sigma_{k}^2 + \sigma_{a}^2 + \sigma_{e}^2}{\tau^2 + \sigma_{k}^2 + \sigma_{a}^2 + \sigma_{e}^2 + \sigma_{m}^2}</span>
<span id="cb21-247"><a href="#cb21-247" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-248"><a href="#cb21-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-249"><a href="#cb21-249" aria-hidden="true" tabindex="-1"></a>The denominator includes the **typical sampling variance** $\sigma^2_m$, which is a fixed function of the inverse-variance weights $w_i = 1/v_i$ and is computed once from the data (not estimated by the model):</span>
<span id="cb21-250"><a href="#cb21-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-251"><a href="#cb21-251" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-252"><a href="#cb21-252" aria-hidden="true" tabindex="-1"></a>\sigma_{m}^2 = \frac{(k-1)\sum w_i}{(\sum w_i)^2 - \sum w_i^2}</span>
<span id="cb21-253"><a href="#cb21-253" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-254"><a href="#cb21-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-255"><a href="#cb21-255" aria-hidden="true" tabindex="-1"></a>Omitting $\sigma^2_m$ would inflate $I^2_{total}$ because the denominator would no longer represent total variance. With $\sigma^2_m$ in hand, we compute the posterior of $I^2_{total}$ by squaring each posterior draw of the random-effect standard deviations, summing them, and dividing by the total. We first want to extract the posterior draws from the model object. We know we should have 8000 draws (rows) in total (4 chains x 2000 iterations) but the effective number of draws may be lower due to autocorrelation. We can extract the posterior draws as a data frame with <span class="in">`brms::as_draws_df()`</span>, which gives us one column per parameter and one row per draw.</span>
<span id="cb21-256"><a href="#cb21-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-257"><a href="#cb21-257" aria-hidden="true" tabindex="-1"></a><span class="in">```{r derived-quantities}</span></span>
<span id="cb21-258"><a href="#cb21-258" aria-hidden="true" tabindex="-1"></a><span class="co"># Typical sampling variance </span></span>
<span id="cb21-259"><a href="#cb21-259" aria-hidden="true" tabindex="-1"></a>w        <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> zr_data<span class="sc">$</span>V_Zr</span>
<span id="cb21-260"><a href="#cb21-260" aria-hidden="true" tabindex="-1"></a>k        <span class="ot">&lt;-</span> <span class="fu">nrow</span>(zr_data)</span>
<span id="cb21-261"><a href="#cb21-261" aria-hidden="true" tabindex="-1"></a>sigma2_m <span class="ot">&lt;-</span> (k <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="fu">sum</span>(w) <span class="sc">/</span> (<span class="fu">sum</span>(w)<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> <span class="fu">sum</span>(w<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb21-262"><a href="#cb21-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-263"><a href="#cb21-263" aria-hidden="true" tabindex="-1"></a><span class="co"># Posterior draws of every random-effect SD; square to get variances!</span></span>
<span id="cb21-264"><a href="#cb21-264" aria-hidden="true" tabindex="-1"></a><span class="co"># Remember, for bayes_phylo2 the within-study residual variance is estimated as </span></span>
<span id="cb21-265"><a href="#cb21-265" aria-hidden="true" tabindex="-1"></a><span class="co"># `sigma` (we used se(..., sigma = TRUE) and dropped the (1 | es_ID) </span></span>
<span id="cb21-266"><a href="#cb21-266" aria-hidden="true" tabindex="-1"></a><span class="co"># observation-level random effect).</span></span>
<span id="cb21-267"><a href="#cb21-267" aria-hidden="true" tabindex="-1"></a>draws        <span class="ot">&lt;-</span> brms<span class="sc">::</span><span class="fu">as_draws_df</span>(bayes_phylo2)</span>
<span id="cb21-268"><a href="#cb21-268" aria-hidden="true" tabindex="-1"></a>sigma2_study <span class="ot">&lt;-</span> draws<span class="sc">$</span>sd_study_ID__Intercept<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb21-269"><a href="#cb21-269" aria-hidden="true" tabindex="-1"></a>sigma2_es    <span class="ot">&lt;-</span> draws<span class="sc">$</span>sigma<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb21-270"><a href="#cb21-270" aria-hidden="true" tabindex="-1"></a>sigma2_spp   <span class="ot">&lt;-</span> draws<span class="sc">$</span>sd_species__Intercept<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb21-271"><a href="#cb21-271" aria-hidden="true" tabindex="-1"></a>sigma2_phylo <span class="ot">&lt;-</span> draws<span class="sc">$</span>sd_species_OTL__Intercept<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb21-272"><a href="#cb21-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-273"><a href="#cb21-273" aria-hidden="true" tabindex="-1"></a>var_total <span class="ot">&lt;-</span> sigma2_study <span class="sc">+</span> sigma2_es <span class="sc">+</span> sigma2_spp <span class="sc">+</span> sigma2_phylo</span>
<span id="cb21-274"><a href="#cb21-274" aria-hidden="true" tabindex="-1"></a>I2_total  <span class="ot">&lt;-</span> var_total <span class="sc">/</span> (var_total <span class="sc">+</span> sigma2_m)</span>
<span id="cb21-275"><a href="#cb21-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-276"><a href="#cb21-276" aria-hidden="true" tabindex="-1"></a><span class="co"># Posterior summary (median + 95% credible interval)</span></span>
<span id="cb21-277"><a href="#cb21-277" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(I2_total, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>))</span>
<span id="cb21-278"><a href="#cb21-278" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-279"><a href="#cb21-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-280"><a href="#cb21-280" aria-hidden="true" tabindex="-1"></a>Because we computed $I^2_{total}$ per draw, we have the *posterior distribution* of $I^2_{total}$ rather than a single point estimate. The 95% interval reported above is a credible interval that fully reflects uncertainty in every variance component simultaneously — something that is awkward to obtain from the REML fit without bootstrapping.</span>
<span id="cb21-281"><a href="#cb21-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-282"><a href="#cb21-282" aria-hidden="true" tabindex="-1"></a>We can also now nicely visualise the posterior distribution of $I^2_{total}$:</span>
<span id="cb21-283"><a href="#cb21-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-284"><a href="#cb21-284" aria-hidden="true" tabindex="-1"></a><span class="in">```{r I2-plot}</span></span>
<span id="cb21-285"><a href="#cb21-285" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(I2_total), <span class="fu">aes</span>(<span class="at">x =</span> I2_total)) <span class="sc">+</span></span>
<span id="cb21-286"><a href="#cb21-286" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb21-287"><a href="#cb21-287" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">quantile</span>(I2_total, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>)), <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb21-288"><a href="#cb21-288" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(I<span class="sc">^</span><span class="dv">2</span>[total]), <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb21-289"><a href="#cb21-289" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb21-290"><a href="#cb21-290" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-291"><a href="#cb21-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-292"><a href="#cb21-292" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Your turn: $I^2_{study}$</span></span>
<span id="cb21-293"><a href="#cb21-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-294"><a href="#cb21-294" aria-hidden="true" tabindex="-1"></a>::: {.panel-tabset}</span>
<span id="cb21-295"><a href="#cb21-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-296"><a href="#cb21-296" aria-hidden="true" tabindex="-1"></a><span class="fu">## Task</span></span>
<span id="cb21-297"><a href="#cb21-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-298"><a href="#cb21-298" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Adapt the code above to compute the posterior of $I^2_{study}$** — the fraction of total variance attributable to *between-study* heterogeneity alone. Report the posterior median and 95% credible interval, and contrast it with $I^2_{total}$.</span></span>
<span id="cb21-299"><a href="#cb21-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-300"><a href="#cb21-300" aria-hidden="true" tabindex="-1"></a><span class="fu">## Answer</span></span>
<span id="cb21-301"><a href="#cb21-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-302"><a href="#cb21-302" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Only the numerator changes; we re-use </span><span class="in">`sigma2_study`</span><span class="at">, </span><span class="in">`var_total`</span><span class="at"> and </span><span class="in">`sigma2_m`</span><span class="at"> from the chunk above. Formally:</span></span>
<span id="cb21-303"><a href="#cb21-303" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb21-304"><a href="#cb21-304" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; $$</span></span>
<span id="cb21-305"><a href="#cb21-305" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; I^2_{study} = \frac{\tau^2}{\tau^2 + \sigma_{k}^2 + \sigma_{a}^2 + \sigma_{e}^2 + \sigma_{m}^2}</span></span>
<span id="cb21-306"><a href="#cb21-306" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; $$</span></span>
<span id="cb21-307"><a href="#cb21-307" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb21-308"><a href="#cb21-308" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; ```{r I2-study}</span></span>
<span id="cb21-309"><a href="#cb21-309" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; I2_study &lt;- sigma2_study / (var_total + sigma2_m)</span></span>
<span id="cb21-310"><a href="#cb21-310" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; quantile(I2_study, c(0.025, 0.5, 0.975))</span></span>
<span id="cb21-311"><a href="#cb21-311" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; ```</span></span>
<span id="cb21-312"><a href="#cb21-312" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb21-313"><a href="#cb21-313" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; The posterior median for $I^2_{study}$ is `r round(median(I2_study), 3)` with a 95% credible interval of `r round(quantile(I2_study, 0.025), 3)` to `r round(quantile(I2_study, 0.975), 3)`. Comparing this with $I^2_{total}$ (median </span><span class="in">`r round(median(I2_total), 3)`</span><span class="at">) tells you how much of the *real* heterogeneity is concentrated at the study level versus spread across the other variance components (within-study residual, non-phylogenetic species, phylogenetic). You can compute $I^2$ for any single component the same way — just put its squared SD in the numerator.</span></span>
<span id="cb21-314"><a href="#cb21-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-315"><a href="#cb21-315" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb21-316"><a href="#cb21-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-317"><a href="#cb21-317" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb21-318"><a href="#cb21-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-319"><a href="#cb21-319" aria-hidden="true" tabindex="-1"></a>This is one of the powerful features of Bayesian meta-analysis; the ability to derive full posterior distributions for any quantity of interest by computing it draw-by-draw across the posterior. You can use this same approach to get a posterior distribution for the overall effect size, prediction intervals, or any other derived quantity you like. When you have moderators, it also means you can get overall means for each group or even contrasts for specific comparisons between levels of a moderator that maybe the model doesn't present by default. </span>
<span id="cb21-320"><a href="#cb21-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-321"><a href="#cb21-321" aria-hidden="true" tabindex="-1"></a><span class="fu">## **References**</span></span>
<span id="cb21-322"><a href="#cb21-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-323"><a href="#cb21-323" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">div</span><span class="ot"> id</span><span class="op">=</span><span class="st">"refs"</span><span class="dt">&gt;&lt;/</span><span class="kw">div</span><span class="dt">&gt;</span></span>
<span id="cb21-324"><a href="#cb21-324" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb21-325"><a href="#cb21-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-326"><a href="#cb21-326" aria-hidden="true" tabindex="-1"></a><span class="fu">## **Session Information**</span></span>
<span id="cb21-327"><a href="#cb21-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-330"><a href="#cb21-330" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb21-331"><a href="#cb21-331" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: sessioninfo-bayes</span></span>
<span id="cb21-332"><a href="#cb21-332" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb21-333"><a href="#cb21-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-334"><a href="#cb21-334" aria-hidden="true" tabindex="-1"></a><span class="fu">pander</span>(<span class="fu">sessionInfo</span>(), <span class="at">locale =</span> <span class="cn">FALSE</span>)</span>
<span id="cb21-335"><a href="#cb21-335" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
</code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>