<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Heterogeneity in Meta-analysis – Meta-Analysis Workshop</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./metaregression.html" rel="next">
<link href="./multi-level.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-47d0440b87685b87fa0f37ef00e16435.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./het.html"><strong>Heterogeneity</strong></a></li><li class="breadcrumb-item"><a href="./het.html"><span class="chapter-title">Heterogeneity in Meta-analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./figs/logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Meta-Analysis Workshop</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/noble-lab/meta-analysis_workshop" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text"><strong>Welcome</strong></span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Welcome</strong></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text"><strong>Fundamentals of Meta-Analysis</strong></span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction-to-meta.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introduction to Meta-analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./systematic_review.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Systematic Review</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text"><strong>Effect Sizes</strong></span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./effect-size.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Calculating and interpreting effect sizes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nuis-het.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Nuisance heterogeneity</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text"><strong>Statistical Models</strong></span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fixed-vs-random.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Fixed versus Random Effects Meta-analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multi-level.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Multi-level Meta-analysis</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text"><strong>Heterogeneity</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./het.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Heterogeneity in Meta-analysis</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text"><strong>Meta-Regression</strong></span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./metaregression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Multi-level Meta-regression</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text"><strong>Advanced Topics</strong></span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./phylo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Phylogenetic Meta-analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./complex-nonind.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Complex Non-independence in Meta-analysis</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text"><strong>Publication Bias</strong></span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pub-bias1.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Publication Bias in Meta-analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pub-bias2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Publication Bias: Analytical Approaches</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction-to-heterogeneity-in-meta-analysis" id="toc-introduction-to-heterogeneity-in-meta-analysis" class="nav-link active" data-scroll-target="#introduction-to-heterogeneity-in-meta-analysis"><strong>Introduction to Heterogeneity in Meta-analysis</strong></a></li>
  <li><a href="#measures-of-heterogeneity" id="toc-measures-of-heterogeneity" class="nav-link" data-scroll-target="#measures-of-heterogeneity"><strong>Measures of Heterogeneity</strong></a>
  <ul class="collapse">
  <li><a href="#visualising-heterogeneity-with-an-orchard-plot" id="toc-visualising-heterogeneity-with-an-orchard-plot" class="nav-link" data-scroll-target="#visualising-heterogeneity-with-an-orchard-plot">Visualising Heterogeneity with an Orchard Plot</a></li>
  <li><a href="#proportion-of-total-heterogeneity-i_total2" id="toc-proportion-of-total-heterogeneity-i_total2" class="nav-link" data-scroll-target="#proportion-of-total-heterogeneity-i_total2">Proportion of Total Heterogeneity: <span class="math inline">\(I_{total}^2\)</span></a></li>
  <li><a href="#beyond-i2-mean-standardised-heterogeneity-cvh_2-and-m_2" id="toc-beyond-i2-mean-standardised-heterogeneity-cvh_2-and-m_2" class="nav-link" data-scroll-target="#beyond-i2-mean-standardised-heterogeneity-cvh_2-and-m_2">Beyond <span class="math inline">\(I^2\)</span>: Mean-Standardised Heterogeneity (<span class="math inline">\(CVH_2\)</span> and <span class="math inline">\(M_2\)</span>)</a></li>
  <li><a href="#prediction-intervals" id="toc-prediction-intervals" class="nav-link" data-scroll-target="#prediction-intervals">Prediction Intervals</a></li>
  <li><a href="#q-tests-inferential-tests-to-determine-excess-heterogeneity" id="toc-q-tests-inferential-tests-to-determine-excess-heterogeneity" class="nav-link" data-scroll-target="#q-tests-inferential-tests-to-determine-excess-heterogeneity"><em>Q</em>-tests: Inferential Tests to Determine Excess Heterogeneity</a></li>
  <li><a href="#proportion-of-variation-explained-by-the-model-r2_marginal-and-r2_conditional" id="toc-proportion-of-variation-explained-by-the-model-r2_marginal-and-r2_conditional" class="nav-link" data-scroll-target="#proportion-of-variation-explained-by-the-model-r2_marginal-and-r2_conditional">Proportion of Variation Explained by the Model: <span class="math inline">\(R^2_{marginal}\)</span> and <span class="math inline">\(R^2_{conditional}\)</span></a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><strong>Conclusion</strong></a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><strong>References</strong></a></li>
  <li><a href="#session-information" id="toc-session-information" class="nav-link" data-scroll-target="#session-information"><strong>Session Information</strong></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./het.html"><strong>Heterogeneity</strong></a></li><li class="breadcrumb-item"><a href="./het.html"><span class="chapter-title">Heterogeneity in Meta-analysis</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-title">Heterogeneity in Meta-analysis</span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction-to-heterogeneity-in-meta-analysis" class="level2">
<h2 class="anchored" data-anchor-id="introduction-to-heterogeneity-in-meta-analysis"><strong>Introduction to Heterogeneity in Meta-analysis</strong></h2>
<p>In physiology, ecology and evolution, we deal with many different populations, species, experimental designs etc. As such, we’re not just interested in understanding ‘what the overall effect’ actually is (in fact, we may not even care in many cases), but we are mainly focused on attempting to understand what factors (e.g., biological, methodological) explain variation in effects <span class="citation" data-cites="Noble2022 Lag2010 Gurevitch2018">(<a href="#ref-Gurevitch2018" role="doc-biblioref">Gurevitch et al., 2018</a>; <a href="#ref-Lag2010" role="doc-biblioref">Lajeunesse, 2010</a>; <a href="#ref-Noble2022" role="doc-biblioref">Noble et al., 2022</a>)</span>. Understanding and quantifying how much variability in effects exist, whether this is more than what we expect by chance, and what factors explain variation is a primary goal of meta-analysis.</p>
<p>Meta-analytic mean estimates need to be interpreted in the context of how much variation in effects exist within and across studies. As such, reporting upon measures of variability, or what is referred to as ‘heterogeneity’ in meta-analysis, is essential to meta-analysis and should never be ignored (even though it often is unfortunately) <span class="citation" data-cites="ODea2021 NakagawaSantos2012 Borenstein2019 Nakagawa2017 Gurevitch2018">(<a href="#ref-Borenstein2019" role="doc-biblioref">Borenstein, 2019</a>; <a href="#ref-Gurevitch2018" role="doc-biblioref">Gurevitch et al., 2018</a>; <a href="#ref-NakagawaSantos2012" role="doc-biblioref">Nakagawa and Santos, 2012</a>; <a href="#ref-Nakagawa2017" role="doc-biblioref">Nakagawa et al., 2017a</a>; <a href="#ref-ODea2021" role="doc-biblioref">O’Dea et al., 2021</a>)</span>.</p>
<p>There are a number of important metrics of heterogeneity that are commonly used and reported upon in the meta-analytic literature <span class="citation" data-cites="NakagawaSantos2012 Borenstein2019 Nakagawa2017">(<a href="#ref-Borenstein2019" role="doc-biblioref">Borenstein, 2019</a>; <a href="#ref-NakagawaSantos2012" role="doc-biblioref">Nakagawa and Santos, 2012</a>; <a href="#ref-Nakagawa2017" role="doc-biblioref">Nakagawa et al., 2017a</a>)</span>. We’ll overview in this tutorial how to calculate, and interpret, many of the common types and what they mean with respect to interpreting the meta-analytic mean. Understanding the consistency of results across studies tells one a great deal about how likely an effect is going to be picked up in future studies and whether we can make broad general conclusions.</p>
</section>
<section id="measures-of-heterogeneity" class="level2">
<h2 class="anchored" data-anchor-id="measures-of-heterogeneity"><strong>Measures of Heterogeneity</strong></h2>
<p>The most commonly encountered measures of heterogeneity in comparative physiology, and indeed ecology and evolution more generally, are results of <em>Q</em> tests, <span class="math inline">\(I^2\)</span> metrics (or raw <span class="math inline">\(\tau^2\)</span> or variance estimates), and less commonly, prediction intervals. These measures of heterogeneity (even if just a few) should always be presented along side meta-analytic mean effect size estimates because they tell the reader a great deal about the ‘consistency’ of results (e.g., prediction intervals, total heterogeneity) or the relative contribution of different factors to effect size variation (i.e., different measures of <span class="math inline">\(I^2\)</span>). We’ll overview these different metrics and show how to calculate an interpret them in meta-analyses.</p>
<p>For the purpose of this tutorial we’ll assume the following multilevel meta-analytic model is fit as described in the <a href="./multi-level.html">multilevel model tutorial</a>. If you can’t quite remember all the notation we recommend going back to review that page.</p>
<p><span class="math display">\[
\begin{aligned}
y_{i} &amp;= \mu + s_{j[i]} + spp_{k[i]} + e_{i} + m_{i} \\
m_{i} &amp;\sim N(0, v_{i}) \\
s_{j} &amp;\sim N(0, \tau^2) \\
spp_{k} &amp;\sim N(0, \sigma_{k}^2) \\
e_{i} &amp;\sim N(0, \sigma_{e}^2)
\end{aligned}
\]</span> We will return to the meta-analysis by <span class="citation" data-cites="Pottier2021">Pottier et al. (<a href="#ref-Pottier2021" role="doc-biblioref">2021</a>)</span> that we already detailed in the <a href="./multi-level.html">multilevel meta-analysis tutorial</a>. We’ll walk through the different types of heterogeneity statistics that we can calculate for the model.</p>
<p><img src="./figs/pottier.png" class="img-fluid"></p>
<p>We can re-load that data again and get it ready for analysis using the code below:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("pacman") ; uncomment this line if you haven't already installed 'pacman'</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(metafor, tidyverse, orchaRd, devtools, patchwork, R.rsp, emmeans, flextable)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>asr_dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://osf.io/qn2af/download"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">#' @title arr</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">#' @description Calculates the acclimation response ratio (ARR).  </span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param t2_l  Lowest of the two treatment temperatures</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param t1_h  Highest of the two treatment temperatures</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param x1_h  Mean trait value at high temperature</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param x2_l  Mean trait value at low temperature</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param sd1_h Standard deviation of mean trait value at high temperature</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param sd2_l Standard deviation of mean trait value at low temperature</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param n1_h  Sample size at high temperature</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param n2_l  Sample size at low temperature</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>arr <span class="ot">&lt;-</span> <span class="cf">function</span>(x1_h, x2_l, sd1_h, sd2_l, n1_h, n2_l, t1_h, t2_l){</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>        ARR <span class="ot">&lt;-</span> (x1_h <span class="sc">-</span> x2_l)<span class="sc">/</span>(t1_h <span class="sc">-</span> t2_l)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>      V_ARR <span class="ot">&lt;-</span> ((<span class="dv">1</span><span class="sc">/</span>(t1_h <span class="sc">-</span> t2_l))<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span>(sd2_l<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n2_l <span class="sc">+</span> sd1_h<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n1_h))</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="fu">return</span>(<span class="fu">data.frame</span>(ARR, V_ARR))</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the effect sizes</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>asr_dat<span class="ot">&lt;-</span>asr_dat <span class="sc">%&gt;%</span> </span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>              <span class="fu">mutate</span>(<span class="at">ARR=</span> <span class="fu">arr</span>(<span class="at">x1_h =</span> mean_high, <span class="at">x2_l =</span> mean_low, <span class="at">t1_h =</span> acc_temp_high, <span class="at">t2_l =</span> acc_temp_low, </span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>                              <span class="at">sd1_h =</span> sd_high, <span class="at">sd2_l =</span> sd_low, <span class="at">n1_h =</span> n_high_adj, <span class="at">n2_l =</span> n_low_adj)[,<span class="dv">1</span>], </span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>                     <span class="at">V_ARR =</span> <span class="fu">arr</span>(<span class="at">x1_h =</span>  mean_high, <span class="at">x2_l =</span> mean_low, <span class="at">t1_h =</span> acc_temp_high, <span class="at">t2_l =</span> acc_temp_low, </span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>                           <span class="at">sd1_h =</span> sd_high, <span class="at">sd2_l =</span> sd_low, <span class="at">n1_h =</span> n_high_adj, <span class="at">n2_l =</span> n_low_adj)[,<span class="dv">2</span>]) <span class="sc">%&gt;%</span> </span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>                <span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">"female"</span>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-fit the multilevel meta-analytic model</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>MLMA <span class="ot">&lt;-</span> metafor<span class="sc">::</span><span class="fu">rma.mv</span>(<span class="at">yi=</span> ARR<span class="sc">~</span> <span class="dv">1</span>, <span class="at">V =</span> V_ARR, </span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>                   <span class="at">method=</span><span class="st">"REML"</span>,</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>                   <span class="at">random=</span><span class="fu">list</span>(<span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>species_ID,</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>                               <span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>study_ID,</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>                               <span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>es_ID), </span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>                   <span class="at">dfs =</span> <span class="st">"contain"</span>,</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>                   <span class="at">test=</span><span class="st">"t"</span>,</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data=</span>asr_dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We’ll now use this model to calculate various heterogeneity statistics in addition to the ones already calculated (which we will describe below). Before doing so, it helps to visualise the data and the model output together.</p>
<section id="visualising-heterogeneity-with-an-orchard-plot" class="level3">
<h3 class="anchored" data-anchor-id="visualising-heterogeneity-with-an-orchard-plot">Visualising Heterogeneity with an Orchard Plot</h3>
<p>The <code>orchaRd</code> package provides the <code>orchard_plot()</code> function, which is a great tool for communicating meta-analytic results and heterogeneity at the same time <span class="citation" data-cites="Nakagawa2021c Nakagawa2023">(<a href="#ref-Nakagawa2021c" role="doc-biblioref">Nakagawa et al., 2021</a>; <a href="#ref-Nakagawa2023" role="doc-biblioref">Nakagawa et al., 2023</a>)</span>. The plot shows:</p>
<ul>
<li>the <strong>meta-analytic mean</strong> as a point estimate (the filled circle in <a href="#fig-orchard" class="quarto-xref">Figure&nbsp;<span>7.1</span></a>);</li>
<li>a <strong>thick bar</strong> spanning the 95% confidence interval (uncertainty around the mean);</li>
<li>a <strong>thin bar</strong> spanning the 95% <strong>prediction interval</strong> (the expected range of a future effect size — the key to visualising heterogeneity);</li>
<li>individual effect sizes are plotted as points scaled by their precision (<span class="math inline">\(1/\sqrt{v_i}\)</span>), so precise estimates appear larger.</li>
</ul>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>orchaRd<span class="sc">::</span><span class="fu">orchard_plot</span>(MLMA, <span class="at">group =</span> <span class="st">"species_ID"</span>, <span class="at">xlab =</span> <span class="st">"Acclimation Response Ratio (ARR, °C / °C)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-orchard" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-orchard-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="het_files/figure-html/fig-orchard-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-orchard-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.1: Orchard plot of acclimation response ratio (ARR) estimates across ectotherm species. The filled circle is the meta-analytic mean, the thick bar is the 95% confidence interval, and the thin bar is the 95% prediction interval. Individual effect sizes are scaled by precision.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The wide prediction interval in <a href="#fig-orchard" class="quarto-xref">Figure&nbsp;<span>7.1</span></a> immediately makes clear that there is substantial heterogeneity in ARR across species — the spread of effects is far greater than sampling error alone would produce. The numerical heterogeneity metrics below quantify this formally.</p>
</section>
<section id="proportion-of-total-heterogeneity-i_total2" class="level3">
<h3 class="anchored" data-anchor-id="proportion-of-total-heterogeneity-i_total2">Proportion of Total Heterogeneity: <span class="math inline">\(I_{total}^2\)</span></h3>
<p><span class="math inline">\(I^2\)</span> estimates are probably most commonly presented in the literature <span class="citation" data-cites="Higgins2003 Higgins2002 Nakagawa2017 Senior2016 Borenstein2019">(<a href="#ref-Borenstein2019" role="doc-biblioref">Borenstein, 2019</a>; <a href="#ref-Higgins2002" role="doc-biblioref">Higgins and Thompson, 2002</a>; <a href="#ref-Higgins2003" role="doc-biblioref">Higgins et al., 2003</a>; <a href="#ref-Nakagawa2017" role="doc-biblioref">Nakagawa et al., 2017a</a>; <a href="#ref-Senior2016" role="doc-biblioref">Senior et al., 2016</a>)</span>. There are different forms of <span class="math inline">\(I^2\)</span> that can be calculated, but the one that describes the proportion of effect size variation after accounting for total sampling variation is <span class="math inline">\(I_{total}^2\)</span> <span class="citation" data-cites="NakagawaSantos2012">(<a href="#ref-NakagawaSantos2012" role="doc-biblioref">Nakagawa and Santos, 2012</a>)</span>. Assuming we’re using our multilevel model described above, it’s calculated as follows:</p>
<p><span id="eq-itot"><span class="math display">\[
I^2_{total} = \frac{\sigma^2_{study} + \sigma^2_{phylogeny} + \sigma^2_{species} + \sigma^2_{residual}}{\sigma^2_{study} + \sigma^2_{phylogeny} + \sigma^2_{species} + \sigma^2_{residual} +\sigma^2_{m}}
\tag{7.1}\]</span></span></p>
<p>where <span class="math inline">\(\sigma^2_{total} = \sigma^2_{study} + \sigma^2_{phylogeny} + \sigma^2_{species} + \sigma^2_{residual} +\sigma^2_{m}\)</span> is the total effect size variance and <span class="math inline">\(\sigma^2_{m}\)</span> is the ‘typical’ sampling error variance calculated as:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="#eq-itot" class="quarto-xref">Equation&nbsp;<span>7.1</span></a> is the general form and may include a phylogenetic variance component (<span class="math inline">\(\sigma^2_{phylogeny}\)</span>) when a phylogenetic correlation structure is added to the model. In the model fitted here, no phylogenetic term is included, so <span class="math inline">\(\sigma^2_{phylogeny} = 0\)</span> and the numerator reduces to <span class="math inline">\(\sigma^2_{study} + \sigma^2_{species} + \sigma^2_{residual}\)</span>.</p>
</div>
</div>
<p><span id="eq-w"><span class="math display">\[
\sigma_{m}^2 = \sum w_{i}\left( k-1\right) / \left[ \left( \sum w_{i}\right)^2  + \sum w_{i}^2\right]
\tag{7.2}\]</span></span></p>
<p>where <em>k</em> is the number of studies and the weights, <span class="math inline">\(w_{i} = \frac{1}{v_{i}}\)</span>, can be calculated using the inverse of the sampling variance (<span class="math inline">\(v_{i}\)</span>) for each effect size, <em>i</em>. Below, we’ll make use of the <code>orchaRd</code> R package <span class="citation" data-cites="Nakagawa2021c Nakagawa2023">(<a href="#ref-Nakagawa2021c" role="doc-biblioref">Nakagawa et al., 2021</a>; <a href="#ref-Nakagawa2023" role="doc-biblioref">Nakagawa et al., 2023</a>)</span> to calculate various <span class="math inline">\(I^2\)</span> metrics. In fact, we can simply change what is in the numerator of <a href="#eq-itot" class="quarto-xref">Equation&nbsp;<span>7.1</span></a> to calculate a multitude of different <span class="math inline">\(I^2\)</span> metrics that can be useful in understanding the relative importance of factors most important in explaining effect size variation. We’ll do this below:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The orchaRd package has some convenient functions for calculating various I2 estimates including total. We'll load and install that package</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("pacman")</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(devtools, tidyverse, metafor, patchwork, R.rsp, emmeans, flextable)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co">#devtools::install_github("daniel1noble/orchaRd", force = TRUE, build_vignettes = TRUE)</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(orchaRd)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>orchaRd<span class="sc">::</span><span class="fu">i2_ml</span>(MLMA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     I2_Total I2_species_ID   I2_study_ID      I2_es_ID 
        98.42          2.98         58.48         36.96 </code></pre>
</div>
</div>
<section id="interpreting-i2-estimates" class="level4">
<h4 class="anchored" data-anchor-id="interpreting-i2-estimates"><strong>Interpreting <span class="math inline">\(I^2\)</span> Estimates</strong></h4>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">First Task!</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">First Answer!</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">Second Task!</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false">Second Answer!</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<blockquote class="blockquote">
<p><strong>Interpret the meaning of <span class="math inline">\(I_{Total}^2\)</span> from the multilevel meta-analytic model</strong></p>
</blockquote>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<blockquote class="blockquote">
<p>Overall, we have highly heterogeneous effect size data because sampling variation only contributes to 1.581% of the total variation in effects.</p>
</blockquote>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<blockquote class="blockquote">
<p><strong>Interpret the meaning of <span class="math inline">\(I_{study}^2\)</span> from the multilevel meta-analytic model</strong></p>
</blockquote>
</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<blockquote class="blockquote">
<p>From the multilevel meta-analytic model we find that 58.481% of the total variation in effect size estimates is the result of differences between studies.</p>
</blockquote>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="bootstrapping-i2-estimates" class="level4">
<h4 class="anchored" data-anchor-id="bootstrapping-i2-estimates">Bootstrapping <span class="math inline">\(I^2\)</span> Estimates</h4>
<p>There are also times that we may want to estimate, and present, uncertainty about these heterogeneity estimates. We can do that by bootstrapping 1000 times:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The orchaRd package has some convenient functions for calculating various I2 estimates including total. We'll load and install that package</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("pacman")</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(devtools, tidyverse, metafor, patchwork, R.rsp, emmeans, flextable)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co">#devtools::install_github("daniel1noble/orchaRd", force = TRUE, build_vignettes = TRUE)</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(orchaRd)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>orchaRd<span class="sc">::</span><span class="fu">i2_ml</span>(MLMA, <span class="at">boot =</span> <span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>               Est. 2.5% 97.5%
I2_Total      98.35 97.1  99.0
I2_species_ID  1.86  0.0  27.7
I2_study_ID   55.67 15.9  76.9
I2_es_ID      37.81 20.0  66.0</code></pre>
</div>
</div>
<p>Here, we can now see that <span class="math inline">\(I_{total}^2\)</span> has a fairly narrow 95% confidence interval of ~ 0.97 to 0.99.</p>
</section>
</section>
<section id="beyond-i2-mean-standardised-heterogeneity-cvh_2-and-m_2" class="level3">
<h3 class="anchored" data-anchor-id="beyond-i2-mean-standardised-heterogeneity-cvh_2-and-m_2">Beyond <span class="math inline">\(I^2\)</span>: Mean-Standardised Heterogeneity (<span class="math inline">\(CVH_2\)</span> and <span class="math inline">\(M_2\)</span>)</h3>
<p><span class="math inline">\(I^2\)</span> is a <em>variance-partitioning</em> metric: it tells you what fraction of total variance is genuine heterogeneity, not sampling error. That is useful, but it says nothing about whether the heterogeneity is large or small <em>relative to the mean effect</em>. Consider two studies that both have <span class="math inline">\(I^2_{total} = 0.90\)</span>. If one has a mean ARR of 0.001 °C/°C the absolute spread of effects is biologically negligible; if the other has a mean of 1 °C/°C the same 90% translates to enormous between-study variation. <span class="citation" data-cites="Yang2025het">Yang et al. (<a href="#ref-Yang2025het" role="doc-biblioref">2025</a>)</span> propose two mean-standardised alternatives that capture this information:</p>
<p><span id="eq-cvh2"><span class="math display">\[
CVH_2 = \frac{\sum \sigma^2}{\hat{\mu}^2}
\tag{7.3}\]</span></span></p>
<p><span id="eq-m2"><span class="math display">\[
M_2 = \frac{\sum \sigma^2}{\hat{\mu}^2 + \sum \sigma^2}
\tag{7.4}\]</span></span></p>
<p>where <span class="math inline">\(\hat{\mu}\)</span> is the meta-analytic mean and <span class="math inline">\(\sum \sigma^2\)</span> is the sum of all random-effect variance components (excluding sampling variance <span class="math inline">\(\sigma^2_m\)</span>). <span class="math inline">\(CVH_2\)</span> (<a href="#eq-cvh2" class="quarto-xref">Equation&nbsp;<span>7.3</span></a>) is analogous to a squared coefficient of variation: values <span class="math inline">\(&gt; 1\)</span> indicate that heterogeneity variance exceeds the mean effect squared. <span class="math inline">\(M_2\)</span> (<a href="#eq-m2" class="quarto-xref">Equation&nbsp;<span>7.4</span></a>) is bounded <span class="math inline">\([0, 1]\)</span> and can be read as the proportion of total ‘signal’ (mean<span class="math inline">\(^2\)</span> + variance) that is heterogeneity. <span class="citation" data-cites="Yang2025het">Yang et al. (<a href="#ref-Yang2025het" role="doc-biblioref">2025</a>)</span> recommend reporting both <span class="math inline">\(CVH_2\)</span> and <span class="math inline">\(M_2\)</span> alongside <span class="math inline">\(I^2\)</span> for a more complete picture. These metrics are implemented in <code>orchaRd</code>:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>orchaRd<span class="sc">::</span><span class="fu">cvh2_ml</span>(MLMA)   <span class="co"># Mean-standardised heterogeneity (variance scale)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     CVH2_Total CVH2_species_ID   CVH2_study_ID      CVH2_es_ID 
         0.9317          0.0282          0.5536          0.3499 </code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>orchaRd<span class="sc">::</span><span class="fu">m2_ml</span>(MLMA)     <span class="co"># Heterogeneity as fraction of total signal</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     M2_Total M2_species_ID   M2_study_ID      M2_es_ID 
       0.4823        0.0146        0.2866        0.1811 </code></pre>
</div>
</div>
<section id="interpreting-cvh_2-and-m_2" class="level4">
<h4 class="anchored" data-anchor-id="interpreting-cvh_2-and-m_2"><strong>Interpreting <span class="math inline">\(CVH_2\)</span> and <span class="math inline">\(M_2\)</span></strong></h4>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">Task!</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Answer!</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<blockquote class="blockquote">
<p><strong>Given the values of <span class="math inline">\(CVH_2\)</span> and <span class="math inline">\(M_2\)</span> above, what do they tell you about ARR heterogeneity that <span class="math inline">\(I^2_{total}\)</span> does not?</strong></p>
</blockquote>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<blockquote class="blockquote">
<p><span class="math inline">\(I^2_{total}\)</span> tells us that almost all of the variance in ARR estimates is real heterogeneity rather than sampling noise. But it does not tell us whether that heterogeneity is large or small on a biologically meaningful scale. <span class="math inline">\(CVH_2\)</span> answers that: a value much greater than 1 means the variance across studies is many times larger than the mean effect squared — i.e., the spread of true effects dwarfs the average effect. <span class="math inline">\(M_2\)</span> near 1 means variation dominates the signal; near 0 means the mean is large and stable relative to the scatter. Together these metrics clarify whether a high <span class="math inline">\(I^2\)</span> reflects <em>a lot of noise around a strong signal</em> or <em>a weak signal swamped by variation</em>.</p>
</blockquote>
</div>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="prediction-intervals" class="level3">
<h3 class="anchored" data-anchor-id="prediction-intervals">Prediction Intervals</h3>
<p>Prediction intervals (PI) are probably the best and most intuitive way to report heterogeneity of meta-analytic results <span class="citation" data-cites="Borenstein2019 Noble2022 Nakagawa2021c Nakagawa2023">(<a href="#ref-Borenstein2019" role="doc-biblioref">Borenstein, 2019</a>; <a href="#ref-Nakagawa2021c" role="doc-biblioref">Nakagawa et al., 2021</a>; <a href="#ref-Nakagawa2023" role="doc-biblioref">Nakagawa et al., 2023</a>; <a href="#ref-Noble2022" role="doc-biblioref">Noble et al., 2022</a>)</span>. Prediction intervals tell us how much we can expect a given effect size to vary across studies. More specifically, if we were to go out and conduct another study or experiment they tell us what the range of effect size estimates we are expected to observe 95% of the time from that new study <span class="citation" data-cites="Borenstein2019 Noble2022 Nakagawa2021c">(<a href="#ref-Borenstein2019" role="doc-biblioref">Borenstein, 2019</a>; <a href="#ref-Nakagawa2021c" role="doc-biblioref">Nakagawa et al., 2021</a>; <a href="#ref-Noble2022" role="doc-biblioref">Noble et al., 2022</a>)</span>.</p>
<p>Prediction intervals can be calculated in a similar way to confidence intervals but instead of just using the standard error, like we do with confidence interval construction, we add in the extra random-effect variance estimates. For our model above, the <strong>total</strong> PI — spanning all sources of variance — is:</p>
<p><span id="eq-pi"><span class="math display">\[
PI_{total} \sim  \bar{\mu} \pm 1.96 \sqrt{SE^2 + \sigma^2_{study} +  \sigma^2_{species} + \sigma^2_{residual}}
\tag{7.5}\]</span></span></p>
<p>However, <span class="citation" data-cites="Yang2024pi">Yang et al. (<a href="#ref-Yang2024pi" role="doc-biblioref">2024</a>)</span> highlight that the total PI conflates two distinct questions: (1) how variable are individual <em>effect size estimates</em> across all studies (which includes within-study residual variance, <span class="math inline">\(\sigma^2_{residual}\)</span>), and (2) how variable are <em>study-level means</em> across different biological contexts (which excludes within-study residual variance). The latter — called the <strong>study-level PI</strong> — is often the more relevant question for biological generality, because it captures how much we expect the average result to shift if we replicated the study in a new species or population context:</p>
<p><span id="eq-pi-study"><span class="math display">\[
PI_{study} \sim  \bar{\mu} \pm 1.96 \sqrt{SE^2 + \sigma^2_{study} +  \sigma^2_{species}}
\tag{7.6}\]</span></span></p>
<p><span class="citation" data-cites="Yang2024pi">Yang et al. (<a href="#ref-Yang2024pi" role="doc-biblioref">2024</a>)</span> found that across 512 ecological and evolutionary meta-analyses, most of the wide total PI came from within-study (residual) variance, and that study-level generality was far more common than the total PI implied.</p>
<p>We can compute both types easily:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Total PI — all variance components (predict() uses all sigma2 by default)</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(MLMA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
   pred     se  ci.lb  ci.ub   pi.lb  pi.ub 
 0.1668 0.0316 0.1010 0.2327 -0.1755 0.5091 </code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Study-level PI — between-study variance only (species_ID + study_ID, excluding es_ID)</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># sigma2 order matches the random= list: [species_ID, study_ID, es_ID]</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>vc <span class="ot">&lt;-</span> MLMA<span class="sc">$</span>sigma2</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>pi_study_se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(vc[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]) <span class="sc">+</span> MLMA<span class="sc">$</span>se<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Study-level 95% PI: ["</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">round</span>(MLMA<span class="sc">$</span>b <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> pi_study_se, <span class="dv">3</span>), <span class="st">","</span>,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">round</span>(MLMA<span class="sc">$</span>b <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> pi_study_se, <span class="dv">3</span>), <span class="st">"]</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Study-level 95% PI: [ -0.09 , 0.424 ]</code></pre>
</div>
</div>
<section id="interpreting-prediction-intervals" class="level4">
<h4 class="anchored" data-anchor-id="interpreting-prediction-intervals"><strong>Interpreting Prediction Intervals</strong></h4>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">Task!</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">Answer!</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<blockquote class="blockquote">
<p><strong>The meta-analytic mean ARR is 0.167. Compare the total PI to the study-level PI. What does each tell you, and why might one be more useful for assessing biological generality?</strong></p>
</blockquote>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<blockquote class="blockquote">
<p>The total 95% PI is wide — from -0.175 to 0.509 — suggesting a lot of inconsistency across individual effect size estimates. But much of that width comes from within-study residual variance (variation among effect sizes <em>within</em> a single study). The study-level PI, which retains only between-study variance (species and study components), is narrower and tells us how much the <em>average result</em> is expected to shift if we repeated the study in a new biological context. For biological generality, the study-level PI is the more relevant question: if most replications in new species or populations land near the mean, the phenomenon generalises well even if individual effect sizes are noisy.</p>
</blockquote>
</div>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="q-tests-inferential-tests-to-determine-excess-heterogeneity" class="level3">
<h3 class="anchored" data-anchor-id="q-tests-inferential-tests-to-determine-excess-heterogeneity"><em>Q</em>-tests: Inferential Tests to Determine Excess Heterogeneity</h3>
<p>So far we’ve talked about important heterogeneity statistics that describe, and quantify, the proportion of variability (<span class="math inline">\(I^2\)</span>) or the expected range of plausible effect size values which incorporate all the variance estimates (PI). But, how do we know that the heterogeneity in the data is greater than what we would expect by chance? It seems obvious that, if the <span class="math inline">\(I_{total}^2\)</span> is really high (i.e., &gt;85%) there’s a lot of variability in effects within and across studies. While these statistics are probably sufficient, <em>Q</em> tests can also be useful to more formally be able to make an inferential statement about whether heterogeneity is significantly greater than chance.</p>
<p>We have already encountered how to calculate the <em>Q</em>-statistic when discussing <a href="./fixed-vs-random.html">fixed and random effects</a> models. We can use the <em>Q</em> statistic now to compare this against a <span class="math inline">\(\chi^2\)</span>-distribution to calculate a p-value. <a href="https://wviechtb.github.io/metafor/reference/rma.mv.html">Wolfgang’s documentation</a> (<code>?rma.mv</code>) describes what the <em>Q</em>-test means:</p>
<blockquote class="blockquote">
<p>Cochran’s 𝑄-test, which tests whether the variability in the observed effect sizes or outcomes is larger than one would expect based on sampling variability (and the given covariances among the sampling errors) alone. A significant test suggests that the true effects/outcomes are heterogeneous.</p>
</blockquote>
<p><br> We don’t need to do anything special to get this test. In fact, this is automatically done by <code>metafor</code>:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(MLMA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Multivariate Meta-Analysis Model (k = 123; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed      factor 
sigma^2.1  0.0008  0.0280     29     no  species_ID 
sigma^2.2  0.0154  0.1241     21     no    study_ID 
sigma^2.3  0.0097  0.0987    123     no       es_ID 

Test for Heterogeneity:
Q(df = 122) = 3941.0055, p-val &lt; .0001

Model Results:

estimate      se    tval  df    pval   ci.lb   ci.ub      
  0.1668  0.0316  5.2857  20  &lt;.0001  0.1010  0.2327  *** 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<section id="describing-the-q-test" class="level4">
<h4 class="anchored" data-anchor-id="describing-the-q-test"><strong>Describing the <em>Q</em>-test</strong></h4>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true">Task!</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false">Answer!</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<blockquote class="blockquote">
<p><strong>How would you describe in a paper the <em>Q</em>-test from the <code>metafor</code> model above?</strong></p>
</blockquote>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<blockquote class="blockquote">
<p>Of course, there are a multitude of ways that we could describe this test in words, but one way to describe it in your results section might be as follows:</p>
</blockquote>
<p><br></p>
<blockquote class="blockquote">
<p>The overall mean ARR across ectotherms was 0.167 and differed significantly from zero (95% CI: 0.101 to 0.233, df = 20, t = 5.286, p &lt; 0.001). However, there was significant residual heterogeneity (<em>Q</em> = 3941.005, df = 122, p &lt; 0.001) with estimates expected to range from -0.175 to 0.509 (95% Prediction Interval) (<span class="math inline">\(I_{total}^2\)</span> = 98.419).</p>
</blockquote>
</div>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="proportion-of-variation-explained-by-the-model-r2_marginal-and-r2_conditional" class="level3">
<h3 class="anchored" data-anchor-id="proportion-of-variation-explained-by-the-model-r2_marginal-and-r2_conditional">Proportion of Variation Explained by the Model: <span class="math inline">\(R^2_{marginal}\)</span> and <span class="math inline">\(R^2_{conditional}\)</span></h3>
<p>You will probably have noticed that <span class="math inline">\(I^2\)</span> looks awfully familiar. It looks a lot like the way we might calculate <span class="math inline">\(R^2\)</span> described by <span class="citation" data-cites="NakagawaSchielzeth2013">Nakagawa and Schielzeth (<a href="#ref-NakagawaSchielzeth2013" role="doc-biblioref">2013</a>)</span>. Well, you would be correct! Often we also want to quantify how much variation is explained by our moderators and random effects in our multilevel meta-regression model <span class="citation" data-cites="Nakagawa2017ab NakagawaSchielzeth2013">(<a href="#ref-NakagawaSchielzeth2013" role="doc-biblioref">Nakagawa and Schielzeth, 2013</a>; <a href="#ref-Nakagawa2017ab" role="doc-biblioref">Nakagawa et al., 2017b</a>)</span>. This is done using <span class="math inline">\(R^2\)</span>. We can calculate different <span class="math inline">\(R^2\)</span> values depending on whether we ignore or include random effects in the numerator. If only the variation explained by moderators is included in the numerator than we call this <span class="math inline">\(R_{marginal}^2\)</span>, which is defined as:</p>
<p><span id="eq-r2"><span class="math display">\[
R^2_{marginal} = \frac{\sigma^2_{fixed}}{\sigma^2_{fixed} + \sigma^2_{study} + \sigma^2_{phylogeny} + \sigma^2_{species} + \sigma^2_{residual}}
\tag{7.7}\]</span></span></p>
<p>Note that this formula does not include <span class="math inline">\(\sigma^2_{m}\)</span> as sampling error variance is assumed to be known in meta-analysis. We won’t go into the details on how to calculate and interpret these because we’ll cover this in a later tutorial on <a href="./pub-bias1.html">publication bias</a>. Suffice it to say that this is a useful statistic for describing how much variation your moderators or model explain.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion"><strong>Conclusion</strong></h2>
<p>Hopefully it’s clear from this tutorial why explicitly estimating and reporting upon heterogeneity is so critically important in meta-analysis. Of course, some of these measures are only possible if we know the total sampling variance, which is not possible if one doesn’t use a weighted meta-analytic model.</p>
<p>No single metric tells the whole story. <span class="citation" data-cites="Yang2025het">Yang et al. (<a href="#ref-Yang2025het" role="doc-biblioref">2025</a>)</span> recommend a <strong>pluralistic approach</strong> to reporting heterogeneity:</p>
<ul>
<li><strong><span class="math inline">\(I^2_{total}\)</span></strong> — tells you what fraction of variance is real signal (not sampling noise);</li>
<li><strong><span class="math inline">\(CVH_2\)</span> and <span class="math inline">\(M_2\)</span></strong> — tell you how large that heterogeneity is relative to the mean effect, answering the question “does the average matter if effects are so variable?”;</li>
<li><strong>Prediction intervals</strong> — give the most intuitive summary of heterogeneity as the expected range of a new result. Reporting both the <em>total</em> PI and the <em>study-level</em> PI <span class="citation" data-cites="Yang2024pi">(<a href="#ref-Yang2024pi" role="doc-biblioref">Yang et al., 2024</a>)</span> helps distinguish noise within studies from genuine variation across biological contexts;</li>
<li><strong>An orchard plot</strong> — visualises all of the above at once and should accompany any numerical heterogeneity summary <span class="citation" data-cites="Nakagawa2021c Nakagawa2023">(<a href="#ref-Nakagawa2021c" role="doc-biblioref">Nakagawa et al., 2021</a>; <a href="#ref-Nakagawa2023" role="doc-biblioref">Nakagawa et al., 2023</a>)</span>.</li>
</ul>
<p>Together these metrics give a far richer picture of heterogeneity than <span class="math inline">\(I^2\)</span> alone.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references"><strong>References</strong></h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-Borenstein2019" class="csl-entry" role="listitem">
<strong>Borenstein, M.</strong> (2019). <a href="https://doi.org/10.7758/9781610448864.23">Heterogenity in meta-analysis</a>. In (ed. Cooper, H.), Hedges, L. V.), and Valentine, J. C.), pp. 454–466. New York: Russell Sage Foundation.
</div>
<div id="ref-Gurevitch2018" class="csl-entry" role="listitem">
<strong>Gurevitch, J., Koricheva, J., Nakagawa, S. and Stewart, G.</strong> (2018). <a href="https://doi.org/10.1038/nature25753">Meta-analysis and the science of research synthesis</a>. <em>Nature</em> <strong>555</strong>, 176–182.
</div>
<div id="ref-Higgins2002" class="csl-entry" role="listitem">
<strong>Higgins, J. P. T. and Thompson, S. G.</strong> (2002). <a href="https://doi.org/10.1002/sim.1186">Quantifying heterogeneity in a meta-analysis.</a> <em>Statistics in Medicine</em> <strong>21</strong>, 1539–1558.
</div>
<div id="ref-Higgins2003" class="csl-entry" role="listitem">
<strong>Higgins, J. P. T., Thompson, S. G., Deeks, J. J. and Altman, D. G.</strong> (2003). <a href="https://doi.org/10.1136/bmj.327.7414.557">Measuring inconsistency in meta-analyses</a>. <em>British Medical Journal</em> <strong>327</strong>, 557–560.
</div>
<div id="ref-Lag2010" class="csl-entry" role="listitem">
<strong>Lajeunesse, M. J.</strong> (2010). <a href="https://doi.org/10.1890/09-1530.1">Achieving synthesis with meta-analysis by combining and comparing all available studies</a>. <em>Ecology</em> <strong>91</strong>, 2561–2564.
</div>
<div id="ref-NakagawaSantos2012" class="csl-entry" role="listitem">
<strong>Nakagawa, S. and Santos, E. S.</strong> (2012). <a href="https://doi.org/10.1007/s10682-012-9555-5">Methodological issues and advances in biological meta-analysis</a>. <em>Evolutionary Ecology</em> <strong>26</strong>, 1253–1274.
</div>
<div id="ref-NakagawaSchielzeth2013" class="csl-entry" role="listitem">
<strong>Nakagawa, S. and Schielzeth, H.</strong> (2013). <a href="https://doi.org/10.1111/j.2041-210x.2012.00261.x">A general and simple method for obtaining R2 from generalized linear mixed‐effects models</a>. <em>Methods in Ecology and Evolution</em> <strong>4</strong>, 133–142.
</div>
<div id="ref-Nakagawa2017" class="csl-entry" role="listitem">
<strong>Nakagawa, S., Noble, D. W. A., Senior, A. M. and Lagisz, M.</strong> (2017a). <a href="https://doi.org/10.1186/s12915-017-0357-7">Meta-evaluation of meta-analysis: Ten appraisal questions for biologists</a>. <em>BMC Biology</em> 15–18, DOI 10.1186/s12915-017-0357-7.
</div>
<div id="ref-Nakagawa2017ab" class="csl-entry" role="listitem">
<strong>Nakagawa, S., Johnson, P. C. and Schielzeth, H.</strong> (2017b). <a href="https://doi.org/10.1098/rsif.2017.0213">The coefficient of determination r 2 and intra-class correlation coefficient from generalized linear mixed-effects models revisited and expanded</a>. <em>Journal of the Royal Society Interface</em> <strong>14</strong>, 20170213.
</div>
<div id="ref-Nakagawa2021c" class="csl-entry" role="listitem">
<strong>Nakagawa, S., Lagisz, M., O’Dea, R. E., Rutkowska, J., Yang, Y., Noble, D. W. A. and Senior, A. M.</strong> (2021). <a href="https://doi.org/10.32942/osf.io/epqa7">The orchard plot: Cultivating forest plots for use in ecology, evolution and beyond</a>. <em>Research Synthesis Methods</em> <strong>12</strong>, 4–12.
</div>
<div id="ref-Nakagawa2023" class="csl-entry" role="listitem">
<strong>Nakagawa, S., Lagisz, M., O’Dea, R. E., Rutkowska, J., Yang, Y., Noble, D. W. A. and Senior, A. M.</strong> (2023). <a href="https://doi.org/10.1111/2041-210X.14152"><span class="nocase">orchaRd</span> 2.0: An <span>R</span> package for visualising meta-analyses with orchard plots</a>. <em>Methods in Ecology and Evolution</em> <strong>14</strong>, 2003–2010.
</div>
<div id="ref-Noble2022" class="csl-entry" role="listitem">
<strong>Noble, D. W. A., Pottier, P., Lagisz, M., Burke, S., Drobniak, S. M., O’Dea, R. E. and Nakagawa, S.</strong> (2022). <a href="https://doi.org/10.1242/jeb.243225">Meta-analytic approaches and effect sizes to account for <span>“nuisance heterogeneity”</span> in comparative physiology</a>. <em>Journal of Experimental Biology</em> <strong>225</strong>, jeb243225.
</div>
<div id="ref-ODea2021" class="csl-entry" role="listitem">
<strong>O’Dea, R. E., Lagisz, M., Jennions, M. D., Koricheva, J., Noble, D. W. A., Parker, T. H., Gurevitch, J., Page, M. J., Stewart, G., Moher, D., et al.</strong> (2021). <a href="https://doi.org/10.1111/brv.12721">Preferred reporting items for systematic reviews and meta-analyses in ecology and evolutionary biology: A PRISMA extension</a>. <em>Biological Reviews</em> <strong>doi: 10.1111/brv.12721</strong>,.
</div>
<div id="ref-Pottier2021" class="csl-entry" role="listitem">
<strong>Pottier, P., Burke, S., Drobniak, S. M., Lagisz, M. and Nakagawa, S.</strong> (2021). <a href="https://doi.org/10.1111/1365-2435.13899">Sexual (in) equality? A meta‐analysis of sex differences in thermal acclimation capacity across ectotherms</a>. <em>Functional Ecology</em> <strong>35</strong>, 2663–2678, https://doi.org/10.1111/1365–2435.13899.
</div>
<div id="ref-Senior2016" class="csl-entry" role="listitem">
<strong>Senior, A. M., Grueber, C. E., Kamiya, T., Lagisz, M., O’dwyer, K., Santos, E. S. A. and Nakagawa, S.</strong> (2016). <a href="https://doi.org/10.1002/ecy.1591">Heterogeneity in ecological and evolutionary meta‐analyses: Its magnitude and implications</a>. <em>Ecology</em> <strong>97</strong>, 3293–3299.
</div>
<div id="ref-Yang2024pi" class="csl-entry" role="listitem">
<strong>Yang, Y., Noble, D. W. A., Senior, A. M., Lagisz, M. and Nakagawa, S.</strong> (2024). <a href="https://doi.org/10.1101/2024.09.10.612386">Interpreting prediction intervals and distributions for decoding biological generality in meta-analyses</a>. <em>bioRxiv</em>.
</div>
<div id="ref-Yang2025het" class="csl-entry" role="listitem">
<strong>Yang, Y., Noble, D. W. A., Spake, R., Senior, A. M., Lagisz, M. and Nakagawa, S.</strong> (2025). <a href="https://doi.org/10.1111/2041-210x.70155">A pluralistic framework for measuring, interpreting and decomposing heterogeneity in meta-analysis</a>. <em>Methods in Ecology and Evolution</em> <strong>16</strong>, 2710–2725.
</div>
</div>
<p><br></p>
</section>
<section id="session-information" class="level2">
<h2 class="anchored" data-anchor-id="session-information"><strong>Session Information</strong></h2>
<div class="cell">
<div class="cell-output-display">
<p><strong>R version 4.5.3 (2026-03-11)</strong></p>
<p><strong>Platform:</strong> aarch64-apple-darwin20</p>
<p><strong>attached base packages:</strong> <em>stats</em>, <em>graphics</em>, <em>grDevices</em>, <em>utils</em>, <em>datasets</em>, <em>methods</em> and <em>base</em></p>
<p><strong>other attached packages:</strong> <em>emmeans(v.2.0.3)</em>, <em>R.rsp(v.0.46.0)</em>, <em>patchwork(v.1.3.1)</em>, <em>devtools(v.2.4.5)</em>, <em>usethis(v.3.2.1)</em>, <em>magick(v.2.9.1)</em>, <em>equatags(v.0.2.1)</em>, <em>mathjaxr(v.2.0-0)</em>, <em>pander(v.0.6.6)</em>, <em>orchaRd(v.2.2.0)</em>, <em>lubridate(v.1.9.5)</em>, <em>forcats(v.1.0.1)</em>, <em>stringr(v.1.6.0)</em>, <em>dplyr(v.1.2.1)</em>, <em>purrr(v.1.2.2)</em>, <em>readr(v.2.2.0)</em>, <em>tidyr(v.1.3.2)</em>, <em>tibble(v.3.3.1)</em>, <em>ggplot2(v.4.0.3)</em>, <em>tidyverse(v.2.0.0)</em>, <em>flextable(v.0.9.9)</em>, <em>metafor(v.4.8-0)</em>, <em>numDeriv(v.2016.8-1.1)</em>, <em>metadat(v.1.4-0)</em> and <em>Matrix(v.1.7-4)</em></p>
<p><strong>loaded via a namespace (and not attached):</strong> <em>remotes(v.2.5.0)</em>, <em>sandwich(v.3.1-1)</em>, <em>rlang(v.1.2.0)</em>, <em>magrittr(v.2.0.5)</em>, <em>multcomp(v.1.4-28)</em>, <em>otel(v.0.2.0)</em>, <em>compiler(v.4.5.3)</em>, <em>systemfonts(v.1.3.2)</em>, <em>vctrs(v.0.7.3)</em>, <em>profvis(v.0.4.0)</em>, <em>pkgconfig(v.2.0.3)</em>, <em>fastmap(v.1.2.0)</em>, <em>ellipsis(v.0.3.3)</em>, <em>labeling(v.0.4.3)</em>, <em>promises(v.1.5.0)</em>, <em>rmarkdown(v.2.31)</em>, <em>sessioninfo(v.1.2.3)</em>, <em>tzdb(v.0.5.0)</em>, <em>ggbeeswarm(v.0.7.3)</em>, <em>ragg(v.1.5.2)</em>, <em>xfun(v.0.57)</em>, <em>cachem(v.1.1.0)</em>, <em>jsonlite(v.2.0.0)</em>, <em>later(v.1.4.8)</em>, <em>uuid(v.1.2-2)</em>, <em>R6(v.2.6.1)</em>, <em>stringi(v.1.8.7)</em>, <em>RColorBrewer(v.1.1-3)</em>, <em>pkgload(v.1.5.1)</em>, <em>estimability(v.1.5.1)</em>, <em>Rcpp(v.1.1.1-1.1)</em>, <em>knitr(v.1.51)</em>, <em>zoo(v.1.8-14)</em>, <em>pacman(v.0.5.1)</em>, <em>R.utils(v.2.13.0)</em>, <em>splines(v.4.5.3)</em>, <em>httpuv(v.1.6.16)</em>, <em>R.cache(v.0.17.0)</em>, <em>timechange(v.0.4.0)</em>, <em>tidyselect(v.1.2.1)</em>, <em>yaml(v.2.3.12)</em>, <em>codetools(v.0.2-20)</em>, <em>miniUI(v.0.1.2)</em>, <em>curl(v.7.1.0)</em>, <em>pkgbuild(v.1.4.8)</em>, <em>lattice(v.0.22-9)</em>, <em>shiny(v.1.13.0)</em>, <em>withr(v.3.0.2)</em>, <em>S7(v.0.2.2)</em>, <em>askpass(v.1.2.1)</em>, <em>coda(v.0.19-4.1)</em>, <em>evaluate(v.1.0.5)</em>, <em>survival(v.3.8-6)</em>, <em>urlchecker(v.1.0.1)</em>, <em>zip(v.2.3.3)</em>, <em>xml2(v.1.5.2)</em>, <em>pillar(v.1.11.1)</em>, <em>generics(v.0.1.4)</em>, <em>hms(v.1.1.4)</em>, <em>scales(v.1.4.0)</em>, <em>xtable(v.1.8-8)</em>, <em>glue(v.1.8.1)</em>, <em>gdtools(v.0.4.2)</em>, <em>tools(v.4.5.3)</em>, <em>data.table(v.1.18.2.1)</em>, <em>fs(v.2.1.0)</em>, <em>mvtnorm(v.1.3-7)</em>, <em>grid(v.4.5.3)</em>, <em>nlme(v.3.1-168)</em>, <em>beeswarm(v.0.4.0)</em>, <em>vipor(v.0.4.7)</em>, <em>latex2exp(v.0.9.8)</em>, <em>cli(v.3.6.6)</em>, <em>textshaping(v.1.0.5)</em>, <em>officer(v.0.6.10)</em>, <em>fontBitstreamVera(v.0.1.1)</em>, <em>V8(v.6.0.4)</em>, <em>katex(v.1.5.0)</em>, <em>gtable(v.0.3.6)</em>, <em>R.methodsS3(v.1.8.2)</em>, <em>digest(v.0.6.39)</em>, <em>fontquiver(v.0.2.1)</em>, <em>TH.data(v.1.1-3)</em>, <em>xslt(v.1.5.1)</em>, <em>htmlwidgets(v.1.6.4)</em>, <em>farver(v.2.1.2)</em>, <em>memoise(v.2.0.1)</em>, <em>htmltools(v.0.5.9)</em>, <em>R.oo(v.1.27.1)</em>, <em>lifecycle(v.1.0.5)</em>, <em>mime(v.0.13)</em>, <em>MASS(v.7.3-65)</em>, <em>fontLiberation(v.0.1.0)</em> and <em>openssl(v.2.4.0)</em></p>
</div>
</div>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./multi-level.html" class="pagination-link" aria-label="Multi-level Meta-analysis">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Multi-level Meta-analysis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./metaregression.html" class="pagination-link" aria-label="Multi-level Meta-regression">
        <span class="nav-page-text"><span class="chapter-title">Multi-level Meta-regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb17" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Heterogeneity in Meta-analysis</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup-packages-het</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(metafor, flextable, tidyverse, orchaRd, pander, mathjaxr, equatags, magick)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">digits=</span><span class="dv">3</span>)</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a><span class="fu">## **Introduction to Heterogeneity in Meta-analysis**</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>In physiology, ecology and evolution, we deal with many different populations, species, experimental designs etc. As such, we're not just interested in understanding 'what the overall effect' actually is (in fact, we may not even care in many cases), but we are mainly focused on attempting to understand what factors (e.g., biological, methodological) explain variation in effects <span class="co">[</span><span class="ot">@Noble2022; @Lag2010; @Gurevitch2018</span><span class="co">]</span>. Understanding and quantifying how much variability in effects exist, whether this is more than what we expect by chance, and what factors explain variation is a primary goal of meta-analysis. </span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>Meta-analytic mean estimates need to be interpreted in the context of how much variation in effects exist within and across studies. As such, reporting upon measures of variability, or what is referred to as 'heterogeneity' in meta-analysis, is essential to meta-analysis and should never be ignored (even though it often is unfortunately) <span class="co">[</span><span class="ot">@ODea2021; @NakagawaSantos2012; @Borenstein2019; @Nakagawa2017; @Gurevitch2018</span><span class="co">]</span>. </span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>There are a number of important metrics of heterogeneity that are commonly used and reported upon in the meta-analytic literature <span class="co">[</span><span class="ot">@NakagawaSantos2012; @Borenstein2019; @Nakagawa2017</span><span class="co">]</span>. We'll overview in this tutorial how to calculate, and interpret, many of the common types and what they mean with respect to interpreting the meta-analytic mean. Understanding the consistency of results across studies tells one a great deal about how likely an effect is going to be picked up in future studies and whether we can make broad general conclusions. </span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a><span class="fu">## **Measures of Heterogeneity**</span></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>The most commonly encountered measures of heterogeneity in comparative physiology, and indeed ecology and evolution more generally, are results of *Q* tests,  $I^2$ metrics (or  raw $\tau^2$ or variance estimates), and less commonly, prediction intervals. These measures of heterogeneity (even if just a few) should always be presented along side meta-analytic mean effect size estimates because they tell the reader a great deal about the 'consistency' of results (e.g., prediction intervals, total heterogeneity) or the relative contribution of different factors to effect size variation (i.e., different measures of $I^2$). We'll overview these different metrics and show how to calculate an interpret them in meta-analyses. </span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>For the purpose of this tutorial we'll assume the following multilevel meta-analytic model is fit as described in the <span class="co">[</span><span class="ot">multilevel model tutorial</span><span class="co">](multi-level.qmd)</span>. If you can't quite remember all the notation we recommend going back to review that page.  </span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>y_{i} &amp;= \mu + s_{j<span class="co">[</span><span class="ot">i</span><span class="co">]</span>} + spp_{k<span class="co">[</span><span class="ot">i</span><span class="co">]</span>} + e_{i} + m_{i} <span class="sc">\\</span></span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>m_{i} &amp;\sim N(0, v_{i}) <span class="sc">\\</span></span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a>s_{j} &amp;\sim N(0, \tau^2) <span class="sc">\\</span></span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>spp_{k} &amp;\sim N(0, \sigma_{k}^2) <span class="sc">\\</span></span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>e_{i} &amp;\sim N(0, \sigma_{e}^2)</span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a>We will return to the meta-analysis by @Pottier2021 that we already detailed in the <span class="co">[</span><span class="ot">multilevel meta-analysis tutorial</span><span class="co">](multi-level.qmd)</span>. We'll walk through the different types of heterogeneity statistics that we can calculate for the model. </span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-41"><a href="#cb17-41" aria-hidden="true" tabindex="-1"></a><span class="al">![](./figs/pottier.png)</span></span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a>We can re-load that data again and get it ready for analysis using the code below:</span>
<span id="cb17-44"><a href="#cb17-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-47"><a href="#cb17-47" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-48"><a href="#cb17-48" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: load-data</span></span>
<span id="cb17-49"><a href="#cb17-49" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb17-50"><a href="#cb17-50" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb17-51"><a href="#cb17-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-52"><a href="#cb17-52" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("pacman") ; uncomment this line if you haven't already installed 'pacman'</span></span>
<span id="cb17-53"><a href="#cb17-53" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(metafor, tidyverse, orchaRd, devtools, patchwork, R.rsp, emmeans, flextable)</span>
<span id="cb17-54"><a href="#cb17-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-55"><a href="#cb17-55" aria-hidden="true" tabindex="-1"></a>asr_dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://osf.io/qn2af/download"</span>)</span>
<span id="cb17-56"><a href="#cb17-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-57"><a href="#cb17-57" aria-hidden="true" tabindex="-1"></a><span class="co">#' @title arr</span></span>
<span id="cb17-58"><a href="#cb17-58" aria-hidden="true" tabindex="-1"></a><span class="co">#' @description Calculates the acclimation response ratio (ARR).  </span></span>
<span id="cb17-59"><a href="#cb17-59" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param t2_l  Lowest of the two treatment temperatures</span></span>
<span id="cb17-60"><a href="#cb17-60" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param t1_h  Highest of the two treatment temperatures</span></span>
<span id="cb17-61"><a href="#cb17-61" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param x1_h  Mean trait value at high temperature</span></span>
<span id="cb17-62"><a href="#cb17-62" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param x2_l  Mean trait value at low temperature</span></span>
<span id="cb17-63"><a href="#cb17-63" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param sd1_h Standard deviation of mean trait value at high temperature</span></span>
<span id="cb17-64"><a href="#cb17-64" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param sd2_l Standard deviation of mean trait value at low temperature</span></span>
<span id="cb17-65"><a href="#cb17-65" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param n1_h  Sample size at high temperature</span></span>
<span id="cb17-66"><a href="#cb17-66" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param n2_l  Sample size at low temperature</span></span>
<span id="cb17-67"><a href="#cb17-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-68"><a href="#cb17-68" aria-hidden="true" tabindex="-1"></a>arr <span class="ot">&lt;-</span> <span class="cf">function</span>(x1_h, x2_l, sd1_h, sd2_l, n1_h, n2_l, t1_h, t2_l){</span>
<span id="cb17-69"><a href="#cb17-69" aria-hidden="true" tabindex="-1"></a>        ARR <span class="ot">&lt;-</span> (x1_h <span class="sc">-</span> x2_l)<span class="sc">/</span>(t1_h <span class="sc">-</span> t2_l)</span>
<span id="cb17-70"><a href="#cb17-70" aria-hidden="true" tabindex="-1"></a>      V_ARR <span class="ot">&lt;-</span> ((<span class="dv">1</span><span class="sc">/</span>(t1_h <span class="sc">-</span> t2_l))<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span>(sd2_l<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n2_l <span class="sc">+</span> sd1_h<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n1_h))</span>
<span id="cb17-71"><a href="#cb17-71" aria-hidden="true" tabindex="-1"></a><span class="fu">return</span>(<span class="fu">data.frame</span>(ARR, V_ARR))</span>
<span id="cb17-72"><a href="#cb17-72" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-73"><a href="#cb17-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-74"><a href="#cb17-74" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the effect sizes</span></span>
<span id="cb17-75"><a href="#cb17-75" aria-hidden="true" tabindex="-1"></a>asr_dat<span class="ot">&lt;-</span>asr_dat <span class="sc">%&gt;%</span> </span>
<span id="cb17-76"><a href="#cb17-76" aria-hidden="true" tabindex="-1"></a>              <span class="fu">mutate</span>(<span class="at">ARR=</span> <span class="fu">arr</span>(<span class="at">x1_h =</span> mean_high, <span class="at">x2_l =</span> mean_low, <span class="at">t1_h =</span> acc_temp_high, <span class="at">t2_l =</span> acc_temp_low, </span>
<span id="cb17-77"><a href="#cb17-77" aria-hidden="true" tabindex="-1"></a>                              <span class="at">sd1_h =</span> sd_high, <span class="at">sd2_l =</span> sd_low, <span class="at">n1_h =</span> n_high_adj, <span class="at">n2_l =</span> n_low_adj)[,<span class="dv">1</span>], </span>
<span id="cb17-78"><a href="#cb17-78" aria-hidden="true" tabindex="-1"></a>                     <span class="at">V_ARR =</span> <span class="fu">arr</span>(<span class="at">x1_h =</span>  mean_high, <span class="at">x2_l =</span> mean_low, <span class="at">t1_h =</span> acc_temp_high, <span class="at">t2_l =</span> acc_temp_low, </span>
<span id="cb17-79"><a href="#cb17-79" aria-hidden="true" tabindex="-1"></a>                           <span class="at">sd1_h =</span> sd_high, <span class="at">sd2_l =</span> sd_low, <span class="at">n1_h =</span> n_high_adj, <span class="at">n2_l =</span> n_low_adj)[,<span class="dv">2</span>]) <span class="sc">%&gt;%</span> </span>
<span id="cb17-80"><a href="#cb17-80" aria-hidden="true" tabindex="-1"></a>                <span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">"female"</span>)</span>
<span id="cb17-81"><a href="#cb17-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-82"><a href="#cb17-82" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-fit the multilevel meta-analytic model</span></span>
<span id="cb17-83"><a href="#cb17-83" aria-hidden="true" tabindex="-1"></a>MLMA <span class="ot">&lt;-</span> metafor<span class="sc">::</span><span class="fu">rma.mv</span>(<span class="at">yi=</span> ARR<span class="sc">~</span> <span class="dv">1</span>, <span class="at">V =</span> V_ARR, </span>
<span id="cb17-84"><a href="#cb17-84" aria-hidden="true" tabindex="-1"></a>                   <span class="at">method=</span><span class="st">"REML"</span>,</span>
<span id="cb17-85"><a href="#cb17-85" aria-hidden="true" tabindex="-1"></a>                   <span class="at">random=</span><span class="fu">list</span>(<span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>species_ID,</span>
<span id="cb17-86"><a href="#cb17-86" aria-hidden="true" tabindex="-1"></a>                               <span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>study_ID,</span>
<span id="cb17-87"><a href="#cb17-87" aria-hidden="true" tabindex="-1"></a>                               <span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>es_ID), </span>
<span id="cb17-88"><a href="#cb17-88" aria-hidden="true" tabindex="-1"></a>                   <span class="at">dfs =</span> <span class="st">"contain"</span>,</span>
<span id="cb17-89"><a href="#cb17-89" aria-hidden="true" tabindex="-1"></a>                   <span class="at">test=</span><span class="st">"t"</span>,</span>
<span id="cb17-90"><a href="#cb17-90" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data=</span>asr_dat)</span>
<span id="cb17-91"><a href="#cb17-91" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-92"><a href="#cb17-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-93"><a href="#cb17-93" aria-hidden="true" tabindex="-1"></a>We'll now use this model to calculate various heterogeneity statistics in addition to the ones already calculated (which we will describe below). Before doing so, it helps to visualise the data and the model output together.</span>
<span id="cb17-94"><a href="#cb17-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-95"><a href="#cb17-95" aria-hidden="true" tabindex="-1"></a><span class="fu">### Visualising Heterogeneity with an Orchard Plot</span></span>
<span id="cb17-96"><a href="#cb17-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-97"><a href="#cb17-97" aria-hidden="true" tabindex="-1"></a>The <span class="in">`orchaRd`</span> package provides the <span class="in">`orchard_plot()`</span> function, which is a great tool for communicating meta-analytic results and heterogeneity at the same time <span class="co">[</span><span class="ot">@Nakagawa2021c; @Nakagawa2023</span><span class="co">]</span>. The plot shows:</span>
<span id="cb17-98"><a href="#cb17-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-99"><a href="#cb17-99" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>the **meta-analytic mean** as a point estimate (the filled circle in @fig-orchard);</span>
<span id="cb17-100"><a href="#cb17-100" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>a **thick bar** spanning the 95% confidence interval (uncertainty around the mean);</span>
<span id="cb17-101"><a href="#cb17-101" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>a **thin bar** spanning the 95% **prediction interval** (the expected range of a future effect size — the key to visualising heterogeneity);</span>
<span id="cb17-102"><a href="#cb17-102" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>individual effect sizes are plotted as points scaled by their precision ($1/\sqrt{v_i}$), so precise estimates appear larger.</span>
<span id="cb17-103"><a href="#cb17-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-106"><a href="#cb17-106" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-107"><a href="#cb17-107" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-orchard</span></span>
<span id="cb17-108"><a href="#cb17-108" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb17-109"><a href="#cb17-109" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: center</span></span>
<span id="cb17-110"><a href="#cb17-110" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Orchard plot of acclimation response ratio (ARR) estimates across ectotherm species. The filled circle is the meta-analytic mean, the thick bar is the 95% confidence interval, and the thin bar is the 95% prediction interval. Individual effect sizes are scaled by precision."</span></span>
<span id="cb17-111"><a href="#cb17-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-112"><a href="#cb17-112" aria-hidden="true" tabindex="-1"></a>orchaRd<span class="sc">::</span><span class="fu">orchard_plot</span>(MLMA, <span class="at">group =</span> <span class="st">"species_ID"</span>, <span class="at">xlab =</span> <span class="st">"Acclimation Response Ratio (ARR, °C / °C)"</span>)</span>
<span id="cb17-113"><a href="#cb17-113" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-114"><a href="#cb17-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-115"><a href="#cb17-115" aria-hidden="true" tabindex="-1"></a>The wide prediction interval in @fig-orchard immediately makes clear that there is substantial heterogeneity in ARR across species — the spread of effects is far greater than sampling error alone would produce. The numerical heterogeneity metrics below quantify this formally.</span>
<span id="cb17-116"><a href="#cb17-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-117"><a href="#cb17-117" aria-hidden="true" tabindex="-1"></a><span class="fu">### Proportion of Total Heterogeneity: $I_{total}^2$</span></span>
<span id="cb17-118"><a href="#cb17-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-119"><a href="#cb17-119" aria-hidden="true" tabindex="-1"></a>$I^2$ estimates are probably most commonly presented in the literature <span class="co">[</span><span class="ot">@Higgins2003; @Higgins2002; @Nakagawa2017; @Senior2016; @Borenstein2019</span><span class="co">]</span>. There are different forms of $I^2$ that can be calculated, but the one that describes the proportion of effect size variation after accounting for total sampling variation is $I_{total}^2$ <span class="co">[</span><span class="ot">@NakagawaSantos2012</span><span class="co">]</span>. Assuming we're using our multilevel model described above, it's calculated as follows:</span>
<span id="cb17-120"><a href="#cb17-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-121"><a href="#cb17-121" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-122"><a href="#cb17-122" aria-hidden="true" tabindex="-1"></a>I^2_{total} = \frac{\sigma^2_{study} + \sigma^2_{phylogeny} + \sigma^2_{species} + \sigma^2_{residual}}{\sigma^2_{study} + \sigma^2_{phylogeny} + \sigma^2_{species} + \sigma^2_{residual} +\sigma^2_{m}}</span>
<span id="cb17-123"><a href="#cb17-123" aria-hidden="true" tabindex="-1"></a>$$ {#eq-itot}</span>
<span id="cb17-124"><a href="#cb17-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-125"><a href="#cb17-125" aria-hidden="true" tabindex="-1"></a>where $\sigma^2_{total} = \sigma^2_{study} + \sigma^2_{phylogeny} + \sigma^2_{species} + \sigma^2_{residual} +\sigma^2_{m}$ is the total effect size variance and $\sigma^2_{m}$ is the 'typical' sampling error variance calculated as:</span>
<span id="cb17-126"><a href="#cb17-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-127"><a href="#cb17-127" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb17-128"><a href="#cb17-128" aria-hidden="true" tabindex="-1"></a>@eq-itot is the general form and may include a phylogenetic variance component ($\sigma^2_{phylogeny}$) when a phylogenetic correlation structure is added to the model. In the model fitted here, no phylogenetic term is included, so $\sigma^2_{phylogeny} = 0$ and the numerator reduces to $\sigma^2_{study} + \sigma^2_{species} + \sigma^2_{residual}$.</span>
<span id="cb17-129"><a href="#cb17-129" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb17-130"><a href="#cb17-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-131"><a href="#cb17-131" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-132"><a href="#cb17-132" aria-hidden="true" tabindex="-1"></a>\sigma_{m}^2 = \sum w_{i}\left( k-1\right) / \left<span class="co">[</span><span class="ot"> \left( \sum w_{i}\right)^2  + \sum w_{i}^2\right</span><span class="co">]</span></span>
<span id="cb17-133"><a href="#cb17-133" aria-hidden="true" tabindex="-1"></a>$$ {#eq-w}</span>
<span id="cb17-134"><a href="#cb17-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-135"><a href="#cb17-135" aria-hidden="true" tabindex="-1"></a>where *k* is the number of studies and the weights, $w_{i} = \frac{1}{v_{i}}$, can be calculated using the inverse of the sampling variance ($v_{i}$) for each effect size, *i*. Below, we'll make use of the <span class="in">`orchaRd`</span> R package <span class="co">[</span><span class="ot">@Nakagawa2021c; @Nakagawa2023</span><span class="co">]</span> to calculate various $I^2$ metrics. In fact, we can simply change what is in the numerator of @eq-itot to calculate a multitude of different $I^2$ metrics that can be useful in understanding the relative importance of factors most important in explaining effect size variation. We'll do this below:</span>
<span id="cb17-136"><a href="#cb17-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-139"><a href="#cb17-139" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-140"><a href="#cb17-140" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: i2</span></span>
<span id="cb17-141"><a href="#cb17-141" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb17-142"><a href="#cb17-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-143"><a href="#cb17-143" aria-hidden="true" tabindex="-1"></a><span class="co"># The orchaRd package has some convenient functions for calculating various I2 estimates including total. We'll load and install that package</span></span>
<span id="cb17-144"><a href="#cb17-144" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("pacman")</span></span>
<span id="cb17-145"><a href="#cb17-145" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(devtools, tidyverse, metafor, patchwork, R.rsp, emmeans, flextable)</span>
<span id="cb17-146"><a href="#cb17-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-147"><a href="#cb17-147" aria-hidden="true" tabindex="-1"></a><span class="co">#devtools::install_github("daniel1noble/orchaRd", force = TRUE, build_vignettes = TRUE)</span></span>
<span id="cb17-148"><a href="#cb17-148" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(orchaRd)</span>
<span id="cb17-149"><a href="#cb17-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-150"><a href="#cb17-150" aria-hidden="true" tabindex="-1"></a>orchaRd<span class="sc">::</span><span class="fu">i2_ml</span>(MLMA)</span>
<span id="cb17-151"><a href="#cb17-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-152"><a href="#cb17-152" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-153"><a href="#cb17-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-154"><a href="#cb17-154" aria-hidden="true" tabindex="-1"></a><span class="fu">#### **Interpreting $I^2$ Estimates**</span></span>
<span id="cb17-155"><a href="#cb17-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-156"><a href="#cb17-156" aria-hidden="true" tabindex="-1"></a>::: {.panel-tabset}</span>
<span id="cb17-157"><a href="#cb17-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-158"><a href="#cb17-158" aria-hidden="true" tabindex="-1"></a><span class="fu">## First Task!</span></span>
<span id="cb17-159"><a href="#cb17-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-160"><a href="#cb17-160" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;**Interpret the meaning of $I_{Total}^2$ from the multilevel meta-analytic model**</span></span>
<span id="cb17-161"><a href="#cb17-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-162"><a href="#cb17-162" aria-hidden="true" tabindex="-1"></a><span class="fu">## First Answer!</span></span>
<span id="cb17-163"><a href="#cb17-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-164"><a href="#cb17-164" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;Overall, we have highly heterogeneous effect size data because sampling variation only contributes to </span><span class="in">`r 100-orchaRd::i2_ml(MLMA)[1]`</span><span class="at">% of the total variation in effects.</span>  </span>
<span id="cb17-165"><a href="#cb17-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-166"><a href="#cb17-166" aria-hidden="true" tabindex="-1"></a><span class="fu">## Second Task!</span></span>
<span id="cb17-167"><a href="#cb17-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-168"><a href="#cb17-168" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;**Interpret the meaning of $I_{study}^2$ from the multilevel meta-analytic model**</span></span>
<span id="cb17-169"><a href="#cb17-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-170"><a href="#cb17-170" aria-hidden="true" tabindex="-1"></a><span class="fu">## Second Answer!</span></span>
<span id="cb17-171"><a href="#cb17-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-172"><a href="#cb17-172" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;From the multilevel meta-analytic model we find that </span><span class="in">`r orchaRd::i2_ml(MLMA)[3]`</span><span class="at">%  of the total variation in effect size estimates is the result of differences between studies.</span></span>
<span id="cb17-173"><a href="#cb17-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-174"><a href="#cb17-174" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb17-175"><a href="#cb17-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-176"><a href="#cb17-176" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb17-177"><a href="#cb17-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-178"><a href="#cb17-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-179"><a href="#cb17-179" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Bootstrapping $I^2$ Estimates</span></span>
<span id="cb17-180"><a href="#cb17-180" aria-hidden="true" tabindex="-1"></a>There are also times that we may want to estimate, and present, uncertainty about these heterogeneity estimates. We can do that by bootstrapping 1000 times:</span>
<span id="cb17-181"><a href="#cb17-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-184"><a href="#cb17-184" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-185"><a href="#cb17-185" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: i2boot</span></span>
<span id="cb17-186"><a href="#cb17-186" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb17-187"><a href="#cb17-187" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: true</span></span>
<span id="cb17-188"><a href="#cb17-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-189"><a href="#cb17-189" aria-hidden="true" tabindex="-1"></a><span class="co"># The orchaRd package has some convenient functions for calculating various I2 estimates including total. We'll load and install that package</span></span>
<span id="cb17-190"><a href="#cb17-190" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("pacman")</span></span>
<span id="cb17-191"><a href="#cb17-191" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(devtools, tidyverse, metafor, patchwork, R.rsp, emmeans, flextable)</span>
<span id="cb17-192"><a href="#cb17-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-193"><a href="#cb17-193" aria-hidden="true" tabindex="-1"></a><span class="co">#devtools::install_github("daniel1noble/orchaRd", force = TRUE, build_vignettes = TRUE)</span></span>
<span id="cb17-194"><a href="#cb17-194" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(orchaRd)</span>
<span id="cb17-195"><a href="#cb17-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-196"><a href="#cb17-196" aria-hidden="true" tabindex="-1"></a>orchaRd<span class="sc">::</span><span class="fu">i2_ml</span>(MLMA, <span class="at">boot =</span> <span class="dv">1000</span>)</span>
<span id="cb17-197"><a href="#cb17-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-198"><a href="#cb17-198" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-199"><a href="#cb17-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-200"><a href="#cb17-200" aria-hidden="true" tabindex="-1"></a>Here, we can now see that $I_{total}^2$ has a fairly narrow 95% confidence interval of ~ 0.97 to 0.99.</span>
<span id="cb17-201"><a href="#cb17-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-202"><a href="#cb17-202" aria-hidden="true" tabindex="-1"></a><span class="fu">### Beyond $I^2$: Mean-Standardised Heterogeneity ($CVH_2$ and $M_2$)</span></span>
<span id="cb17-203"><a href="#cb17-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-204"><a href="#cb17-204" aria-hidden="true" tabindex="-1"></a>$I^2$ is a *variance-partitioning* metric: it tells you what fraction of total variance is genuine heterogeneity, not sampling error. That is useful, but it says nothing about whether the heterogeneity is large or small *relative to the mean effect*. Consider two studies that both have $I^2_{total} = 0.90$. If one has a mean ARR of 0.001 °C/°C the absolute spread of effects is biologically negligible; if the other has a mean of 1 °C/°C the same 90% translates to enormous between-study variation. @Yang2025het propose two mean-standardised alternatives that capture this information:</span>
<span id="cb17-205"><a href="#cb17-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-206"><a href="#cb17-206" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-207"><a href="#cb17-207" aria-hidden="true" tabindex="-1"></a>CVH_2 = \frac{\sum \sigma^2}{\hat{\mu}^2}</span>
<span id="cb17-208"><a href="#cb17-208" aria-hidden="true" tabindex="-1"></a>$$ {#eq-cvh2}</span>
<span id="cb17-209"><a href="#cb17-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-210"><a href="#cb17-210" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-211"><a href="#cb17-211" aria-hidden="true" tabindex="-1"></a>M_2 = \frac{\sum \sigma^2}{\hat{\mu}^2 + \sum \sigma^2}</span>
<span id="cb17-212"><a href="#cb17-212" aria-hidden="true" tabindex="-1"></a>$$ {#eq-m2}</span>
<span id="cb17-213"><a href="#cb17-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-214"><a href="#cb17-214" aria-hidden="true" tabindex="-1"></a>where $\hat{\mu}$ is the meta-analytic mean and $\sum \sigma^2$ is the sum of all random-effect variance components (excluding sampling variance $\sigma^2_m$). $CVH_2$ (@eq-cvh2) is analogous to a squared coefficient of variation: values $&gt; 1$ indicate that heterogeneity variance exceeds the mean effect squared. $M_2$ (@eq-m2) is bounded $<span class="co">[</span><span class="ot">0, 1</span><span class="co">]</span>$ and can be read as the proportion of total 'signal' (mean$^2$ + variance) that is heterogeneity. @Yang2025het recommend reporting both $CVH_2$ and $M_2$ alongside $I^2$ for a more complete picture. These metrics are implemented in <span class="in">`orchaRd`</span>:</span>
<span id="cb17-215"><a href="#cb17-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-218"><a href="#cb17-218" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-219"><a href="#cb17-219" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: cvhm</span></span>
<span id="cb17-220"><a href="#cb17-220" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb17-221"><a href="#cb17-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-222"><a href="#cb17-222" aria-hidden="true" tabindex="-1"></a>orchaRd<span class="sc">::</span><span class="fu">cvh2_ml</span>(MLMA)   <span class="co"># Mean-standardised heterogeneity (variance scale)</span></span>
<span id="cb17-223"><a href="#cb17-223" aria-hidden="true" tabindex="-1"></a>orchaRd<span class="sc">::</span><span class="fu">m2_ml</span>(MLMA)     <span class="co"># Heterogeneity as fraction of total signal</span></span>
<span id="cb17-224"><a href="#cb17-224" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-225"><a href="#cb17-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-226"><a href="#cb17-226" aria-hidden="true" tabindex="-1"></a><span class="fu">#### **Interpreting $CVH_2$ and $M_2$**</span></span>
<span id="cb17-227"><a href="#cb17-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-228"><a href="#cb17-228" aria-hidden="true" tabindex="-1"></a>::: {.panel-tabset}</span>
<span id="cb17-229"><a href="#cb17-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-230"><a href="#cb17-230" aria-hidden="true" tabindex="-1"></a><span class="fu">## Task!</span></span>
<span id="cb17-231"><a href="#cb17-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-232"><a href="#cb17-232" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;**Given the values of $CVH_2$ and $M_2$ above, what do they tell you about ARR heterogeneity that $I^2_{total}$ does not?**</span></span>
<span id="cb17-233"><a href="#cb17-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-234"><a href="#cb17-234" aria-hidden="true" tabindex="-1"></a><span class="fu">## Answer!</span></span>
<span id="cb17-235"><a href="#cb17-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-236"><a href="#cb17-236" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;$I^2_{total}$ tells us that almost all of the variance in ARR estimates is real heterogeneity rather than sampling noise. But it does not tell us whether that heterogeneity is large or small on a biologically meaningful scale. $CVH_2$ answers that: a value much greater than 1 means the variance across studies is many times larger than the mean effect squared — i.e., the spread of true effects dwarfs the average effect. $M_2$ near 1 means variation dominates the signal; near 0 means the mean is large and stable relative to the scatter. Together these metrics clarify whether a high $I^2$ reflects *a lot of noise around a strong signal* or *a weak signal swamped by variation*.</span></span>
<span id="cb17-237"><a href="#cb17-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-238"><a href="#cb17-238" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb17-239"><a href="#cb17-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-240"><a href="#cb17-240" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb17-241"><a href="#cb17-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-242"><a href="#cb17-242" aria-hidden="true" tabindex="-1"></a><span class="fu">### Prediction Intervals</span></span>
<span id="cb17-243"><a href="#cb17-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-244"><a href="#cb17-244" aria-hidden="true" tabindex="-1"></a>Prediction intervals (PI) are probably the best and most intuitive way to report heterogeneity of meta-analytic results <span class="co">[</span><span class="ot">@Borenstein2019; @Noble2022; @Nakagawa2021c; @Nakagawa2023</span><span class="co">]</span>. Prediction intervals tell us how much we can expect a given effect size to vary across studies. More specifically, if we were to go out and conduct another study or experiment they tell us what the range of effect size estimates we are expected to observe 95% of the time from that new study <span class="co">[</span><span class="ot">@Borenstein2019; @Noble2022; @Nakagawa2021c</span><span class="co">]</span>.</span>
<span id="cb17-245"><a href="#cb17-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-246"><a href="#cb17-246" aria-hidden="true" tabindex="-1"></a>Prediction intervals can be calculated in a similar way to confidence intervals but instead of just using the standard error, like we do with confidence interval construction, we add in the extra random-effect variance estimates. For our model above, the **total** PI — spanning all sources of variance — is:</span>
<span id="cb17-247"><a href="#cb17-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-248"><a href="#cb17-248" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-249"><a href="#cb17-249" aria-hidden="true" tabindex="-1"></a>PI_{total} \sim  \bar{\mu} \pm 1.96 \sqrt{SE^2 + \sigma^2_{study} +  \sigma^2_{species} + \sigma^2_{residual}}</span>
<span id="cb17-250"><a href="#cb17-250" aria-hidden="true" tabindex="-1"></a>$$ {#eq-pi}</span>
<span id="cb17-251"><a href="#cb17-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-252"><a href="#cb17-252" aria-hidden="true" tabindex="-1"></a>However, @Yang2024pi highlight that the total PI conflates two distinct questions: (1) how variable are individual *effect size estimates* across all studies (which includes within-study residual variance, $\sigma^2_{residual}$), and (2) how variable are *study-level means* across different biological contexts (which excludes within-study residual variance). The latter — called the **study-level PI** — is often the more relevant question for biological generality, because it captures how much we expect the average result to shift if we replicated the study in a new species or population context:</span>
<span id="cb17-253"><a href="#cb17-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-254"><a href="#cb17-254" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-255"><a href="#cb17-255" aria-hidden="true" tabindex="-1"></a>PI_{study} \sim  \bar{\mu} \pm 1.96 \sqrt{SE^2 + \sigma^2_{study} +  \sigma^2_{species}}</span>
<span id="cb17-256"><a href="#cb17-256" aria-hidden="true" tabindex="-1"></a>$$ {#eq-pi-study}</span>
<span id="cb17-257"><a href="#cb17-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-258"><a href="#cb17-258" aria-hidden="true" tabindex="-1"></a>@Yang2024pi found that across 512 ecological and evolutionary meta-analyses, most of the wide total PI came from within-study (residual) variance, and that study-level generality was far more common than the total PI implied.</span>
<span id="cb17-259"><a href="#cb17-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-260"><a href="#cb17-260" aria-hidden="true" tabindex="-1"></a>We can compute both types easily:</span>
<span id="cb17-261"><a href="#cb17-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-264"><a href="#cb17-264" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-265"><a href="#cb17-265" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: pis</span></span>
<span id="cb17-266"><a href="#cb17-266" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb17-267"><a href="#cb17-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-268"><a href="#cb17-268" aria-hidden="true" tabindex="-1"></a><span class="co"># Total PI — all variance components (predict() uses all sigma2 by default)</span></span>
<span id="cb17-269"><a href="#cb17-269" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(MLMA)</span>
<span id="cb17-270"><a href="#cb17-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-271"><a href="#cb17-271" aria-hidden="true" tabindex="-1"></a><span class="co"># Study-level PI — between-study variance only (species_ID + study_ID, excluding es_ID)</span></span>
<span id="cb17-272"><a href="#cb17-272" aria-hidden="true" tabindex="-1"></a><span class="co"># sigma2 order matches the random= list: [species_ID, study_ID, es_ID]</span></span>
<span id="cb17-273"><a href="#cb17-273" aria-hidden="true" tabindex="-1"></a>vc <span class="ot">&lt;-</span> MLMA<span class="sc">$</span>sigma2</span>
<span id="cb17-274"><a href="#cb17-274" aria-hidden="true" tabindex="-1"></a>pi_study_se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(vc[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]) <span class="sc">+</span> MLMA<span class="sc">$</span>se<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb17-275"><a href="#cb17-275" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Study-level 95% PI: ["</span>,</span>
<span id="cb17-276"><a href="#cb17-276" aria-hidden="true" tabindex="-1"></a>    <span class="fu">round</span>(MLMA<span class="sc">$</span>b <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> pi_study_se, <span class="dv">3</span>), <span class="st">","</span>,</span>
<span id="cb17-277"><a href="#cb17-277" aria-hidden="true" tabindex="-1"></a>    <span class="fu">round</span>(MLMA<span class="sc">$</span>b <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> pi_study_se, <span class="dv">3</span>), <span class="st">"]</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb17-278"><a href="#cb17-278" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-279"><a href="#cb17-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-280"><a href="#cb17-280" aria-hidden="true" tabindex="-1"></a><span class="fu">#### **Interpreting Prediction Intervals**</span></span>
<span id="cb17-281"><a href="#cb17-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-282"><a href="#cb17-282" aria-hidden="true" tabindex="-1"></a>::: {.panel-tabset}</span>
<span id="cb17-283"><a href="#cb17-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-284"><a href="#cb17-284" aria-hidden="true" tabindex="-1"></a><span class="fu">## Task!</span></span>
<span id="cb17-285"><a href="#cb17-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-286"><a href="#cb17-286" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;**The meta-analytic mean ARR is `r round(predict(MLMA)[[1]], 3)`. Compare the total PI to the study-level PI. What does each tell you, and why might one be more useful for assessing biological generality?**</span></span>
<span id="cb17-287"><a href="#cb17-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-288"><a href="#cb17-288" aria-hidden="true" tabindex="-1"></a><span class="fu">## Answer!</span></span>
<span id="cb17-289"><a href="#cb17-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-290"><a href="#cb17-290" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;The total 95% PI is wide — from </span><span class="in">`r round(predict(MLMA)[[5]], 3)`</span><span class="at"> to </span><span class="in">`r round(predict(MLMA)[[6]], 3)`</span><span class="at"> — suggesting a lot of inconsistency across individual effect size estimates. But much of that width comes from within-study residual variance (variation among effect sizes *within* a single study). The study-level PI, which retains only between-study variance (species and study components), is narrower and tells us how much the *average result* is expected to shift if we repeated the study in a new biological context. For biological generality, the study-level PI is the more relevant question: if most replications in new species or populations land near the mean, the phenomenon generalises well even if individual effect sizes are noisy.</span></span>
<span id="cb17-291"><a href="#cb17-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-292"><a href="#cb17-292" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb17-293"><a href="#cb17-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-294"><a href="#cb17-294" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb17-295"><a href="#cb17-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-296"><a href="#cb17-296" aria-hidden="true" tabindex="-1"></a><span class="fu">### *Q*-tests: Inferential Tests to Determine Excess Heterogeneity </span></span>
<span id="cb17-297"><a href="#cb17-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-298"><a href="#cb17-298" aria-hidden="true" tabindex="-1"></a>So far we've talked about important heterogeneity statistics that describe, and quantify, the proportion of variability ($I^2$) or the expected range of plausible effect size values which incorporate all the variance estimates (PI). But, how do we know that the heterogeneity in the data is greater than what we would expect by chance? It seems obvious that, if the $I_{total}^2$ is really high (i.e., &gt;85%) there's a lot of variability in effects within and across studies. While these statistics are probably sufficient, *Q* tests can also be useful to more formally be able to make an inferential statement about whether heterogeneity is significantly greater than chance. </span>
<span id="cb17-299"><a href="#cb17-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-300"><a href="#cb17-300" aria-hidden="true" tabindex="-1"></a>We have already encountered how to calculate the *Q*-statistic when discussing [fixed and random effects](fixed-vs-random.qmd) models. We can use the *Q* statistic now to compare this against a $\chi^2$-distribution to calculate a p-value. [Wolfgang's documentation](https://wviechtb.github.io/metafor/reference/rma.mv.html) (`?rma.mv`) describes what the *Q*-test means:</span>
<span id="cb17-301"><a href="#cb17-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-302"><a href="#cb17-302" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Cochran's 𝑄-test, which tests whether the variability in the observed effect sizes or outcomes is larger than one would expect based on sampling variability (and the given covariances among the sampling errors) alone. A significant test suggests that the true effects/outcomes are heterogeneous. </span></span>
<span id="cb17-303"><a href="#cb17-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-304"><a href="#cb17-304" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span> </span>
<span id="cb17-305"><a href="#cb17-305" aria-hidden="true" tabindex="-1"></a>We don't need to do anything special to get this test. In fact, this is automatically done by <span class="in">`metafor`</span>:</span>
<span id="cb17-306"><a href="#cb17-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-309"><a href="#cb17-309" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-310"><a href="#cb17-310" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: q</span></span>
<span id="cb17-311"><a href="#cb17-311" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb17-312"><a href="#cb17-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-313"><a href="#cb17-313" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(MLMA)</span>
<span id="cb17-314"><a href="#cb17-314" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-315"><a href="#cb17-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-316"><a href="#cb17-316" aria-hidden="true" tabindex="-1"></a><span class="fu">#### **Describing the *Q*-test**</span></span>
<span id="cb17-317"><a href="#cb17-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-318"><a href="#cb17-318" aria-hidden="true" tabindex="-1"></a>::: {.panel-tabset}</span>
<span id="cb17-319"><a href="#cb17-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-320"><a href="#cb17-320" aria-hidden="true" tabindex="-1"></a><span class="fu">## Task!</span></span>
<span id="cb17-321"><a href="#cb17-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-322"><a href="#cb17-322" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;**How would you describe in a paper the *Q*-test from the `metafor` model above?**</span></span>
<span id="cb17-323"><a href="#cb17-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-324"><a href="#cb17-324" aria-hidden="true" tabindex="-1"></a><span class="fu">## Answer!</span></span>
<span id="cb17-325"><a href="#cb17-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-326"><a href="#cb17-326" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;Of course, there are a multitude of ways that we could describe this test in words, but one way to describe it in your results section might be as follows:</span></span>
<span id="cb17-327"><a href="#cb17-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-328"><a href="#cb17-328" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb17-329"><a href="#cb17-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-330"><a href="#cb17-330" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;The overall mean ARR across ectotherms was </span><span class="in">`r MLMA$b`</span><span class="at"> and differed significantly from zero (95% CI: </span><span class="in">`r MLMA$ci.lb`</span><span class="at"> to </span><span class="in">`r MLMA$ci.ub`</span><span class="at">, df = </span><span class="in">`r MLMA$ddf`</span><span class="at">, t = </span><span class="in">`r MLMA$b / MLMA$se`</span><span class="at">, p &lt; 0.001). However, there was significant residual heterogeneity (*Q* = </span><span class="in">`r MLMA$QE`</span><span class="at">, df = </span><span class="in">`r dim(MLMA$data)[1]-1`</span><span class="at">, p &lt; 0.001) with estimates expected to range from </span><span class="in">`r predict(MLMA)[[5]]`</span><span class="at"> to </span><span class="in">`r predict(MLMA)[[6]]`</span><span class="at"> (95% Prediction Interval) ($I_{total}^2$ = </span><span class="in">`r orchaRd::i2_ml(MLMA)[1]`</span><span class="at">).</span></span>
<span id="cb17-331"><a href="#cb17-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-332"><a href="#cb17-332" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb17-333"><a href="#cb17-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-334"><a href="#cb17-334" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb17-335"><a href="#cb17-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-336"><a href="#cb17-336" aria-hidden="true" tabindex="-1"></a><span class="fu">### Proportion of Variation Explained by the Model: $R^2_{marginal}$ and $R^2_{conditional}$</span></span>
<span id="cb17-337"><a href="#cb17-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-338"><a href="#cb17-338" aria-hidden="true" tabindex="-1"></a>You will probably have noticed that $I^2$ looks awfully familiar. It looks a lot like the way we might calculate $R^2$ described by @NakagawaSchielzeth2013. Well, you would be correct! Often we also want to quantify how much variation is explained by our moderators and random effects in our multilevel meta-regression model <span class="co">[</span><span class="ot">@Nakagawa2017ab; @NakagawaSchielzeth2013</span><span class="co">]</span>. This is done using $R^2$. We can calculate different $R^2$ values depending on whether we ignore or include random effects in the numerator. If only the variation explained by moderators is included in the numerator than we call this $R_{marginal}^2$, which is defined as:</span>
<span id="cb17-339"><a href="#cb17-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-340"><a href="#cb17-340" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-341"><a href="#cb17-341" aria-hidden="true" tabindex="-1"></a>R^2_{marginal} = \frac{\sigma^2_{fixed}}{\sigma^2_{fixed} + \sigma^2_{study} + \sigma^2_{phylogeny} + \sigma^2_{species} + \sigma^2_{residual}}</span>
<span id="cb17-342"><a href="#cb17-342" aria-hidden="true" tabindex="-1"></a>$$ {#eq-r2}</span>
<span id="cb17-343"><a href="#cb17-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-344"><a href="#cb17-344" aria-hidden="true" tabindex="-1"></a>Note that this formula does not include $\sigma^2_{m}$ as sampling error variance is assumed to be known in meta-analysis. We won't go into the details on how to calculate and interpret these because we'll cover this in a later tutorial on <span class="co">[</span><span class="ot">publication bias</span><span class="co">](pub-bias1.qmd)</span>. Suffice it to say that this is a useful statistic for describing how much variation your moderators or model explain.</span>
<span id="cb17-345"><a href="#cb17-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-346"><a href="#cb17-346" aria-hidden="true" tabindex="-1"></a><span class="fu">## **Conclusion**</span></span>
<span id="cb17-347"><a href="#cb17-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-348"><a href="#cb17-348" aria-hidden="true" tabindex="-1"></a>Hopefully it's clear from this tutorial why explicitly estimating and reporting upon heterogeneity is so critically important in meta-analysis. Of course, some of these measures are only possible if we know the total sampling variance, which is not possible if one doesn't use a weighted meta-analytic model.</span>
<span id="cb17-349"><a href="#cb17-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-350"><a href="#cb17-350" aria-hidden="true" tabindex="-1"></a>No single metric tells the whole story. @Yang2025het recommend a **pluralistic approach** to reporting heterogeneity:</span>
<span id="cb17-351"><a href="#cb17-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-352"><a href="#cb17-352" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**$I^2_{total}$** — tells you what fraction of variance is real signal (not sampling noise);</span>
<span id="cb17-353"><a href="#cb17-353" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**$CVH_2$ and $M_2$** — tell you how large that heterogeneity is relative to the mean effect, answering the question "does the average matter if effects are so variable?";</span>
<span id="cb17-354"><a href="#cb17-354" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Prediction intervals** — give the most intuitive summary of heterogeneity as the expected range of a new result. Reporting both the *total* PI and the *study-level* PI <span class="co">[</span><span class="ot">@Yang2024pi</span><span class="co">]</span> helps distinguish noise within studies from genuine variation across biological contexts;</span>
<span id="cb17-355"><a href="#cb17-355" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**An orchard plot** — visualises all of the above at once and should accompany any numerical heterogeneity summary <span class="co">[</span><span class="ot">@Nakagawa2021c; @Nakagawa2023</span><span class="co">]</span>.</span>
<span id="cb17-356"><a href="#cb17-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-357"><a href="#cb17-357" aria-hidden="true" tabindex="-1"></a>Together these metrics give a far richer picture of heterogeneity than $I^2$ alone.</span>
<span id="cb17-358"><a href="#cb17-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-359"><a href="#cb17-359" aria-hidden="true" tabindex="-1"></a><span class="fu">## **References**</span></span>
<span id="cb17-360"><a href="#cb17-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-361"><a href="#cb17-361" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">div</span><span class="ot"> id</span><span class="op">=</span><span class="st">"refs"</span><span class="dt">&gt;&lt;/</span><span class="kw">div</span><span class="dt">&gt;</span></span>
<span id="cb17-362"><a href="#cb17-362" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span> </span>
<span id="cb17-363"><a href="#cb17-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-364"><a href="#cb17-364" aria-hidden="true" tabindex="-1"></a><span class="fu">## **Session Information**</span></span>
<span id="cb17-365"><a href="#cb17-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-368"><a href="#cb17-368" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-369"><a href="#cb17-369" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: sessioninfo-het</span></span>
<span id="cb17-370"><a href="#cb17-370" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb17-371"><a href="#cb17-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-372"><a href="#cb17-372" aria-hidden="true" tabindex="-1"></a><span class="fu">pander</span>(<span class="fu">sessionInfo</span>(), <span class="at">locale =</span> <span class="cn">FALSE</span>)</span>
<span id="cb17-373"><a href="#cb17-373" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
</code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>