<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Multi-level Meta-analysis – Meta-Analysis Workshop</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./complex-nonind.html" rel="next">
<link href="./metaregression.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9b98f18118eee809be1c051eb5cc78e4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./multi-level.html"><span class="chapter-title">Multi-level Meta-analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Meta-Analysis Workshop</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/noble-lab/meta-analysis_workshop" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction-to-meta.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introduction to Meta-analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./effect-size.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Calculating and interpreting effect sizes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./effect-assume.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Effect size assumptions and checking their suitability</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fixed-vs-random.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Fixed versus Random Effects Meta-analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./het.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Heterogeneity in Meta-analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nuis-het.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Nuisance heterogeneity</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./metaregression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Multi-level Meta-regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multi-level.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Multi-level Meta-analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./complex-nonind.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Complex Non-independence in Meta-analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./phylo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Phylogenetic Meta-analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pub-bias1.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Publication Bias in Meta-analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pub-bias2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Publication Bias: Analytical Approaches</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction-to-multi-level-meta-analysis" id="toc-introduction-to-multi-level-meta-analysis" class="nav-link active" data-scroll-target="#introduction-to-multi-level-meta-analysis"><strong>Introduction to Multi-level Meta-analysis</strong></a></li>
  <li><a href="#simple-multilevel-meta-analytic-model" id="toc-simple-multilevel-meta-analytic-model" class="nav-link" data-scroll-target="#simple-multilevel-meta-analytic-model"><strong>Simple Multilevel Meta-analytic Model</strong></a></li>
  <li><a href="#building-more-complex-multilevel-meta-analytic-models" id="toc-building-more-complex-multilevel-meta-analytic-models" class="nav-link" data-scroll-target="#building-more-complex-multilevel-meta-analytic-models"><strong>Building more Complex Multilevel Meta-analytic Models</strong></a></li>
  <li><a href="#fitting-a-multi-level-meta-analytic-model" id="toc-fitting-a-multi-level-meta-analytic-model" class="nav-link" data-scroll-target="#fitting-a-multi-level-meta-analytic-model"><strong>Fitting a Multi-level Meta-analytic Model</strong></a>
  <ul class="collapse">
  <li><a href="#download-data-and-functions-for-arr" id="toc-download-data-and-functions-for-arr" class="nav-link" data-scroll-target="#download-data-and-functions-for-arr">Download Data and Functions for <span class="math inline">\(ARR\)</span></a></li>
  <li><a href="#calculating-arr-and-its-sampling-variance" id="toc-calculating-arr-and-its-sampling-variance" class="nav-link" data-scroll-target="#calculating-arr-and-its-sampling-variance">Calculating <span class="math inline">\(ARR\)</span> and It’s Sampling Variance</a></li>
  <li><a href="#fitting-a-multilevel-meta-analytic-model-in-metafor" id="toc-fitting-a-multilevel-meta-analytic-model-in-metafor" class="nav-link" data-scroll-target="#fitting-a-multilevel-meta-analytic-model-in-metafor">Fitting a Multilevel Meta-analytic Model in <code>metafor</code></a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><strong>References</strong></a></li>
  <li><a href="#session-information" id="toc-session-information" class="nav-link" data-scroll-target="#session-information"><strong>Session Information</strong></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-title">Multi-level Meta-analysis</span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction-to-multi-level-meta-analysis" class="level2">
<h2 class="anchored" data-anchor-id="introduction-to-multi-level-meta-analysis"><strong>Introduction to Multi-level Meta-analysis</strong></h2>
<p>Ecological and evolutionary meta-analysis more often than not need much more sophisticated multilevel meta-analytic models <span class="citation" data-cites="NakagawaSantos2012 Hadfield2010 Noble2017">(<a href="#ref-Hadfield2010" role="doc-biblioref">Hadfield, 2010</a>; <a href="#ref-NakagawaSantos2012" role="doc-biblioref">Nakagawa and Santos, 2012</a>; <a href="#ref-Noble2017" role="doc-biblioref">Noble et al., 2017</a>)</span> compared with <a href="https://daniel1noble.github.io/meta-workshop/fixed-vs-random">random effect models</a> to analyse data. Biological data from field and lab-based experiments are highly structured – many studies could be done on the same species or they could be done by the same lab group or student sharing similar methodology <span class="citation" data-cites="Noble2017 NakagawaSantos2012">(<a href="#ref-NakagawaSantos2012" role="doc-biblioref">Nakagawa and Santos, 2012</a>; <a href="#ref-Noble2017" role="doc-biblioref">Noble et al., 2017</a>)</span>. In addition, we might have many effect size estimates from a single study because many traits are measured, or many treatments are applied <span class="citation" data-cites="Noble2017">(<a href="#ref-Noble2017" role="doc-biblioref">Noble et al., 2017</a>)</span>. This adds complexity to the data set and also results in special types of non-independence that are somewhat unique to meta-analysis – especially when using contrast-based effect sizes like Hedges’ g, log response ratios, log odds ratios etc <span class="citation" data-cites="Noble2017">(<a href="#ref-Noble2017" role="doc-biblioref">Noble et al., 2017</a>)</span>.</p>
<p>In the past, complex non-independence was often dealt with by: <strong>1)</strong> conducting separate meta-analyses on subsets of non-independent data sets, usually using random effect models; <strong>2)</strong> taking one or only a subset of effect size estimates from a single study to reduce non-independence; and/or <strong>3)</strong> averaging effect size estimates from a single study and modelling the average <span class="citation" data-cites="NakagawaSantos2012">(<a href="#ref-NakagawaSantos2012" role="doc-biblioref">Nakagawa and Santos, 2012</a>)</span>. <strong>These approaches can be problematic because disposing of useful effect size data will result in a loss of statistical power or even inflated Type I error rates if average effect size estimates were not calculated accounting for non-independence <span class="citation" data-cites="Nakagawa2021">(<a href="#ref-Nakagawa2021" role="doc-biblioref">Nakagawa et al., 2022</a>)</span></strong>. Furthermore, removing effect size estimates from an analysis prevents estimation of biological and methodologically relevant information that can help shape the field <span class="citation" data-cites="NakagawaSantos2012 Nakagawa2021">(<a href="#ref-NakagawaSantos2012" role="doc-biblioref">Nakagawa and Santos, 2012</a>; <a href="#ref-Nakagawa2021" role="doc-biblioref">Nakagawa et al., 2022</a>)</span>. While the above approaches could still be useful at times, where possible, we recommend you model all available data <span class="citation" data-cites="Nakagawa2021 Noble2017 NakagawaSantos2012">(<a href="#ref-NakagawaSantos2012" role="doc-biblioref">Nakagawa and Santos, 2012</a>; <a href="#ref-Nakagawa2021" role="doc-biblioref">Nakagawa et al., 2022</a>; <a href="#ref-Noble2017" role="doc-biblioref">Noble et al., 2017</a>)</span>.</p>
<p>In the next series of tutorials we’ll overview multilevel meta-analytic models and discuss common forms of non-independence and how to deal with these challenges. Here, we’ll first focus on simple multilevel meta-analysis models and how to interpret these. We’ll then work our way up to including more complex forms of non-independence, such as phylogenetic meta-analysis and accounting for shared control. Technically, all these sources could be built into a single model but will require a substantial amount of data. Sometimes it will not be possible to deal with all sources of non-independence, in which case it’s important to conduct sensitivity analyses to understand how your conclusions and inferences are affected by the analytic decisions made <span class="citation" data-cites="Noble2017">(<a href="#ref-Noble2017" role="doc-biblioref">Noble et al., 2017</a>)</span>. <strong>Strong justification for your choices is always essential</strong>.</p>
</section>
<section id="simple-multilevel-meta-analytic-model" class="level2">
<h2 class="anchored" data-anchor-id="simple-multilevel-meta-analytic-model"><strong>Simple Multilevel Meta-analytic Model</strong></h2>
<p><a href="https://daniel1noble.github.io/meta-workshop/fixed-vs-random">Recall</a> that a random effects model is defined as follows:</p>
<p><span class="math display">\[
y_{i} = \mu + s_{i} + m_{i} \\
m_{i} \sim N(0, v_{i}) \\
s_{i} \sim N(0, \tau^2)
\]</span> In this model, <span class="math inline">\(y_{i}\)</span> is the <em>i</em>th effect size estimate and <span class="math inline">\(m_{i}\)</span> is the sampling error (deviation from <span class="math inline">\(\mu\)</span>) for effect size <em>i</em>. Given that we have a single effect size estimate from each study we can include <span class="math inline">\(s_{i}\)</span>, which is the study specific deviation, and this gives us an ability to estimate a “residual” variance from this model. That’s because after we remove the known sampling variance there is likely to be “extra” variability among effect sizes at the effect/study level (in this case these are confounded because we have one effect / study). We can estimate that explicitly which is what we are doing here. <strong>The challenge with having a single effect estimate per study is that the within and between study variances are confounded</strong>. In other words, we cannot estimate both.</p>
<p>More commonly, we can extract many (sometimes a lot) effect size estimates from a single study. In such case, we no longer have a single effect size estimate from a given study but a whole bunch of effects from a single study. These could be effects from different experimental treatments, at different time points or on different traits. These effects are not independent of each other and there is likely a substantial amount of within study variation in addition to the across study variation <span class="citation" data-cites="NakagawaSantos2012">(<a href="#ref-NakagawaSantos2012" role="doc-biblioref">Nakagawa and Santos, 2012</a>)</span>. We can now estimate these two sources of variability explicitly turning our model into what is the simplest form of a multilevel meta-analytic model:</p>
<p><span class="math display">\[
y_{i,j} = \mu + s_{j} + e_{i,j} + m_{i,j} \\
m_{i,j} \sim N(0, v_{i,j}) \\
s_{j} \sim N(0, \tau^2) \\
e_{i,j} \sim N(0, \sigma_{e}^2)
\]</span></p>
<p>You’ll notice that the notation changes slightly – <span class="math inline">\(y_{i,j}\)</span> is now the <em>i</em> effect size from study <em>j</em> and <span class="math inline">\(m_{i,j}\)</span> is effect size <em>i</em>’s known sampling variance from study <em>j</em>. <span class="math inline">\(s_{j}\)</span> is now the study specific effect, <em>j</em>, applied to the <em>i</em>th effect size, where <em>j</em> = 1,…,<span class="math inline">\(N_{studies}\)</span>. We have also now added a random effect (<span class="math inline">\(e_{i,j}\)</span>) to the model. <strong><span class="math inline">\(e_{i,j}\)</span> is the effect-size-specific (within study) effect. This is often referred to as a ‘residual’ effect <span class="citation" data-cites="NakagawaSantos2012">(<a href="#ref-NakagawaSantos2012" role="doc-biblioref">Nakagawa and Santos, 2012</a>)</span> and is used to estimate a residual variance</strong>.</p>
</section>
<section id="building-more-complex-multilevel-meta-analytic-models" class="level2">
<h2 class="anchored" data-anchor-id="building-more-complex-multilevel-meta-analytic-models"><strong>Building more Complex Multilevel Meta-analytic Models</strong></h2>
<p>In reality, we may also have lots of studies on a specific set of species. For example, common or economically important species, like Salmon, Trout or lab model organisms like Zebrafish might be over-represented in the data set. This adds an additional level of structure to our data. We can account for species in this model by adding another random effect that captures the similarities between effect size estimates from the same species. As such, we can expand our multilevel model as follows:</p>
<p><span class="math display">\[
y_{i,j,k} = \mu + s_{j} + spp_{k} + e_{i,j,k} + m_{i,j,k} \\
m_{i,j,k} \sim N(0, v_{i,j}) \\
s_{j} \sim N(0, \tau^2) \\
spp_{k} \sim N(0, \sigma_{k}^2) \\
e_{i,j,k} \sim N(0, \sigma_{e}^2)
\]</span></p>
<p>Here, <span class="math inline">\(y_{i,j, k}\)</span> is now the <em>i</em>th effect size from study <em>j</em> and species <em>k</em>. <span class="math inline">\(m_{i,j, k}\)</span> is effect size <em>i</em>’s known sampling variance from study <em>j</em> and species <em>k</em>. <span class="math inline">\(e_{i,j, k}\)</span> is the effect-size-specific (within study) applied to each effect <em>i</em> from study <em>j</em> and species <em>k</em>. <span class="math inline">\(s_{j}\)</span> is still the study specific effect, <em>j</em>, applied to the <em>i</em>th effect size, where <em>j</em> = 1,…,<span class="math inline">\(N_{studies}\)</span>, but now <span class="math inline">\(spp_{k}\)</span> is the species specific effect, <em>k</em>, applied to the <em>i</em>th effect size, where <em>k</em> = 1,…,<span class="math inline">\(N_{species}\)</span>.</p>
<p>As you can imagine, the notation can get quite complicated the more levels you add. As such, a simplification of the above model notation that you might read <span class="citation" data-cites="NakagawaSantos2012 Noble2017">(e.g., <a href="#ref-NakagawaSantos2012" role="doc-biblioref">Nakagawa and Santos, 2012</a>; <a href="#ref-Noble2017" role="doc-biblioref">Noble et al., 2017</a>)</span> is as follows:</p>
<p><span class="math display">\[
y_{i} = \mu + s_{j[i]} + spp_{k[i]} + e_{i} + m_{i} \\
m_{i} \sim N(0, v_{i}) \\
s_{j} \sim N(0, \tau^2) \\
spp_{k} \sim N(0, \sigma_{k}^2) \\
e_{i} \sim N(0, \sigma_{e}^2)
\]</span></p>
</section>
<section id="fitting-a-multi-level-meta-analytic-model" class="level2">
<h2 class="anchored" data-anchor-id="fitting-a-multi-level-meta-analytic-model"><strong>Fitting a Multi-level Meta-analytic Model</strong></h2>
<p><img src="./figs/pottier.png" class="img-fluid"></p>
<p>To demonstrate how to fit a multilevel meta-analytic model similar to the one discussed above we’ll turn to a <a href="https://daniel1noble.github.io/meta-workshop/nuis-het">familiar example</a> by <span class="citation" data-cites="Pottier2021">Pottier et al. (<a href="#ref-Pottier2021" role="doc-biblioref">2021</a>)</span>, who used the acclimation response ratio (ARR) to analyse thermal acclimation responses on <span class="math inline">\(CT_{max}\)</span> and how this differs between the sexes. We’ll keep it simple for the moment and focus exclusively on a single sex.</p>
<section id="download-data-and-functions-for-arr" class="level3">
<h3 class="anchored" data-anchor-id="download-data-and-functions-for-arr">Download Data and Functions for <span class="math inline">\(ARR\)</span></h3>
<p>We’ll download the raw data from the paper again. We’ll also need to load the <code>metafor</code> package to fit our models and the tidyverse package for processing the data.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("pacman") ; uncomment this line if you haven't already installed 'pacman'</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(metafor, tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>asr_dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://osf.io/qn2af/download"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We’ll also need our function for calculating ARR and its sampling variance because these don’t exist in any current packages.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#' @title arr</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#' @description Calculates the acclimation response ratio (ARR).  </span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param t2_l  Lowest of the two treatment temperatures</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param t1_h  Highest of the two treatment temperatures</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param x1_h  Mean trait value at high temperature</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param x2_l  Mean trait value at low temperature</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param sd1_h Standard deviation of mean trait value at high temperature</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param sd2_l Standard deviation of mean trait value at low temperature</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param n1_h  Sample size at high temperature</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param n2_l  Sample size at low temperature</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>arr <span class="ot">&lt;-</span> <span class="cf">function</span>(x1_h, x2_l, sd1_h, sd2_l, n1_h, n2_l, t1_h, t2_l){</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>        ARR <span class="ot">&lt;-</span> (x1_h <span class="sc">-</span> x2_l)<span class="sc">/</span>(t1_h <span class="sc">-</span> t2_l)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>      V_ARR <span class="ot">&lt;-</span> ((<span class="dv">1</span><span class="sc">/</span>(t1_h <span class="sc">-</span> t2_l))<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span>(sd2_l<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n2_l <span class="sc">+</span> sd1_h<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n1_h))</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="fu">return</span>(<span class="fu">data.frame</span>(ARR, V_ARR))</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="calculating-arr-and-its-sampling-variance" class="level3">
<h3 class="anchored" data-anchor-id="calculating-arr-and-its-sampling-variance">Calculating <span class="math inline">\(ARR\)</span> and It’s Sampling Variance</h3>
<p>Using the <code>arr</code> function above we can now calculate the acclimation response ratio (ARR). Given <span class="citation" data-cites="Pottier2021">Pottier et al. (<a href="#ref-Pottier2021" role="doc-biblioref">2021</a>)</span> were interested in comparing the sexes, they calculated the ARR difference between males and females. To simplify here, we’ll just focus on estimating the ARR for a single sex, females. As such, we’ll calculate our ARR effect size and sampling variance and then sub-set out the data on females.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the effect sizes</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>asr_dat<span class="ot">&lt;-</span>asr_dat <span class="sc">%&gt;%</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>              <span class="fu">mutate</span>(<span class="at">ARR=</span> <span class="fu">arr</span>(<span class="at">x1_h =</span> mean_high, <span class="at">x2_l =</span> mean_low, <span class="at">t1_h =</span> acc_temp_high, <span class="at">t2_l =</span> acc_temp_low, </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">sd1_h =</span> sd_high, <span class="at">sd2_l =</span> sd_low, <span class="at">n1_h =</span> n_high_adj, <span class="at">n2_l =</span> n_low_adj)[,<span class="dv">1</span>], </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">V_ARR =</span> <span class="fu">arr</span>(<span class="at">x1_h =</span>  mean_high, <span class="at">x2_l =</span> mean_low, <span class="at">t1_h =</span> acc_temp_high, <span class="at">t2_l =</span> acc_temp_low, </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>                           <span class="at">sd1_h =</span> sd_high, <span class="at">sd2_l =</span> sd_low, <span class="at">n1_h =</span> n_high_adj, <span class="at">n2_l =</span> n_low_adj)[,<span class="dv">2</span>]) <span class="sc">%&gt;%</span> </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>                <span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">"female"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="fitting-a-multilevel-meta-analytic-model-in-metafor" class="level3">
<h3 class="anchored" data-anchor-id="fitting-a-multilevel-meta-analytic-model-in-metafor">Fitting a Multilevel Meta-analytic Model in <code>metafor</code></h3>
<p>Our data is now ready for analysis! We will use the <code>rma.mv</code> function in <code>metafor</code> to fit our first multilevel meta-analysis model. The model takes the ARR as a response variable (<code>yi</code>) and accounts for it’s sampling variance (<code>V</code> = V_ARR). We are also going to estimate a random effect variance for species, between study and within-study grouping variables to control for non-independence and understand sources driving effect size variability. These are all denoted in the <code>random</code> argument of <code>metafor</code> which takes a list of all the random effects.</p>
<p>You will notice two additional arguments being specified:</p>
<ul>
<li><p>The first, <code>dfs</code>, which calculates the degrees of freedom for the inferential tests in the model. <code>dfs = "contain"</code> will calculate the degrees of freedom based on the lowest clustering level minus 1 (in this case study). Simulations have shown that this is a more robust measure to protect against type I errors <span class="citation" data-cites="Nakagawa2021">(<a href="#ref-Nakagawa2021" role="doc-biblioref">Nakagawa et al., 2022</a>)</span>.</p></li>
<li><p>The second argument, <code>test</code> specifies the test statistic used. <code>metafor</code> defaults to z values based on the standard normal distribution, however, simulations have shown <span class="citation" data-cites="Pappalardo2021">(<a href="#ref-Pappalardo2021" role="doc-biblioref">Pappalardo et al., 2020</a>)</span> and it has been recommended <span class="citation" data-cites="Rosenberg2013b">(<a href="#ref-Rosenberg2013b" role="doc-biblioref">Rosenberg, 2013</a>)</span>, that the t-distribution be used because samples sizes are often small and the true variance of the test is being estimated.</p></li>
</ul>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Multi-level meta-analytic model</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>MLMA <span class="ot">&lt;-</span> metafor<span class="sc">::</span><span class="fu">rma.mv</span>(<span class="at">yi=</span> ARR<span class="sc">~</span> <span class="dv">1</span>, <span class="at">V =</span> V_ARR, </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">method=</span><span class="st">"REML"</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">random=</span><span class="fu">list</span>(<span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>species_ID,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>                               <span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>study_ID,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>                               <span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>es_ID), </span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">dfs =</span> <span class="st">"contain"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">test=</span><span class="st">"t"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data=</span>asr_dat)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(MLMA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Multivariate Meta-Analysis Model (k = 123; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed      factor 
sigma^2.1  0.0008  0.0280     29     no  species_ID 
sigma^2.2  0.0154  0.1241     21     no    study_ID 
sigma^2.3  0.0097  0.0987    123     no       es_ID 

Test for Heterogeneity:
Q(df = 122) = 3941.0055, p-val &lt; .0001

Model Results:

estimate      se    tval  df    pval   ci.lb   ci.ub      
  0.1668  0.0316  5.2857  20  &lt;.0001  0.1010  0.2327  *** 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<section id="what-does-the-model-output-tell-us" class="level4 tabset tabset-fade tabset-pills">
<h4 class="tabset tabset-fade tabset-pills anchored" data-anchor-id="what-does-the-model-output-tell-us"><strong>What does the model output tell us?</strong></h4>
<section id="task" class="level5 tabset tabset-fade tabset-pills">
<h5 class="tabset tabset-fade tabset-pills anchored" data-anchor-id="task">Task</h5>
<blockquote class="blockquote">
<p><strong>What is the overall mean estimate and variance of the model, and how much heterogeneity exist?</strong></p>
</blockquote>
<p><br></p>
</section>
<section id="answer" class="level5 tabset tabset-fade tabset-pills">
<h5 class="tabset tabset-fade tabset-pills anchored" data-anchor-id="answer">Answer</h5>
<blockquote class="blockquote">
<p>We can see from above that the model estimates an <strong>overall meta-analytic mean as 0.167 with a 95% confidence interval of 0.101 to 0.233</strong>. <strong>In other words, for each degree variation in acclimation temperature female heat tolerance changes by an average of 0.167<span class="math inline">\(^{\circ}\)</span>C</strong>.</p>
</blockquote>
<p><br></p>
<blockquote class="blockquote">
<p>We can also see that there’s a significant amount of heterogeneity among our effect size estimates with our <em>Q</em>-test being significant. Some of this heterogeneity seems to be driven by variation among studies, within studies and among species as judged by the variance components of the model. We’ll probe how to dissect and discuss this heterogeneity in later tutorials.</p>
</blockquote>
<p><br></p>
</section>
</section>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references"><strong>References</strong></h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-Hadfield2010" class="csl-entry" role="listitem">
<strong>Hadfield, J.</strong> (2010). MCMC methods for multi-response generalized linear mixed models: The <span>MCMCglmm</span> <span>R</span> package. <em>Journal of Statistical Software</em> <strong>33</strong>, 1–22.
</div>
<div id="ref-NakagawaSantos2012" class="csl-entry" role="listitem">
<strong>Nakagawa, S. and Santos, E. S.</strong> (2012). Methodological issues and advances in biological meta-analysis. <em>Evolutionary Ecology</em> <strong>26</strong>, 1253–1274.
</div>
<div id="ref-Nakagawa2021" class="csl-entry" role="listitem">
<strong>Nakagawa, S., Senior, A. M., Viechtbauer, W. and Noble, D. W. A.</strong> (2022). An assessment of statistical methods for non-independent data in ecological meta-analyses: comment. <em>Ecology</em> <strong>103</strong>, e03490, https://doi.org/10.1002/ecy.3490.
</div>
<div id="ref-Noble2017" class="csl-entry" role="listitem">
<strong>Noble, D. W. A., Lagisz, M., O’Dea, R. E. and Nakagawa, S.</strong> (2017). Non‐independence and sensitivity analyses in ecological and evolutionary meta‐analyses. <em>Molecular Ecology</em> <strong>26</strong>, 2410–2425.
</div>
<div id="ref-Pappalardo2021" class="csl-entry" role="listitem">
<strong>Pappalardo, P., Ogle, K., Hamman, E. A., Hungate, B. A. and Osenberg, C. W.</strong> (2020). Comparing traditional and bayesian approaches to ecological meta-analysis. <em>Methods in Ecology and Evolution</em> <strong>11</strong>, 1286–1295.
</div>
<div id="ref-Pottier2021" class="csl-entry" role="listitem">
<strong>Pottier, P., Burke, S., Drobniak, S. M., Lagisz, M. and Nakagawa, S.</strong> (2021). Sexual (in) equality? A meta‐analysis of sex differences in thermal acclimation capacity across ectotherms. <em>Functional Ecology</em> <strong>35</strong>, 2663–2678, https://doi.org/10.1111/1365–2435.13899.
</div>
<div id="ref-Rosenberg2013b" class="csl-entry" role="listitem">
<strong>Rosenberg, M. S.</strong> (2013). Moment and least squares based approaches to meta-analytic inference. <em>In: Handbook of Meta-Analysis in Ecology and Evolution (eds J. Koricheva, J. Gurevitch &amp; K. Mengersen), Princeton University Press, Princeton, New Jersey.</em> pp 108–124.
</div>
</div>
<p><br></p>
</section>
<section id="session-information" class="level2">
<h2 class="anchored" data-anchor-id="session-information"><strong>Session Information</strong></h2>
<div class="cell">
<div class="cell-output-display">
<p><strong>R version 4.5.1 (2025-06-13)</strong></p>
<p><strong>Platform:</strong> aarch64-apple-darwin20</p>
<p><strong>attached base packages:</strong> <em>stats</em>, <em>graphics</em>, <em>grDevices</em>, <em>utils</em>, <em>datasets</em>, <em>methods</em> and <em>base</em></p>
<p><strong>other attached packages:</strong> <em>magick(v.2.8.7)</em>, <em>equatags(v.0.2.1)</em>, <em>mathjaxr(v.2.0-0)</em>, <em>pander(v.0.6.6)</em>, <em>orchaRd(v.2.1.3)</em>, <em>lubridate(v.1.9.5)</em>, <em>forcats(v.1.0.1)</em>, <em>stringr(v.1.6.0)</em>, <em>dplyr(v.1.2.0)</em>, <em>purrr(v.1.2.1)</em>, <em>readr(v.2.2.0)</em>, <em>tidyr(v.1.3.2)</em>, <em>tibble(v.3.3.1)</em>, <em>ggplot2(v.4.0.2)</em>, <em>tidyverse(v.2.0.0)</em>, <em>flextable(v.0.9.9)</em>, <em>metafor(v.4.8-0)</em>, <em>numDeriv(v.2016.8-1.1)</em>, <em>metadat(v.1.4-0)</em> and <em>Matrix(v.1.7-3)</em></p>
<p><strong>loaded via a namespace (and not attached):</strong> <em>xslt(v.1.5.1)</em>, <em>gtable(v.0.3.6)</em>, <em>xfun(v.0.56)</em>, <em>htmlwidgets(v.1.6.4)</em>, <em>lattice(v.0.22-7)</em>, <em>tzdb(v.0.5.0)</em>, <em>vctrs(v.0.7.1)</em>, <em>tools(v.4.5.1)</em>, <em>generics(v.0.1.4)</em>, <em>curl(v.7.0.0)</em>, <em>pacman(v.0.5.1)</em>, <em>pkgconfig(v.2.0.3)</em>, <em>katex(v.1.5.0)</em>, <em>data.table(v.1.18.2.1)</em>, <em>RColorBrewer(v.1.1-3)</em>, <em>S7(v.0.2.1)</em>, <em>uuid(v.1.2-2)</em>, <em>lifecycle(v.1.0.5)</em>, <em>compiler(v.4.5.1)</em>, <em>farver(v.2.1.2)</em>, <em>textshaping(v.1.0.5)</em>, <em>fontquiver(v.0.2.1)</em>, <em>fontLiberation(v.0.1.0)</em>, <em>htmltools(v.0.5.9)</em>, <em>yaml(v.2.3.12)</em>, <em>pillar(v.1.11.1)</em>, <em>openssl(v.2.3.5)</em>, <em>nlme(v.3.1-168)</em>, <em>fontBitstreamVera(v.0.1.1)</em>, <em>tidyselect(v.1.2.1)</em>, <em>zip(v.2.3.3)</em>, <em>digest(v.0.6.39)</em>, <em>stringi(v.1.8.7)</em>, <em>fastmap(v.1.2.0)</em>, <em>grid(v.4.5.1)</em>, <em>cli(v.3.6.5)</em>, <em>magrittr(v.2.0.4)</em>, <em>withr(v.3.0.2)</em>, <em>gdtools(v.0.4.2)</em>, <em>scales(v.1.4.0)</em>, <em>timechange(v.0.4.0)</em>, <em>rmarkdown(v.2.30)</em>, <em>officer(v.0.6.10)</em>, <em>otel(v.0.2.0)</em>, <em>askpass(v.1.2.1)</em>, <em>ragg(v.1.5.1)</em>, <em>hms(v.1.1.4)</em>, <em>evaluate(v.1.0.5)</em>, <em>knitr(v.1.51)</em>, <em>V8(v.6.0.4)</em>, <em>rlang(v.1.1.7)</em>, <em>Rcpp(v.1.1.1)</em>, <em>glue(v.1.8.0)</em>, <em>xml2(v.1.5.2)</em>, <em>jsonlite(v.2.0.0)</em>, <em>R6(v.2.6.1)</em> and <em>systemfonts(v.1.3.2)</em></p>
</div>
</div>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./metaregression.html" class="pagination-link" aria-label="Multi-level Meta-regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Multi-level Meta-regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./complex-nonind.html" class="pagination-link" aria-label="Complex Non-independence in Meta-analysis">
        <span class="nav-page-text"><span class="chapter-title">Complex Non-independence in Meta-analysis</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb6" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Multi-level Meta-analysis</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(metafor, flextable, tidyverse, orchaRd, pander, mathjaxr, equatags, magick)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">digits=</span><span class="dv">3</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="fu">## **Introduction to Multi-level Meta-analysis**</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>Ecological and evolutionary meta-analysis more often than not need much more sophisticated multilevel meta-analytic models <span class="co">[</span><span class="ot">@NakagawaSantos2012; @Hadfield2010; @Noble2017</span><span class="co">]</span> compared with <span class="co">[</span><span class="ot">random effect models</span><span class="co">](https://daniel1noble.github.io/meta-workshop/fixed-vs-random)</span> to analyse data. Biological data from field and lab-based experiments are highly structured -- many studies could be done on the same species or they could be done by the same lab group or student sharing similar methodology <span class="co">[</span><span class="ot">@Noble2017; @NakagawaSantos2012</span><span class="co">]</span>. In addition, we might have many effect size estimates from a single study because many traits are measured, or many treatments are applied <span class="co">[</span><span class="ot">@Noble2017</span><span class="co">]</span>. This adds complexity to the data set and also results in special types of non-independence that are somewhat unique to meta-analysis -- especially when using contrast-based effect sizes like Hedges' g, log response ratios, log odds ratios etc <span class="co">[</span><span class="ot">@Noble2017</span><span class="co">]</span>. </span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>In the past, complex non-independence was often dealt with by: **1)** conducting separate meta-analyses on subsets of non-independent data sets, usually using random effect models; **2)** taking one or only a subset of effect size estimates from a single study to reduce non-independence; and/or **3)** averaging effect size estimates from a single study and modelling the average [@NakagawaSantos2012]. **These approaches can be problematic because disposing of useful effect size data will result in a loss of statistical power or even inflated Type I error rates if average effect size estimates were not calculated accounting for non-independence [@Nakagawa2021]**. Furthermore, removing effect size estimates from an analysis prevents estimation of biological and methodologically relevant information that can help shape the field <span class="co">[</span><span class="ot">@NakagawaSantos2012; @Nakagawa2021</span><span class="co">]</span>. While the above approaches could still be useful at times, where possible, we recommend you model all available data <span class="co">[</span><span class="ot">@Nakagawa2021; @Noble2017; @NakagawaSantos2012</span><span class="co">]</span>.</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>In the next series of tutorials we'll overview multilevel meta-analytic models and discuss common forms of non-independence and how to deal with these challenges. Here, we'll first focus on simple multilevel meta-analysis models and how to interpret these. We'll then work our way up to including more complex forms of non-independence, such as phylogenetic meta-analysis and accounting for shared control. Technically, all these sources could be built into a single model but will require a substantial amount of data. Sometimes it will not be possible to deal with all sources of non-independence, in which case it's important to conduct sensitivity analyses to understand how your conclusions and inferences are affected by the analytic decisions made <span class="co">[</span><span class="ot">@Noble2017</span><span class="co">]</span>. **Strong justification for your choices is always essential**.</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a><span class="fu">## **Simple Multilevel Meta-analytic Model**</span></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Recall</span><span class="co">](https://daniel1noble.github.io/meta-workshop/fixed-vs-random)</span> that a random effects model is defined as follows: </span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>y_{i} = \mu + s_{i} + m_{i} <span class="sc">\\</span></span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>m_{i} \sim N(0, v_{i}) <span class="sc">\\</span></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>s_{i} \sim N(0, \tau^2)</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>In this model, $y_{i}$ is the *i*th effect size estimate and $m_{i}$ is the sampling error (deviation from $\mu$) for effect size *i*. Given that we have a single effect size estimate from each study we can include $s_{i}$, which is the study specific deviation, and this gives us an ability to estimate a "residual" variance from this model. That's because after we remove the known sampling variance there is likely to be "extra" variability among effect sizes at the effect/study level (in this case these are confounded because we have one effect / study). We can estimate that explicitly which is what we are doing here. **The challenge with having a single effect estimate per study is that the within and between study variances are confounded**. In other words, we cannot estimate both. </span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>More commonly, we can extract many (sometimes a lot) effect size estimates from a single study. In such case, we no longer have a single effect size estimate from a given study but a whole bunch of effects from a single study. These could be effects from different experimental treatments, at different time points or on different traits. These effects are not independent of each other and there is likely a substantial amount of within study variation in addition to the across study variation <span class="co">[</span><span class="ot">@NakagawaSantos2012</span><span class="co">]</span>. We can now estimate these two sources of variability explicitly turning our model into what is the simplest form of a multilevel meta-analytic model: </span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>y_{i,j} = \mu + s_{j} + e_{i,j} + m_{i,j} <span class="sc">\\</span></span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>m_{i,j} \sim N(0, v_{i,j}) <span class="sc">\\</span></span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>s_{j} \sim N(0, \tau^2) <span class="sc">\\</span></span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>e_{i,j} \sim N(0, \sigma_{e}^2)</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a>You'll notice that the notation changes slightly -- $y_{i,j}$ is now the *i* effect size from study *j* and $m_{i,j}$ is effect size *i*'s known sampling variance from study *j*. $s_{j}$ is now the study specific effect, *j*, applied to the *i*th effect size, where *j* = 1,...,$N_{studies}$. We have also now added a random effect ($e_{i,j}$) to the model. **$e_{i,j}$ is the effect-size-specific (within study) effect. This is often referred to as a 'residual' effect [@NakagawaSantos2012] and is used to estimate a residual variance**. </span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a><span class="fu">## **Building more Complex Multilevel Meta-analytic Models**</span></span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a>In reality, we may also have lots of studies on a specific set of species. For example, common or economically important species, like Salmon, Trout or lab model organisms like Zebrafish might be over-represented in the data set. This adds an additional level of structure to our data. We can account for species in this model by adding another random effect that captures the similarities between effect size estimates from the same species. As such, we can expand our multilevel model as follows:</span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a>y_{i,j,k} = \mu + s_{j} + spp_{k} + e_{i,j,k} + m_{i,j,k} <span class="sc">\\</span></span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a>m_{i,j,k} \sim N(0, v_{i,j}) <span class="sc">\\</span></span>
<span id="cb6-52"><a href="#cb6-52" aria-hidden="true" tabindex="-1"></a>s_{j} \sim N(0, \tau^2) <span class="sc">\\</span></span>
<span id="cb6-53"><a href="#cb6-53" aria-hidden="true" tabindex="-1"></a>spp_{k} \sim N(0, \sigma_{k}^2) <span class="sc">\\</span></span>
<span id="cb6-54"><a href="#cb6-54" aria-hidden="true" tabindex="-1"></a>e_{i,j,k} \sim N(0, \sigma_{e}^2)</span>
<span id="cb6-55"><a href="#cb6-55" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-56"><a href="#cb6-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-57"><a href="#cb6-57" aria-hidden="true" tabindex="-1"></a>Here, $y_{i,j, k}$ is now the *i*th effect size from study *j* and species *k*. $m_{i,j, k}$ is effect size *i*'s known sampling variance from study *j* and species *k*. $e_{i,j, k}$ is the effect-size-specific (within study) applied to each effect *i* from study *j* and species *k*. $s_{j}$ is still the study specific effect, *j*, applied to the *i*th effect size, where *j* = 1,...,$N_{studies}$, but now $spp_{k}$ is the species specific effect, *k*, applied to the *i*th effect size, where *k* = 1,...,$N_{species}$. </span>
<span id="cb6-58"><a href="#cb6-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-59"><a href="#cb6-59" aria-hidden="true" tabindex="-1"></a>As you can imagine, the notation can get quite complicated the more levels you add. As such, a simplification of the above model notation that you might read <span class="co">[</span><span class="ot">e.g., @NakagawaSantos2012; @Noble2017</span><span class="co">]</span> is as follows:</span>
<span id="cb6-60"><a href="#cb6-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-61"><a href="#cb6-61" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-62"><a href="#cb6-62" aria-hidden="true" tabindex="-1"></a>y_{i} = \mu + s_{j<span class="co">[</span><span class="ot">i</span><span class="co">]</span>} + spp_{k<span class="co">[</span><span class="ot">i</span><span class="co">]</span>} + e_{i} + m_{i} <span class="sc">\\</span></span>
<span id="cb6-63"><a href="#cb6-63" aria-hidden="true" tabindex="-1"></a>m_{i} \sim N(0, v_{i}) <span class="sc">\\</span></span>
<span id="cb6-64"><a href="#cb6-64" aria-hidden="true" tabindex="-1"></a>s_{j} \sim N(0, \tau^2) <span class="sc">\\</span></span>
<span id="cb6-65"><a href="#cb6-65" aria-hidden="true" tabindex="-1"></a>spp_{k} \sim N(0, \sigma_{k}^2) <span class="sc">\\</span></span>
<span id="cb6-66"><a href="#cb6-66" aria-hidden="true" tabindex="-1"></a>e_{i} \sim N(0, \sigma_{e}^2)</span>
<span id="cb6-67"><a href="#cb6-67" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-68"><a href="#cb6-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-69"><a href="#cb6-69" aria-hidden="true" tabindex="-1"></a><span class="fu">## **Fitting a Multi-level Meta-analytic Model**</span></span>
<span id="cb6-70"><a href="#cb6-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-71"><a href="#cb6-71" aria-hidden="true" tabindex="-1"></a><span class="al">![](./figs/pottier.png)</span></span>
<span id="cb6-72"><a href="#cb6-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-73"><a href="#cb6-73" aria-hidden="true" tabindex="-1"></a>To demonstrate how to fit a multilevel meta-analytic model similar to the one discussed above we'll turn to a <span class="co">[</span><span class="ot">familiar example</span><span class="co">](https://daniel1noble.github.io/meta-workshop/nuis-het)</span> by @Pottier2021, who used the acclimation response ratio (ARR) to analyse thermal acclimation responses on $CT_{max}$ and how this differs between the sexes. We'll keep it simple for the moment and focus exclusively on a single sex. </span>
<span id="cb6-74"><a href="#cb6-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-75"><a href="#cb6-75" aria-hidden="true" tabindex="-1"></a><span class="fu">### Download Data and Functions for $ARR$</span></span>
<span id="cb6-76"><a href="#cb6-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-77"><a href="#cb6-77" aria-hidden="true" tabindex="-1"></a>We'll download the raw data from the paper again. We'll also need to load the <span class="in">`metafor`</span> package to fit our models and the tidyverse package for processing the data.</span>
<span id="cb6-78"><a href="#cb6-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-81"><a href="#cb6-81" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-82"><a href="#cb6-82" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("pacman") ; uncomment this line if you haven't already installed 'pacman'</span></span>
<span id="cb6-83"><a href="#cb6-83" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(metafor, tidyverse)</span>
<span id="cb6-84"><a href="#cb6-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-85"><a href="#cb6-85" aria-hidden="true" tabindex="-1"></a>asr_dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://osf.io/qn2af/download"</span>)</span>
<span id="cb6-86"><a href="#cb6-86" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-87"><a href="#cb6-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-88"><a href="#cb6-88" aria-hidden="true" tabindex="-1"></a>We'll also need our function for calculating ARR and its sampling variance because these don't exist in any current packages. </span>
<span id="cb6-89"><a href="#cb6-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-90"><a href="#cb6-90" aria-hidden="true" tabindex="-1"></a><span class="in">```{r ARRfunc}</span></span>
<span id="cb6-91"><a href="#cb6-91" aria-hidden="true" tabindex="-1"></a><span class="co">#' @title arr</span></span>
<span id="cb6-92"><a href="#cb6-92" aria-hidden="true" tabindex="-1"></a><span class="co">#' @description Calculates the acclimation response ratio (ARR).  </span></span>
<span id="cb6-93"><a href="#cb6-93" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param t2_l  Lowest of the two treatment temperatures</span></span>
<span id="cb6-94"><a href="#cb6-94" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param t1_h  Highest of the two treatment temperatures</span></span>
<span id="cb6-95"><a href="#cb6-95" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param x1_h  Mean trait value at high temperature</span></span>
<span id="cb6-96"><a href="#cb6-96" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param x2_l  Mean trait value at low temperature</span></span>
<span id="cb6-97"><a href="#cb6-97" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param sd1_h Standard deviation of mean trait value at high temperature</span></span>
<span id="cb6-98"><a href="#cb6-98" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param sd2_l Standard deviation of mean trait value at low temperature</span></span>
<span id="cb6-99"><a href="#cb6-99" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param n1_h  Sample size at high temperature</span></span>
<span id="cb6-100"><a href="#cb6-100" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param n2_l  Sample size at low temperature</span></span>
<span id="cb6-101"><a href="#cb6-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-102"><a href="#cb6-102" aria-hidden="true" tabindex="-1"></a>arr <span class="ot">&lt;-</span> <span class="cf">function</span>(x1_h, x2_l, sd1_h, sd2_l, n1_h, n2_l, t1_h, t2_l){</span>
<span id="cb6-103"><a href="#cb6-103" aria-hidden="true" tabindex="-1"></a>        ARR <span class="ot">&lt;-</span> (x1_h <span class="sc">-</span> x2_l)<span class="sc">/</span>(t1_h <span class="sc">-</span> t2_l)</span>
<span id="cb6-104"><a href="#cb6-104" aria-hidden="true" tabindex="-1"></a>      V_ARR <span class="ot">&lt;-</span> ((<span class="dv">1</span><span class="sc">/</span>(t1_h <span class="sc">-</span> t2_l))<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span>(sd2_l<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n2_l <span class="sc">+</span> sd1_h<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n1_h))</span>
<span id="cb6-105"><a href="#cb6-105" aria-hidden="true" tabindex="-1"></a><span class="fu">return</span>(<span class="fu">data.frame</span>(ARR, V_ARR))</span>
<span id="cb6-106"><a href="#cb6-106" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-107"><a href="#cb6-107" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-108"><a href="#cb6-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-109"><a href="#cb6-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-110"><a href="#cb6-110" aria-hidden="true" tabindex="-1"></a><span class="fu">### Calculating $ARR$ and It's Sampling Variance</span></span>
<span id="cb6-111"><a href="#cb6-111" aria-hidden="true" tabindex="-1"></a>Using the <span class="in">`arr`</span> function above we can now calculate the acclimation response ratio (ARR). Given @Pottier2021 were interested in comparing the sexes, they calculated the ARR difference between males and females. To simplify here, we'll just focus on estimating the ARR for a single sex, females. As such, we'll calculate our ARR effect size and sampling variance and then sub-set out the data on females.</span>
<span id="cb6-112"><a href="#cb6-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-115"><a href="#cb6-115" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-116"><a href="#cb6-116" aria-hidden="true" tabindex="-1"></a><span class="co">#| tidy: true</span></span>
<span id="cb6-117"><a href="#cb6-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-118"><a href="#cb6-118" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the effect sizes</span></span>
<span id="cb6-119"><a href="#cb6-119" aria-hidden="true" tabindex="-1"></a>asr_dat<span class="ot">&lt;-</span>asr_dat <span class="sc">%&gt;%</span> </span>
<span id="cb6-120"><a href="#cb6-120" aria-hidden="true" tabindex="-1"></a>              <span class="fu">mutate</span>(<span class="at">ARR=</span> <span class="fu">arr</span>(<span class="at">x1_h =</span> mean_high, <span class="at">x2_l =</span> mean_low, <span class="at">t1_h =</span> acc_temp_high, <span class="at">t2_l =</span> acc_temp_low, </span>
<span id="cb6-121"><a href="#cb6-121" aria-hidden="true" tabindex="-1"></a>                              <span class="at">sd1_h =</span> sd_high, <span class="at">sd2_l =</span> sd_low, <span class="at">n1_h =</span> n_high_adj, <span class="at">n2_l =</span> n_low_adj)[,<span class="dv">1</span>], </span>
<span id="cb6-122"><a href="#cb6-122" aria-hidden="true" tabindex="-1"></a>                     <span class="at">V_ARR =</span> <span class="fu">arr</span>(<span class="at">x1_h =</span>  mean_high, <span class="at">x2_l =</span> mean_low, <span class="at">t1_h =</span> acc_temp_high, <span class="at">t2_l =</span> acc_temp_low, </span>
<span id="cb6-123"><a href="#cb6-123" aria-hidden="true" tabindex="-1"></a>                           <span class="at">sd1_h =</span> sd_high, <span class="at">sd2_l =</span> sd_low, <span class="at">n1_h =</span> n_high_adj, <span class="at">n2_l =</span> n_low_adj)[,<span class="dv">2</span>]) <span class="sc">%&gt;%</span> </span>
<span id="cb6-124"><a href="#cb6-124" aria-hidden="true" tabindex="-1"></a>                <span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">"female"</span>)</span>
<span id="cb6-125"><a href="#cb6-125" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-126"><a href="#cb6-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-127"><a href="#cb6-127" aria-hidden="true" tabindex="-1"></a><span class="fu">### Fitting a Multilevel Meta-analytic Model in `metafor`</span></span>
<span id="cb6-128"><a href="#cb6-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-129"><a href="#cb6-129" aria-hidden="true" tabindex="-1"></a>Our data is now ready for analysis! We will use the <span class="in">`rma.mv`</span> function in <span class="in">`metafor`</span> to fit our first multilevel meta-analysis model. The model takes the ARR as a response variable (<span class="in">`yi`</span>) and accounts for it's sampling variance (<span class="in">`V`</span> = V_ARR). We are also going to estimate a random effect variance for species, between study and within-study grouping variables to control for non-independence and understand sources driving effect size variability. These are all denoted in the <span class="in">`random`</span> argument of <span class="in">`metafor`</span> which takes a list of all the random effects. </span>
<span id="cb6-130"><a href="#cb6-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-131"><a href="#cb6-131" aria-hidden="true" tabindex="-1"></a>You will notice two additional arguments being specified: </span>
<span id="cb6-132"><a href="#cb6-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-133"><a href="#cb6-133" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>The first, <span class="in">`dfs`</span>, which calculates the degrees of freedom for the inferential tests in the model. <span class="in">`dfs = "contain"`</span> will calculate the degrees of freedom based on the lowest clustering level minus 1 (in this case study). Simulations have shown that this is a more robust measure to protect against type I errors <span class="co">[</span><span class="ot">@Nakagawa2021</span><span class="co">]</span>. </span>
<span id="cb6-134"><a href="#cb6-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-135"><a href="#cb6-135" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>The second argument, <span class="in">`test`</span> specifies the test statistic used. <span class="in">`metafor`</span> defaults to z values based on the standard normal distribution, however, simulations have shown <span class="co">[</span><span class="ot">@Pappalardo2021</span><span class="co">]</span> and it has been recommended <span class="co">[</span><span class="ot">@Rosenberg2013b</span><span class="co">]</span>, that the t-distribution be used because samples sizes are often small and the true variance of the test is being estimated. </span>
<span id="cb6-136"><a href="#cb6-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-139"><a href="#cb6-139" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-140"><a href="#cb6-140" aria-hidden="true" tabindex="-1"></a><span class="co"># Multi-level meta-analytic model</span></span>
<span id="cb6-141"><a href="#cb6-141" aria-hidden="true" tabindex="-1"></a>MLMA <span class="ot">&lt;-</span> metafor<span class="sc">::</span><span class="fu">rma.mv</span>(<span class="at">yi=</span> ARR<span class="sc">~</span> <span class="dv">1</span>, <span class="at">V =</span> V_ARR, </span>
<span id="cb6-142"><a href="#cb6-142" aria-hidden="true" tabindex="-1"></a>                   <span class="at">method=</span><span class="st">"REML"</span>,</span>
<span id="cb6-143"><a href="#cb6-143" aria-hidden="true" tabindex="-1"></a>                   <span class="at">random=</span><span class="fu">list</span>(<span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>species_ID,</span>
<span id="cb6-144"><a href="#cb6-144" aria-hidden="true" tabindex="-1"></a>                               <span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>study_ID,</span>
<span id="cb6-145"><a href="#cb6-145" aria-hidden="true" tabindex="-1"></a>                               <span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>es_ID), </span>
<span id="cb6-146"><a href="#cb6-146" aria-hidden="true" tabindex="-1"></a>                   <span class="at">dfs =</span> <span class="st">"contain"</span>,</span>
<span id="cb6-147"><a href="#cb6-147" aria-hidden="true" tabindex="-1"></a>                   <span class="at">test=</span><span class="st">"t"</span>,</span>
<span id="cb6-148"><a href="#cb6-148" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data=</span>asr_dat)</span>
<span id="cb6-149"><a href="#cb6-149" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(MLMA)</span>
<span id="cb6-150"><a href="#cb6-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-151"><a href="#cb6-151" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-152"><a href="#cb6-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-153"><a href="#cb6-153" aria-hidden="true" tabindex="-1"></a><span class="fu">#### **What does the model output tell us?** {.tabset .tabset-fade .tabset-pills} </span></span>
<span id="cb6-154"><a href="#cb6-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-155"><a href="#cb6-155" aria-hidden="true" tabindex="-1"></a><span class="fu">##### Task {.tabset .tabset-fade .tabset-pills} </span></span>
<span id="cb6-156"><a href="#cb6-156" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;**What is the overall mean estimate and variance of the model, and how much heterogeneity exist?** </span></span>
<span id="cb6-157"><a href="#cb6-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-158"><a href="#cb6-158" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb6-159"><a href="#cb6-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-160"><a href="#cb6-160" aria-hidden="true" tabindex="-1"></a><span class="fu">##### Answer {.tabset .tabset-fade .tabset-pills} </span></span>
<span id="cb6-161"><a href="#cb6-161" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;We can see from above that the model estimates an **overall meta-analytic mean as `r MLMA$b` with a 95% confidence interval of `r MLMA$ci.lb` to `r MLMA$ci.ub`**. **In other words, for each degree variation in acclimation temperature female heat tolerance changes by an average of `r MLMA$b`$^{\circ}$C**. </span></span>
<span id="cb6-162"><a href="#cb6-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-163"><a href="#cb6-163" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb6-164"><a href="#cb6-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-165"><a href="#cb6-165" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;We can also see that there's a significant amount of heterogeneity among our effect size estimates with our *Q*-test being significant. Some of this heterogeneity seems to be driven by variation among studies, within studies and among species as judged by the variance components of the model. We'll probe how to dissect and discuss this heterogeneity in later tutorials. </span></span>
<span id="cb6-166"><a href="#cb6-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-167"><a href="#cb6-167" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb6-168"><a href="#cb6-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-169"><a href="#cb6-169" aria-hidden="true" tabindex="-1"></a><span class="fu">## **References**</span></span>
<span id="cb6-170"><a href="#cb6-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-171"><a href="#cb6-171" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">div</span><span class="ot"> id</span><span class="op">=</span><span class="st">"refs"</span><span class="dt">&gt;&lt;/</span><span class="kw">div</span><span class="dt">&gt;</span></span>
<span id="cb6-172"><a href="#cb6-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-173"><a href="#cb6-173" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb6-174"><a href="#cb6-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-175"><a href="#cb6-175" aria-hidden="true" tabindex="-1"></a><span class="fu">## **Session Information**</span></span>
<span id="cb6-176"><a href="#cb6-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-179"><a href="#cb6-179" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-180"><a href="#cb6-180" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: sessioninfo</span></span>
<span id="cb6-181"><a href="#cb6-181" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb6-182"><a href="#cb6-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-183"><a href="#cb6-183" aria-hidden="true" tabindex="-1"></a><span class="fu">pander</span>(<span class="fu">sessionInfo</span>(), <span class="at">locale =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-184"><a href="#cb6-184" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
</code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>